### ISSUE TITLE
Discover tests in SRPM

### ISSUE THREAD

**Issue by mgrabovsky** [teemtee/tmt#1037]
I have [a plan](https://src.fedoraproject.org/rpms/python-cachelib/blob/31e9ed57c352b194aba4ed2b1ddb308c4862dadf/f/plans/upstream.fmf) which runs upstream tests for a package I maintain in Fedora. The way I do this at the moment is I define a single test in the plan which clones the upstream repository, checks out the pertaining tag and runs the tests using Pytest.

This works fine for the moment. However, the first two steps appear somewhat superfluous since the tests are bundled in the source tarball (and hence in the SRPM). Moreover, the tag name changes with each release so I have to remember to update it every time.

Is it possible to discover and run tests bundled in the tarbal/SRPM? If not, would it make sense to implement this feature?

**Comment by mgrabovsky** [comment]
The second option is closer to what I want/need. I have no control over the upstream (beyond suggesting a patch) so I suppose I need to store the metadata in dist-git.

**Comment by psss** [comment]
Actually, currently it's also possible to enable the `dist-git-source` feature and use test discovered from the local git repo to access the unpacked tarball. I gave it a quick try and it [seems to be working](https://src.fedoraproject.org/rpms/python-cachelib/pull-request/4) as expected.

@lukaszachy, now I'm not sure whether we should fix #978 ;-)

**Comment by psss** [comment]
> discover tests elsewhere but extract tarball/SRPM to a known directory so its content can be used in tests (or other steps)

Btw, what about creating a symlink `source --> tarbal-1.2.3` to make the directory more "known"?

**Comment by lukaszachy** [comment]
> Actually, currently it's also possible to enable the `dist-git-source` feature and use test discovered from the local git repo to access the unpacked tarball. I gave it a quick try and it [seems to be working](https://src.fedoraproject.org/rpms/python-cachelib/pull-request/4) as expected.
> 
> @lukaszachy, now I'm not sure whether we should fix #978 ;-)

We have to - otherwise "name" is corrupted :) but dist-git-init:false should keep current behaviour

> Btw, what about creating a symlink source --> tarbal-1.2.3 to make the directory more "known"?

Well, tarball doesn't need to contain subdir so it might not be possible.

**Comment by lukaszachy** [comment]
I believe we fixed this in #1128 (part of 1.14.0 release which got pushed to fedora updates repo today).

If not, please reopen and hint what is missing. Thank you.
