### ISSUE TITLE
Missing overall result: fail on test case timeout

### ISSUE THREAD

**Issue by KwisatzHaderach** [teemtee/tmt#1060]
If a test case in test suite fails due to timeout there is no overall result for that test case and thus it can't be found easily.
The run just reports n tests passed and 1 error and you basically have to match list of tests with results with tests that were executed to find the one offending case to investigate.

Maybe this could also be fixed by generating some overall result report so I don't have to grep OVERALL from the log to get the list of failing cases.

**Comment by lukaszachy** [comment]
```
$ tmt run -a provision -h local
/var/tmp/tmt/run-176
...
    execute
        how: tmt
        summary: 1 test executed
    report
        how: display
        summary: 1 error

$ tmt run --id /var/tmp/tmt/run-176 report -v
/var/tmp/tmt/run-176

/plans/default
    report
        how: display
            errr / (timeout)
        summary: 1 error

total: 1 error


```

**Comment by KwisatzHaderach** [comment]
Right, now I don't understand why I filled this in the first place because the verbosity is obvious.
Also -v can be added to the `run` as well, no need for specifying it extra for report.
