### ISSUE TITLE
dry-run in provision --how=connect leads to error

### ISSUE THREAD

**Issue by sbertramrh** [teemtee/tmt#1064]
This is dry mode so not an urgent thing but I assume because its not a real run the remote tmt directory structure is not created and so rsync fails.

 tmt run --id remote-001 --all provision --how connect --guest ampere-mtsnow-altra-08.khw4.lab.eng.bos.redhat.com --dry
/var/tmp/tmt/remote-001

/plans/kselftests
    discover
        how: fmf
        directory: /home/sbertram/gitstuff/kernel
        path: selftests/wrapper
        tests: rhivos
        summary: 1 test selected
    provision
        how: connect
        guest: ampere-mtsnow-altra-08.khw4.lab.eng.bos.redhat.com
        user: root
        key: not provided
        summary: 1 guest provisioned
    prepare
        how: shell
        name: Enable Repos
        overview: 1 script found
        how: install
        name: Packages
        package: tar, yum, autoconf and 15 more
        how: shell
        name: sendip rpm
        overview: 1 script found
        how: install
        summary: Install recommended packages
        name: recommends
        package: netcat, traceroute, man and 10 more
    finish
        summary: 0 tasks completed

stderr (3/3 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rsync: [sender] link_stat "/var/tmp/tmt/remote-001/plans/kselftests/data" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1663) [Receiver=3.1.3]
rsync: [Receiver] write error: Broken pipe (32)

Failed to run command 'rsync -Rrz --links --safe-links --protect-args -e ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -S /run/user/4202847/tmt/tmp31__du98 root@ampere-mtsnow-altra-08.khw4.lab.eng.bos.redhat.com:/var/tmp/tmt/remote-001/plans/kselftests/data /'. Reason: Command returned '23'.

**Comment by psss** [comment]
Yes, during dry run all `guest.push()` and `guest.pull()` actions should be ignored. Should be very easy to fix. Maybe some of the new contributors would be interested?

**Comment by idorax** [comment]
@psss, I'd like to fix it to get familiar with TMT.

**Comment by lukaszachy** [comment]
Just FYI: simpler reproducer (uses virtual provisioner to get local VM, any VM/remote machine is enough)
0. fresh directory
1. tmt init -t base
2. tmt run --id ownVM plans --default provision -vvv -h virtual --connection system
3. Note IP from the step above
4. tmt run -a provision -h connect -g <IP> --dry

To stop and remove machine created in 2. step `tmt run --id ownVM plans --default finish`

**Comment by idorax** [comment]
@sbertramrh, would you please show me the detailed steps about how to reproduce this issue? I failed to reproduce it according to @lukaszachy 's suggestion.

```bash
$ export GUEST=hpe-dl380pgen8-02-vm-7.hpe2.lab.eng.bos.redhat.com
$ tmt run --id remote-001 --all provision -vvv --how connect --guest $GUEST --dry
/var/tmp/tmt/remote-001

/plans/example
    discover
        status: done
        summary: 1 test selected
    provision
        status: done
        summary: 1 guest provisioned
    prepare
        status: done
        summary: 0 preparations applied
    execute
        status: done
        summary: 1 test executed
    report
        how: display
        summary: 1 error
    finish
        status: done
        summary: 0 tasks completed

total: 1 error
```

**Comment by sbertramrh** [comment]
@idorax The only other details I can provide would be the actual test. I have sent you a separate email with that test case. Also, looking at your test run output, I think you are running against the same output directory and not cleaning it after your test. This will in most cases cause an error and not run properly. --id forces tmt to run the test from the same location So either clean it after each run or point --id to another directory.

Also can you do a clean run of the test you are running and lets see the output, this is without --dry. I want to make sure the test is running successfully. Thanks.

**Comment by lukaszachy** [comment]
@idorax What tmt version do you have? Either 1.11 or current github main branch should fail

```
$ tmt run --id remote-001 --all provision -vvv --how connect --guest 192.168.122.95 --dry
/var/tmp/tmt/remote-001

/plans/example
    discover
        how: fmf
        directory: /tmp/r_152128_mAc
        summary: 1 test selected
    provision
        how: connect
        order: 50
        guest: 192.168.122.95
        user: root
        key: not provided
        summary: 1 guest provisioned
    prepare
        how: install
        summary: Install required packages
        name: requires
        package: beakerlib
    
        fail: Failed to pull workdir from the guest. This usually means that login as 'root' to the guest does not work.
    finish
        summary: 0 tasks completed

stderr (3/3 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rsync: link_stat "/var/tmp/tmt/remote-001/plans/example/data" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1816) [Receiver=3.2.3]
rsync: [Receiver] write error: Broken pipe (32)

Failed to run command 'rsync -Rrz --links --safe-links --protect-args -e ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -S /run/user/17062/tmt/tmpn25550cz root@192.168.122.95:/var/tmp/tmt/remote-001/plans/example/data /'. Reason: Command returned '23'.

```

**Comment by idorax** [comment]
Well, my tmt looks pretty old, its version is `1.8.0`.  I'll try 1.11 later.
```
# tmt --version
tmt version: 1.8.0 (0577fe6)
```

**Comment by idorax** [comment]
If  `--dry` is specified, I found that `self.opt('dry')` is `True` in `guest.push()` but it is `None` in `guest.pull()`.  

So currently I added a property `self.dry` to `__init__()` in class `class Guest(tmt.utils.Common)`:
* https://github.com/teemtee/tmt/blob/main/tmt/steps/provision/__init__.py#L224
```patch
@@ -252,6 +252,8 @@ class Guest(tmt.utils.Common):
         # Initialize role, it will be overridden by load() if specified
         self.role = None
         self.load(data)
+        # Save 'dry' flag in case it's gone
+        self.dry = self.opt('dry')
```

Then in both `guest.push()` and `guest.pull()`,  such code is added to fix this defect.
```patch
+        # Skip to pull in dry mode
+        if self.dry:
+            return
```

@lukaszachy and @sbertramrh, please help to review, thanks!

**Comment by thrix** [comment]
ups ....

> If --dry is specified, I found that self.opt('dry') is True in guest.push() but it is None in guest.pull().

this stinks, it will need to be investigated

**Comment by lukaszachy** [comment]
Ouch. Reading code and command line properly - the `--dry` is parameter of 'provision' not of the whole run.
For (see that --dry moved from end of line just after run) `tmt run --dry --id remote-001 --all provision --how connect --guest 192.168.122.203`
```(Pdb) p guest.opt('dry')
True
(Pdb) p guest_copy.opt('dry')
True
```

**Comment by FrNecas** [comment]
Yes, that looks like it. So only provision was run in dry mode (so nothing was provisioned) but the other steps tried to use the provisioned guest.

The `guest_copy` thing was introduced so that guest uses options of the currently running step. Previously, it was strictly tied to provision so that when `tmt run prepare -vvv` was used, no verbose output would be seen from the guest which was rather confusing. But as a side-effect, when only provision has `--dry` this means that after creating a copy and changing the parent to prepare, guest no longer sees the `dry` mode and hence tries to do something. This may be tricky to solve (at least I currently don't see a straight forward solution)

**Comment by lukaszachy** [comment]
Indeed - guest.push sees 'dry' is bug (strictly speaking). However - Is there a _valid_ use case when one can run --dry for provision but not for later steps? Imho it doesn't make sense, no provision -> no SUT to run steps on. 
IMO dry should be global option. Or is the expected usage to skip over one step (so one doesn't need to enumerate rest?)

**Comment by psss** [comment]
Yes, `--dry` should not be used for skipping steps when not needed or when already done, for this `--skip` should be used. And I don't see any real life use case to run only `provision --dry` while attempting to perform other actions without a provisioned guest. A single `--dry` option for the whole `tmt run` as suggested by @lukaszachy makes probably the most sense to me.

**Comment by psss** [comment]
> IMO dry should be global option. Or is the expected usage to skip over one step

Thinking about it a bit more I (probably) found a relatively reasonable use cases for using `--dry` with a single step:

 * It could make sense to run the `prepare` step in dry mode (just quickly show me which required packages would be installed or which ansible playbooks would be applied)
 * For long test scripts I can imagine doing an `execute --dry` to quickly double check that the right command line is used to run the tests and the right set of environment variables is provided to it

@lukaszachy, @FrNecas, does it make sense? If so, then perhaps using the `guest.ready()` method which was discussed on today's hacking session could be a better solution.

**Comment by lukaszachy** [comment]
It does.

**Comment by idorax** [comment]
@lukaszachy, currently class Guest doesn't have a method `ready()`, do we need to add one, right?

**Comment by lukaszachy** [comment]
Exactly - And ideally have it set properly: let it be true when guest lives (start() or wake(), I'm not sure) and false once guest is not available (stop() maybe)

**Comment by psss** [comment]
Yes, `Guest.ready()` should return `True` after `start()` and/or `wake()` methods are completed and return `False` after `stop()` is called or before the guest is fully initialized. Perhaps we could use an internal `guest._ready` attribute for storing the current status.

**Comment by idorax** [comment]
@psss, @lukaszachy and @FrNecas, if I run `tmt run --dry` `--id remote-001 --all provision --how connect --guest GuestVM`, the output looks like:
```bash
$ tmt run --dry --id remote-001 --all provision --how connect --guest GuestVM
/var/tmp/tmt/remote-001

/plans/example
    discover
        how: fmf
        directory: /home/huanli/dev/1064/foo
        summary: 0 tests selected
    provision
        how: connect
        guest: GuestVM
        user: root
        key: not provided
        summary: 1 guest provisioned
    prepare
        summary: 0 preparations applied
    execute
        how: tmt
        summary: 0 tests executed
    report
        how: display
        summary: no results found
    finish
        summary: 0 tasks completed

total: no results found
```

Is this expected output? If yes, looks patch https://github.com/teemtee/tmt/pull/1094/commits/6bad57278c4921a5898bc693e9277be408251b17 fixed this issue because with the patch, `tmt run --id remote-001 --all provision --dry `    `--how connect --guest GuestVM` has the same output to `tmt run --dry `   `--id remote-001 --all provision --how connect --guest GuestVM`. 

Sorry I'm confused with the solution above about `Guest.ready()` because if we use `tmt run --dry ...`, `--dry` is a global option as a matter of fact.  Please explain more details if we should have the solution above, thanks!
* https://github.com/teemtee/tmt/blob/main/tmt/cli.py#L255
```python
@force_dry
def run(context, id_, **kwargs):
    """ Run test steps. """
    # Initialize
    run = tmt.Run(id_, context.obj.tree, context=context)
...<snip>...
```

**Comment by idorax** [comment]
Hi @psss and @lukaszachy, to fix this issue, do we need to change something in steps of `prepare`, `execute`, `finish`? Currently I only updated class `Guest()`, please help to take a look at the latest commit in https://github.com/teemtee/tmt/pull/1094, thanks!

**Comment by idorax** [comment]
Since [PR#1094](https://github.com/teemtee/tmt/pull/1094) is ready, let's give a brief summary right here. To fix this issue, the final solution  looks like:
1. Introduce new _options attribute to [Common class](https://github.com/teemtee/tmt/blob/main/tmt/utils.py#L246)
2. Propagate dry mode from provision to prepare, execute and finish in method [go()](https://github.com/teemtee/tmt/blob/main/tmt/base.py#L1656) in [Run class](https://github.com/teemtee/tmt/blob/main/tmt/base.py#L1427)
3. Add unit test to case [tests/core/dry](https://github.com/teemtee/tmt/blob/main/tests/core/dry/test.sh)
