### ISSUE TITLE
Invalid SSL cert for artifacts.dev.testing-farm.io

### ISSUE THREAD

**Issue by frenzymadness** [teemtee/tmt#1068]
Would it be possible to allow HTTPS for artifacts.dev.testing-farm.io? HTTPS for that domain works but the provided certificate is not valid because it!s issued for api.dev.testing-farm.io.

Let!s encrypt CA supports wildcard certificates so it should be possible to get a certificate for *.dev.testing-farm.io.

**Comment by thrix** [comment]
It is resolved

**Comment by frenzymadness** [comment]
Thank you!
