### ISSUE TITLE
Unable to provision rawhide using testcloud provision

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#1083]
The latest rawhide images do not work with `provision --how virtual`. As a workaround, some of the older images can be used:

    tmt run -vvvddd provision -h virtual -i https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20220222.n.0/compose/Cloud/x86_64/images/Fedora-Cloud-Base-Rawhide-20220222.n.0.x86_64.qcow2 login finish

@frantisekz is investigating the problem.

**Comment by frantisekz** [comment]
Reported against NetworkManager: https://bugzilla.redhat.com/show_bug.cgi?id=2062211

**Comment by psss** [comment]
Works fine with the latest rawhide image.

    https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20220314.n.0/compose/Cloud/x86_64/images/Fedora-Cloud-Base-Rawhide-20220314.n.0.x86_64.qcow2

Thanks for investigating this @frantisekz.
