### ISSUE TITLE
Order of junit XML attributes is not reliable

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#1098]
`junit` plugin's tests expect following junit content:

```xml
<?xml version="1.0" ?>
  <testsuites disabled="0" errors="0" failures="1" tests="1" time="0.0">
    <testsuite disabled="0" errors="0" failures="1" name="name" skipped="0" tests="1" time="0">
        <testcase name="/fail">
            <failure type="failure" message="fail"/>
        </testcase>
    </testsuite>
</testsuites>
```

There seems to be a problem with the order of attributes of `<failure type="failure" message="fail"/>`. In Copr, the test passes, `type` appears before `message`, but on my workstation, it is reversed (`<failure message="fail" type="failure"/>`). As far as XML is interested, the order of attributes is not at all important, but when it comes to string comparison, as in `junit` tests, it's causing false negatives.

I'm not sure whether it's possible to enforce this kind of "pretty-printing" with the current code. AFAICT, dictionaries are used to bundle attributes for a given element, which does impose an ordering on keys, but by accident, thanks to implementation details. A possible option could be comparing elements as elements/trees rather than their string representations.

**Comment by lukaszachy** [comment]
Hm, any chance you did run into issue on python3.6? 
3.7+ should keep the order  https://mail.python.org/pipermail/python-dev/2017-December/151283.html

**Comment by lukaszachy** [comment]
But test should check xml equality in more robust way (not by pure chance of same order)

**Comment by happz** [comment]
> Hm, any chance you did run into issue on python3.6? 3.7+ should keep the order https://mail.python.org/pipermail/python-dev/2017-December/151283.html

I think you're right, it was Python 3.6.
