### ISSUE TITLE
Recommends packages fail test against ostree image

### ISSUE THREAD

**Issue by BeeGrech** [teemtee/tmt#1108]
**Expected**
In the docs we can see: As a tester I want to specify additional packages which should be installed on the system if available and no error should be reported if they cannot be installed.

so recommend packages should not report any error?

**Actual** 
```
Error Summary
-------------
Disk Requirements:
   At least 151MB more space needed on the /usr filesystem.

Failed to run command 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -S /run/user/1000/tmt/tmp3drb9r_2 root@192.168.122.76 export TMT_PLAN_DATA=/var/tmp/tmt/run-308/stress/stress/data; rpm -q --whatprovides "libattr-devel" "libsctp-devel" "libbsd-devel" "libgcrypt-devel" "beakerlib-redhat" "rpmdevtools" "libaio-devel" "dmidecode" "keyutils-libs" || dnf --skip-broken install -y "libattr-devel" "libsctp-devel" "libbsd-devel" "libgcrypt-devel" "beakerlib-redhat" "rpmdevtools" "libaio-devel" "dmidecode" "keyutils-libs"'. Reason: Command returned '1
```
But this is in an ostree environment where using dnf results in a read only operation. This could be linked to supporting rpm-ostree install as that would solve this issue I think.

**Comment by psss** [comment]
I guess this should be covered by #1164, right?

**Comment by BeeGrech** [comment]
Ah yes forgot i wrote this up... Yep, I did cover the recommend use case also

Side thought * Not necessarily the same as recommend, but also covers "missing: skip"
