### ISSUE TITLE
Running a single test should not copy contents of all tests into plan in /var/tmp

### ISSUE THREAD

**Issue by pemensik** [teemtee/tmt#1183]
I used command: 
`` tmt run -avvv --skip finish plan --default execute --how tmt --interactive test --name . provision --how minute --image rhel9 login``.

In my current directory is almost nothing
```
du -sh .
28K	.
du -sh ../..
278M	../..
du -sh /var/tmp/tmt/run-001/
1,1G	/var/tmp/tmt/run-001/
```

This is not acceptable. 1minutetip command might be too simplistic, but this is far from a replacement for it.

**Comment by pemensik** [comment]
Bugzilla report: https://bugzilla.redhat.com/show_bug.cgi?id=2086756

**Comment by lukaszachy** [comment]
Is any of your parent directories git or fmf root?  Currently tmt copies while parent git repo it can traverse from current working directory.
We have opened issue to copy only fmf root by default #1016 

Easiest for your use case is run tmt command in cwd which doesn't have parent git repo or fmf root.
Or make one in cwd.

**Comment by lukaszachy** [comment]
Well, now this is strange. /me tries to reproduce

**Comment by pemensik** [comment]
I had a core dump in directory ``../../Regression/domain-query-the-last-known-server``, which is not even listed by fmf.
``267M	../../Regression/domain-query-the-last-known-server``

**Comment by juk** [comment]
Voting for this one to be added.
My team has to run tests from three huge repos in a single test plan.
It takes significant amount of time for TMT to copy over everything.

**Comment by thrix** [comment]
@lukaszachy proposed for next release. What are our next steps in this long term problem? I lost a bit track of the conversation ...

**Comment by pellecchialuigi** [comment]
I just want to highlight that I am seeing a lot of tests that use relative path for source / import of other files instead of using import as library from fmf file. I think this is a scenario that we have to manage too.
Here an example:
```
. ../../include/include.sh
```

**Comment by lukaszachy** [comment]
@thrix Next steps? Find an owner, propose solution, get it accepted as the right thing to do and finally do a PR.

As @pellecchialuigi pointed this could break relative imports so probably have this as opt-in (I think 'test' should have a way how to limit / select files it needs)

**Comment by psss** [comment]
The file require functionality proposed in #1852 should allow selecting which files should be synced to the guest. @pemensik, will it cover your use case?

**Comment by pemensik** [comment]
yes, I think that should help in my case.

**Comment by psss** [comment]
Covered by #1852.

**Comment by KwisatzHaderach** [comment]
And #2333, you just need to add `prune: True` into your discover steps
