### ISSUE TITLE
As a user, I'd like to acquire system providing TPM

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#1191]
As mentioned by @kkaarreell today, this is yet another HW requirement out there. See e.g. https://aws.amazon.com/blogs/aws/amazon-ec2-now-supports-nitrotpm-and-uefi-secure-boot/ for AWS, and there might be ways how to set up VMs accordingly (or request them) for other possible sources.

In any case, adding "requires TPM" should be documented as a HW requirement.

**Comment by kkaarreell** [comment]
Beaker currently implements TPM key/value pair, allowing me to filter relevant systems.
In particular I am using

- TPM=2 to get any system with TPM v2 device
- TPM=2 and hypervisor==KVM in order to get system with TPM v2 emulated and served through QEMU/KVM
- TPM=2 and hypervisor!=KVM or hypervisor=='' in order to get bare-metal system with HW TPM v2

I would like to be able to specify similar requirements in Testing Farm so I can run my gating/regression tests without TCMS and wow

**Comment by happz** [comment]
FTR, there are TPM and TPM v2 available in AWS (https://aws.amazon.com/blogs/aws/amazon-ec2-now-supports-nitrotpm-and-uefi-secure-boot/), in theory available to Testing farm requests, therefore a generic specification would be valuable to support more than one pool in Artemis (and later tmt as well).

**Comment by happz** [comment]
> Also, one can emulate TPM in qemu using swtpm so maybe `tmt provision -h virtual` could prepare such a system.. however that would be rather another `tmt` feature.

Yeah, that's how it should work, in the ideal world: different provision plugins might support this `tmt: 2` requirement, and deliver (`artemis`+AWS would pick fitting instance type, `virtual` would throw in a qemu option or two, etc.).

**Comment by qcheng-redhat** [comment]
FYI: Here is libvirt parameters for TPM device:  https://libvirt.org/formatdomain.html#tpm-device

**Comment by happz** [comment]
> FYI: Here is libvirt parameters for TPM device: https://libvirt.org/formatdomain.html#tpm-device

Nice! Thanks for the link, this is exactly what I knew must exist somewhere.

**Comment by kkaarreell** [comment]
@happz Hi, may I ask what is the status of TPM support filtering on the Artemis side?

**Comment by happz** [comment]
> @happz Hi, may I ask what is the status of TPM support filtering on the Artemis side?

I'm afraid I forgot to look into it, sorry :( I'll try to get it to our staging instance this week.
