### ISSUE TITLE
make reboot more compatible with the rhts-reboot command (kill $PPID)

### ISSUE THREAD

**Issue by sopos** [teemtee/tmt#1212]
Some tests are using following approach to make sure the test does not continue past the `rhts-reboot` call.
```
rhts-reboot
sleep 3600
```
The rhts-reboot actually kills the `$PPID` to stop the invoking test.

Just add the `kill $PPID` into the `tmt-reboot` script to get closer to the original implementation. There should not be any issues with adding that.

**Comment by FrNecas** [comment]
Good catch, also thanks for describing the solution, I wasn't aware of the `$PPID` variable.
