### ISSUE TITLE
Rename tmt.uuid module due to potential conflict in some environments with py standard module name 

### ISSUE THREAD

**Issue by BeeGrech** [teemtee/tmt#1267]
Calling tmt binary in a debug environment caused an issue with module name conflicts. 

Actual behavior:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/bgrech/tmt/myfork/tmt/tmt/__init__.py", line 18, in <module>
    from tmt.base import Clean, Plan, Result, Run, Status, Story, Test, Tree
  File "/home/bgrech/tmt/myfork/tmt/tmt/base.py", line 35, in <module>
    import tmt.uuid
  File "/home/bgrech/tmt/myfork/tmt/tmt/uuid.py", line 2, in <module>
    from uuid import uuid4
  File "/home/bgrech/tmt/myfork/tmt/tmt/uuid.py", line 2, in <module>
    from uuid import uuid4
ImportError: cannot import name 'uuid4' from partially initialized module 'uuid' (most likely due to a circular import)

Expected: Would be normal operation of the tmt command

Resolution:
Renaming of the uuid module will resolve the conflict:
```
diff --git a/tests/unit/test_id.py b/tests/unit/test_id.py
index 295b181..2de7b88 100644
--- a/tests/unit/test_id.py
+++ b/tests/unit/test_id.py
@@ -9,7 +9,7 @@ from click.testing import CliRunner
 
 import tmt
 import tmt.cli
-from tmt.uuid import ID_KEY, IdError, IdLeafError, locate_key
+from tmt.uuid1 import ID_KEY, IdError, IdLeafError, locate_key
 
 runner = CliRunner()
 test_path = Path(__file__).parent / "id"
@@ -78,7 +78,7 @@ class IdEmpty(TestCase):
         node = self.base_tree.find("/some/structure")
         test = tmt.Test(node)
         self.assertEqual(test.id, None)
-        identifier = tmt.uuid.add_uuid_if_not_defined(node, dry=False)
+        identifier = tmt.uuid1.add_uuid_if_not_defined(node, dry=False)
         self.assertGreater(len(identifier), 10)
 
         self.base_tree = fmf.Tree(self.path)
diff --git a/tmt/base.py b/tmt/base.py
index f6a866a..755166f 100644
--- a/tmt/base.py
+++ b/tmt/base.py
@@ -32,7 +32,7 @@ import tmt.steps.provision
 import tmt.steps.report
 import tmt.templates
 import tmt.utils
-import tmt.uuid
+import tmt.uuid1
 from tmt.utils import verdict
 
 # Default test duration is 5m for individual tests discovered from L1
@@ -113,7 +113,7 @@ class Core(tmt.utils.Common):
 
         # Store the unique id if provided
         try:
-            self.id = tmt.uuid.get_id(self.node)
+            self.id = tmt.uuid1.get_id(self.node)
         except tmt.uuid.IdLeafError:
             raise tmt.utils.SpecificationError(
                 f"The 'id' key '{self.node.get('id')}' in '{self.name}' "
diff --git a/tmt/cli.py b/tmt/cli.py
index 4191ae8..2b0b5d3 100644
--- a/tmt/cli.py
+++ b/tmt/cli.py
@@ -19,7 +19,7 @@ import tmt.plugins
 import tmt.steps
 import tmt.templates
 import tmt.utils
-import tmt.uuid
+import tmt.uuid1
 
 # Explore available plugins (need to detect all supported methods first)
 tmt.plugins.explore()
@@ -785,7 +785,7 @@ def id_(context, **kwargs):
     """
     tmt.Plan._save_context(context)
     for plan in context.obj.tree.plans():
-        tmt.uuid.id_command(plan.node, "plan", dry=kwargs["dry"])
+        tmt.uuid1.id_command(plan.node, "plan", dry=kwargs["dry"])
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 #  Story
@@ -1007,7 +1007,7 @@ def id_(context, implemented, verified, documented, covered,
     for story in context.obj.tree.stories():
         if story._match(implemented, verified, documented, covered,
                         unimplemented, unverified, undocumented, uncovered):
-            tmt.uuid.id_command(story.node, "story", dry=kwargs["dry"])
+            tmt.uuid1.id_command(story.node, "story", dry=kwargs["dry"])

```

**Comment by lukaszachy** [comment]
Note: This is an old issue of pycharm: https://youtrack.jetbrains.com/issue/PY-23615?_ga=2.115449669.2133347934.1574751633-964587983.1573479767

There might be another IDE or debug/devel helper tools with similar problems.

IMO we should avoid shadowing system modules if possible either way. Currently there shouldn't be many users of 'tmt.uuid' so  rename might be OK.

**Comment by lukaszachy** [comment]
@jscotka @psss: Any ideas for the name? 
While this is clearly pycharm's fault it is still used a lot so potential for hitting this by new contributors is high.

How about 'identifier'?

**Comment by psss** [comment]
I'm ok with renaming, `tmt.identifier` or `tmt.id` sound good to me, the first one probably slightly better.
