### ISSUE TITLE
Implement caching of remote environment files

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#1312]
As for now the `environment-file` content for remote files is fetched repeatedly even if the same url is used. Would be nice to cache the remote content to speed-up user experience. Simple steps to reproduce:

    git clone https://github.com/oamg/convert2rhel
    cd convert2rhel
    tmt plan ls

Takes a very long time. Should be easy to implement using `functools.lru_cache`.

**Comment by psss** [comment]
Relevant code is here:

https://github.com/teemtee/tmt/blob/69322f858719cb8c081ef1fc8a25d67300cbf71a/tmt/utils.py#L1032

**Comment by happz** [comment]
@psss unless you want to implement the fix yourself, I'd take it.

**Comment by psss** [comment]
I was thinking this could be a good material for newcomers. Definitely free for you as well ;-) Especially if you have some good idea how to solve this in a more elegant way.

**Comment by happz** [comment]
I'm pretty sure I have no extra elegant idea, it just seems pretty simple and quick to resolve while being an obvious improvement, unlike a pile of type annotation patches that will be extremely helpful, not just this afternoon...
