### ISSUE TITLE
import assumes entry_point argument has to exist

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#1350]
Restrain metadata specify that test runs 'make run' as the test itself. However `tmt test import` attempts to read 'run' argument and fails.

Expected outcome of the conversion is
```
test: make run
```

'metadata' file:
 ```
[General]
name=reproducer
[restraint]
entry_point=make run
```
Failing command: 
```
$ tmt t import --restraint
Checking the '/x' directory.
Restraint file found in '/x/metadata'.
task: reproducer
test: run
Unable to open '/x/run'.
```

**Comment by lukaszachy** [comment]
Note that 'test: run' is already wrong in this case.

 https://github.com/teemtee/tmt/blob/main/tmt/convert.py#L227
@pfdaly Why it assigns last argument as 'test'? Do you have counter example when it has to be that way?

**Comment by pfdaly** [comment]
This looks to be an issue with the test data I used not being representative of all possible property values.

I examined how the importing of Makefile was working and then set about doing the same for a metadata file.
One existing test, at import/data/parent/child, has both a Makefile and a metadata file. For that reason I decided to use those two files as my test data for my local testing of the metadata import code I was implementing.

In the original convert.py code, the 'test' property information was retrieved from the Makefile with the following code
`data['test'] = re.search(
                r'^run:.*\n\t(.*)$', makefile, re.M).group(1)`

The Makefile I was using for my testing had the following for the 'run:' property.
`run: $(FILES) build
        ./runtest.sh`

With the original code the output was as follows:

> [root@pdaly parent]# tmt test import --makefile
> Checking the '/root/auto-kernel/tmt_fork/tmt/tests/test/import/data/parent' directory.
> Makefile found in '/root/auto-kernel/tmt_fork/tmt/tests/test/import/data/parent/Makefile'.
> task: /tmt/smoke
> summary: Simple smoke test
> test: ./runtest.sh

The metadata file had the following entry:
`[restraint]
entry_point=bash -x ./runtest.sh`

I was retrieving only the ./runtest.sh value from the metadata entry so as to match that of the Makefile.

So the output of my implemented code for importing a restraint metadata file is the following:

> [root@pdaly child]# tmt test import --restraint
> Checking the '/root/auto-kernel/tmt/tmt/tests/test/import/data/parent/child' directory.
> Restraint file found in '/root/auto-kernel/tmt/tmt/tests/test/import/data/parent/child/metadata'.
> task: /tmt/smoke
> summary: Simple smoke test using restraint.
> test: ./runtest.sh

**Comment by lukaszachy** [comment]
Thank you @pfdaly  I think that from Makefile first line of 'run' target is captured, see `\n\t` in the regexp. 

Could import be changed to paste entry_point line as is? In other words, for your test data it will do `test: bash -x ./runtest.sh`. Will it break something for your usage?
