### ISSUE TITLE
Support 'reboot' in prepare (and finish) steps

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#1351]
If I do some preparation which require reboot (or reconnect) it is not possible to do now in tmt. 
E.g.: 
- Update VM to have newer kernel and reboot
- Make VM to run in FIPS
- Change group/shell of user used by ssh (in this case forced reconnect might be enough)

**Comment by BeeGrech** [comment]
Ah nice, just ran into this with trying to run on finish step. The reasoning for my case is, the image is ostree based, I would like to perform a commit reset, as to start with a clean image after the test. 

I tried both:
```
finish:
  how: shell
  script: |
    rlRun "rpm-ostree reset" 0 "Reset rpm-ostree commit"
    rlRun "tmt-reboot" 0 "Reboot the machine"

&&

finish:
  how: shell
  script: tmt-reboot -c "rpm-ostree reset -r"
```

where reset is an image commit operation and -r is a reset flag for when the operation is completed. 
Debug output:
```
 finish
    workdir: /var/tmp/tmt/run-110/tmt/plans/test2/finish
        how: shell
        order: 50
        overview: 1 script found
        script: tmt-reboot -c "rpm-ostree reset -r"
        Execute command 'tmt-reboot -c "rpm-ostree reset -r"' on guest '10.42.5.175'.
        Run command 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -S/run/user/1000/tmt/tmpo0h8jjzx root@10.42.5.175 export TMT_PLAN_DATA=/var/tmp/tmt/run-110/tmt/plans/test2/data; cd '/var/tmp/tmt/run-110/tmt/plans/test2/tree'; tmt-reboot -c "rpm-ostree reset -r"'.
        err: touch: cannot touch '': No such file or directory
        err: /usr/local/bin/tmt-reboot: line 5: : No such file or directory
        Command returned '255'.
```

**Comment by lukaszachy** [comment]
Ah, duplicate with #902

**Comment by psss** [comment]
Ok, let's track this functionality in #902.
