### ISSUE TITLE
Type annotations to help with command escaping

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#1361]
I ran into this article, which suggests the use of type annotations to split strings into "safe" and "unsafe" groups when it comes to shell commands: https://dev.to/flare/typing-your-way-into-safety-4lek

Could be helpful to catch instances of incorrect or missing escaping, like in https://github.com/teemtee/tmt/pull/1359 or https://github.com/teemtee/tmt/pull/232.

**Comment by psss** [comment]
@happz, has this been covered by #1730?

**Comment by happz** [comment]
> @happz, has this been covered by #1730?

Sort of, we took a slightly different turn, mostly because of `LiteralString` not being supported by linters, yet. I'd say we don't need this issue anymore.
