### ISSUE TITLE
Use pathlib.Path for paths instead of strings

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#1371]
Besides having several advantages over flat API of `os.path` (e.g. https://towardsdatascience.com/why-you-should-start-using-pathlib-as-an-alternative-to-the-os-module-d9eccd994745 for few ideas), switching internal path representation from strings to `pathlib.Path` would create a clear boundary between paths and other strings with generic content. `/foo bar` might look like a string, but it does have special semantics, and it requires special handling, for example when entering `subprocess` machinery, the space must be escaped correctly. Changing the type of "path-like" object would help in this regard.

**Comment by thrix** [comment]
+1 from me, seems a neat idea

**Comment by FrNecas** [comment]
Yes, great idea, although a lot of places will need to be changed.

**Comment by happz** [comment]
Thanks for taking the issue, @idorax - please, be aware that this is sort of blocked by completing #1182 first. It's not impossible to work the patch already, but as #1182 is getting closer to completion, we expect smaller patches to amend various rough edges, and these may make your life much harder because of rebases involved. So, no rush, I guess :)

**Comment by idorax** [comment]
Thank you too, @happz. Will work on this issue after #1182 is done :-)

**Comment by happz** [comment]
@idorax hi, I believe this is now unblocked. There are still patches pending for merge that change lines here and there, but I'd say it should be calm enough for hacking :)

**Comment by idorax** [comment]
@happz, will do it soon :-)

**Comment by happz** [comment]
@idorax hi, how are you doing WRT this patch? I do have some spare time, I could work on this if your hands are not free enough.

**Comment by idorax** [comment]
@happz, I'm just back from PTO, please help to take over it as you know better than me on it, thanks!

**Comment by happz** [comment]
> @happz, I'm just back from PTO, please help to take over it as you know better than me on it, thanks!

Understood, I'll submit my PR Soon(TM).

**Comment by psss** [comment]
Covered by #1776.
