### ISSUE TITLE
Convert "command" and "command options" to list of strings to simplify their handling

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#1378]
CLI commands and arguments are often interchanged in two different forms: as strings (e.g. `ansible --extra-args "-vvv --foo"` propagates the value of `--extra-args` option down to `Guest` classes as a string) or as a list of strings (e.g. `tmt.steps.provision.DEFAULT_RSYNC_OPTIONS` is a list of strings, one per option). Some places accept both forms (e.g. `Common.run()` and `Guest.execute()` accept `Union[str, List[str]]`, and perform some kind of coercion as needed).

This leaves us with an entangled web of two different types entering the "run a command" API. My proposal would be:

* pick one type, and make it the one and only internal "command-line" type.
  * I for one would prefer it to be `List[str]`, for various reasons:
    * easy to extend/replace items (much harder with `str`)
    * easy to quote every item (much harder with `str`)
    * accepted by `subprocess`
    * easy to convert to `str` (harder for `str`)
* ditch the other type (`str` in my scenario)
  * do not allow internal functions dealing with commands and command-line to accept it, ever
  * whenever command-line enters tmt's code in form of this type, convert it to the official one, as soon as possible. For example, in the case of `ansible --extra-args`, the value of this option would be converted to `List[str]` by `ansible` plugin, in it's `get()` or whatever method - it would *never* be left as `str` and given to the rest of the code. This is a common practice when working with 3rd party data  - validate, normalize, sanitize data when they enter our code and do not let them go through calls in their original form.
  * if there are "default foo options" as a string (DEFAULT_FOO_OPTIONS = '-v --user root` and so on), convert them to the official type.
* give the official type an alias, `CommandLine = List[str]` - easy to follow, easy to understand
  * We can make one extra step, and introduce `ShellEscapedStr` type to distinguish between a string and a string that's safe to use for CLI operations

What do we get?

* simplicity: is the value command to run, or command-line options? *Then it's a list of strings*, end of the story. **No exceptions.**
* clear responsibilities: is my plugin given command or command-line options as a string? It's my plugin's responsibility to convert them to internal format ASAP. Is command about to be executed? Escape its components, just before it leaves tmt's "jurisdiction".
* safety: noone can forget to apply `shlex.quote`. Noone can use `str` in place of `List[str]` and vice versa.
* sanity

I went for this scenario naturally when I first added annotations to `tmt.utils`, but it was not accepted. One of the main objections was `Guest.execute` accepting command as a string - such a command is then merged with `ssh` & co., forming a list of strings representing the final `ssh` command to execute which would run the given command on a guest. I still believe the current API should go, as it's simply nothing else than an exception, making it harder to reason about "run a command" API, and I hope I would be able to demonstrate advantages and convince you to go this road.

(Yeah, I'm adding type annotations to `tmt.steps.provision`, and it's... It's more painful than it should be.)

**Comment by happz** [comment]
Few more examples of ambiguous return value and how it makes harder to use the internal API: 

```python
# In mt.steps.provision.Guest
def _ssh_command(self, join: bool = False) -> Union[str, List[str]]:
  ...

command = (
  self._ssh_command() + interactive + [self._ssh_guest()] + ...
)

# but also
self.run(
    ["rsync"] + options
    + ["-e", self._ssh_command(join=True)]
    + [source, f"{self._ssh_guest()}:{destination}"])

# When ' '.join(self._ssh_command()) would be perfectly fine...

# Same goes for this one:
def _ssh_options(self, join: bool = False) -> Union[str, List[str]]:
   ...

command = command + self._ssh_options() + ["-MNnT", self._ssh_guest()]

# but also (in _ssh_command() ...):

        if join:
            return " ".join(command) + " " + self._ssh_options(join=True)
        else:
            return command + self._ssh_options()
```

**Comment by psss** [comment]
This has been covered by #1730.
