### ISSUE TITLE
Make `tmt plan ls|show` report enabled plans by default

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#1391]
Quite common use case is to do pipeline like `tmt plans ls | xargs -n 1 tmt run plan --name` however there is one big difference:
"tmt plan ls" list even disabled plans while "tmt run" runs only enabled plans.

If one happen to have disabled plan there is confusing error from "tmt run" saying that "No plans found"
Correct way of this pipe is  `tmt plans ls  --filter=enabled:true | xargs -n 1 tmt run plan --name`.
One way to match user expectations is to make 'plan ls' print only enabled plans (and add e.g. '--all' as a flag to list all).

Reproducer:
```
$ cat plan.fmf
execute:
  how: tmt
enabled: false

$ tmt p ls | xargs tmt run pla -n 
/var/tmp/tmt/run-087
No plans found.
```

Another way would to say "No enabled plans found"...

Not sure what should be done for `tmt` command - current behaviour seems OK so maybe leave it as is?

**Comment by sopos** [comment]
Note that `tmt tests ls` uses the same logic so we should keep it in sync.

For an automation, the more complicated pipeline is not an issue. The fact that the automation owners do not use it correctly is mainly about improving the documentation.

What we should focus on is the use expectations, e.g. manual usage.

While adding `--all|-a` switch to the command make sense for `ls` it does not necessarily make sense for `show`. One may want to show details of a disabled test even without any further switches.
So there's another question: do we want to keep the consistency between `ls` and `show`?

**Comment by idorax** [comment]
For `tmt plans ls`, `Tree.plans()` get all plans even if the property  `enabled` of a plan is `false`,
* https://github.com/teemtee/tmt/blob/main/tmt/base.py#L1483
  ```python
  1483	        plans = [
  1484	            Plan(plan, run=run) for plan
  1485	            in self.tree.prune(keys=keys, names=names, sources=sources)]
  1486	        return self._filters_conditions(
  1487	            sorted(plans, key=lambda plan: plan.order),
  1488	            filters, conditions, links, excludes)
  ```
But `Tree._filters_conditions()` doesn't filter those plans whose property `enabled` is `false` by default. Looks we should update `Tree._filters_conditions()` to fix this issue.

**Comment by psss** [comment]
> So there's another question: do we want to keep the consistency between `ls` and `show`?

I'd say both `ls` both `show` command should behave consistently. Similarly for `tmt test` versus `tmt plan`. Consistency is the key to what users can expect from individual commands without having to read the docs too much.

What about making the get-all-enabled-plans use case more straightforward?

    tmt plan ls --enabled

Would that help a bit?

**Comment by idorax** [comment]
`tmt plan ls --enabled` only list those plans which is enabled, and `tmt plan ls` list all plans, right？ @psss

**Comment by psss** [comment]
Discussed on the hacking session today. New option for listing enabled only plans sounds good. In order to make the user experience consistent, let's add new options `--enabled` and `--disabled` to the `name_filter_condition` decorator and enable them for tests, plans and stories.
