### ISSUE TITLE
tmt should make sure the machine reboot process started before tring to reconnect

### ISSUE THREAD

**Issue by sopos** [teemtee/tmt#1399]
Currently, tmt simply wait for some time (5 sec?) after reboot before it tries to connect again.
If the machines does not reboot within that time tmt simply thinks the reboot is over and proceeds with the execution, then the real reboot happens.

Tmt, should implement a mechanism to check the machine state rather than just wait. E.g. for the ssh connected SUTs the connection breakage would be good indication that the machine got rebooted.

**Comment by lukaszachy** [comment]
Blocker for 1.16 as we must have this working ASAP and 1.17 is too far away.

**Comment by pcahyna** [comment]
Could it use `uptime` ?

**Comment by sopos** [comment]
> Blocker for 1.16 as we must have this working ASAP and 1.17 is too far away.

the reason for the blocker is that it breaks CUT testing



> Could it use `uptime` ?

could be usable for more provision methods

**Comment by happz** [comment]
`uptime -s` could be helpful (save its output => initiate reboot => connect & run `uptime -s` for as long as it's possible to connect and outputs match => spin until connection can be re-established again => verify `uptime -s` is now different). Not helpful for containers though, podman plugin might need a different approach.

**Comment by sopos** [comment]
I've found out that the different behavior I'm observing is due to the timing issues on the different SUTs rather than a regression in the tmt code.

**Comment by lukaszachy** [comment]
Please comment #1402 if acceptable for GuestSSH

Rest of guests are:
GuestLocal doesn't support reboot
GuestContainer (uses podman-container-restart)
GuestTestcloud (uses self.stop && self.start unless command is used, then it is GuestSSH)
private GuestMinute will need change similar to GuestSSH

**Comment by lukaszachy** [comment]
As for `uptime` it could work however will be  `procps-ng` (which own uptime)  everywhere and every time? I'd like to avoid depending on yet another binary to be present on SUT (currently: ssh, rsync, bash AFAIK)

**Comment by pcahyna** [comment]
> 

It seems to also invoke `whoami` according to the logs I have seen

**Comment by sopos** [comment]
If you want to avoid the `uptime` dependency, we might parse the `/proc/uptime` directly.
