### ISSUE TITLE
lean/persistent repo clonning for discover step

### ISSUE THREAD

**Issue by martinhoyer** [teemtee/tmt#1413]
Currently, tmt clones the whole git repository to discover tests every time the plan is run.  
Since some repositories are extremely large, I was wondering whether it wouldn't make sense to have an option to either do a 'sparse' clone, or to have a persistent-ish directory with the cloned repo and do a git pull instead of clone.

**Comment by lukaszachy** [comment]
Since #1253 we are using shallow clone if 'ref' is not used. Is that enough for your use case?

**Comment by martinhoyer** [comment]
I see, I was using 'ref' for testing. Shallow clone by default sounds good. Thanks Lukas.
