### ISSUE TITLE
testcloud doesn't print path to the used (generated) ssh identity

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#1442]
I'm using `provision -h virtual -vvv` and all I see is `key: []`. 
I'd say that when virtual.testcloud provision is generating the key it should wait with this output until key is generated and print path to the real identity file.

Use case: Provision VM in one run and use it for other runs with 'connect'. Currently I need to dig used key from workdir / guests.yml (or have it noted somewhere as the path to the key is predictable).

**Comment by idorax** [comment]
The root cause is because `[]` is not `not None`, so `key: []` is printed.
* https://github.com/teemtee/tmt/blob/main/tmt/steps/provision/testcloud.py#L304
  ```python
   297	        for key, value in data.to_dict().items():
   298	            if key == 'memory':
   299	                self.info('memory', f"{value} MB", 'green')
   300	            elif key == 'disk':
   301	                self.info('disk', f"{value} GB", 'green')
   302	            elif key == 'connection':
   303	                self.verbose('connection', value, 'green')
   304	            elif value is not None:
   305	                self.info(key, value, 'green')
  ```
