### ISSUE TITLE
Hint user if 'tmt init' creates nested root

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#1449]
It is quite easy to create nested fmf root by mistake (e.g. tmt guide mentions "tmt init" few times) however this is something user usually doesn't want.

Would be nice if tmt tries to find if current working directory is inside fmf root and if yes then mention this to the user as a warning/hint. Something amongst lines of "Existing fmf root at <location>, if you executed tmt init by mistake use "rm -r .fmf" to remove it."

Or we might ask for confirmation (e.g. by click's confirm prompt) unless -y (as yes) or -f (as force) is used.  This might be more user friendly.

Why this could be a problem? Nested fmf roots are invisible to the upper one so whole structure disappears from the original tmt tree. 
The tmt test suite uses it a lot (check "data" subdirectories) which contain plans and test inaccessible to the tmt run outside of those dirs.

**Comment by idorax** [comment]
To find out the parent fmf root of a path to initialize, we can leverage `tmt.Tree(path)`. e.g.
```bash
$ tree -a /tmp/foo
/tmp/foo
├── .fmf
│   └── version
└── root01
    ├── .fmf
    │   └── version
    ├── foo1.fmf
    ├── root02
    │   └── example.fmf
    └── tests
        └── example
            ├── main.fmf
            └── test.sh
```

* 

```python
(tmt) huanli@kvm-01-guest03:example$ pwd
/tmp/foo/root01/tests/example
(tmt) huanli@kvm-01-guest03:example$ pt init -t mini
> /home/huanli/.virtualenvs/tmt/bin/tmt(3)<module>()
-> import click
(Pdb) b tmt/base.py:1910
Breakpoint 1 at /home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/tmt/base.py:1910
(Pdb) c
> /home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/tmt/base.py(1910)init()
-> path = os.path.realpath(path)
(Pdb) args
path = '.'
template = 'mini'
force = False
kwargs = {'verbose': 0, 'debug': 0, 'quiet': False, 'dry': False}
(Pdb) n
> /home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/tmt/base.py(1911)init()
-> dry = Tree._opt('dry')
(Pdb) p path
'/tmp/foo/root01/tests/example'
(Pdb) p tmt.Tree('/tmp/foo/root01/tests/example').root
'/tmp/foo/root01'
(Pdb) p tmt.Tree('/tmp/foo/root01/tests').root
'/tmp/foo/root01'
(Pdb) p tmt.Tree('/tmp/foo/root01').root
'/tmp/foo/root01'
(Pdb) p tmt.Tree('/tmp/foo').root
'/tmp/foo'
(Pdb) p tmt.Tree('/tmp').root
*** tmt.utils.MetadataError: No metadata found in the '/tmp' directory. Use 'tmt init' to get started.
(Pdb) p tmt.Tree('/').root
*** tmt.utils.MetadataError: No metadata found in the '/' directory. Use 'tmt init' to get started.
(Pdb) 
```

**Comment by lukaszachy** [comment]
@idorax Yes, you can `tree = tmt.Tree('.')` and catch the exception. 
If it raises exception -> you are good to continue with 'init'
If not - report `tree.root` and ask user what to do (whether continue with 'init' in cwd or stop as they realize their mistake)
