### ISSUE TITLE
Formalize "data" package passed to `tmt.result.Result`

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#1456]
As of now, it's a free-form dictionary, with no formal specification of mandatory and/or allowed keys and values. A change to dataclasses + an enum or two should bring more stability.

**Comment by ZelenyMartin** [comment]
I have experience with #1488 so I guess I can do this as well. Please reach me when this gets priority/approval so I can start working on it.

**Comment by ZelenyMartin** [comment]
After consulting with @happz, there are blockers for starting to work on this:
1. merge #1488
2. move `Result` class from `base.py` to separate module
