### ISSUE TITLE
Report plugin arguments from fmf plan are ignored

### ISSUE THREAD

**Issue by KwisatzHaderach** [teemtee/tmt#1483]
fmf file:
```
report:
    how: junit
    file: ahoj.xml

```
run:
```
$ tmt run -a provision -h connect -g ip -u user -p password plans --name tests
...
    report
        how: junit
        output: /var/tmp/tmt/run-047/plans/tests/report/default-0/junit.xml

```
Originally wanted to report that using multiple report plugins does execute both but arguments are ignored, after testing more I found out the arguments are ignored altogether.

**Comment by psss** [comment]
Easy to fix, let's include this in `1.17`.
