### ISSUE TITLE
Convert Result class to serializable container

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#1492]
Types, better visibility for linters, load/save support out of the box.

**Comment by ZelenyMartin** [comment]
I have experience with https://github.com/teemtee/tmt/pull/1488 so I guess I can do this as well. Please reach me when this gets priority/approval so I can start working on it.

For this issue, I'll need some consultation what is exactly expected.

**Comment by happz** [comment]
I have something in https://github.com/teemtee/tmt/blob/eccf758305dd0f84b7be5393133d5ab90283426a/tmt/base.py#L2431 (part of draft https://github.com/teemtee/tmt/pull/1457) - I was adding annotations to `base.py`, and one of the side effects was `Result` slowly being turned into a more strict class with enums.

It's by no means complete, and it's worth its own PR instead of being sneaked into this patch, the issue here would be changing `Result` wouldn't be covered by `mypy` until all of `base.py` is annotated, therefore refactoring would involve considerable risk. We might get around this by moving `Result` into its own Python module (`tmt.result`, for example), and enabling mypy checks for this module from the beginning, still all uses of `Result` from `tmt.base` would be risky until `base.py` is annotated... Chicken and egg, I'm afraid :/

Let's see how my work on annotating `base.py` goes, I'd try to leave something nice to begin with - I'd be happy if someone else would work on `Result` later, especially since you checked the waters already :)

**Comment by happz** [comment]
This issue has been completed already, as part of #1457. Serialization methods are used from https://github.com/teemtee/tmt/blob/main/tmt/steps/execute/__init__.py#L465 and https://github.com/teemtee/tmt/blob/main/tmt/steps/execute/__init__.py#L474.
