### ISSUE TITLE
Polarion reporter needs to be able to consume tmt env vars

### ISSUE THREAD

**Issue by thrix** [teemtee/tmt#1505]
Pylero can consume environment variables for credentials and settings, but we should teach it to be able to pick these up also from tmt environment variables. This way setting env vars can be unified for the users of Testing Farm. The Testing Farm does not want to introduce another setting of env vars in the session where `tmt` is running.

**Comment by thrix** [comment]
This is blocking polarion reporter plugin integration in Testing Farm

**Comment by smwltr** [comment]
If you are need to make changes to Pylero, may I recommend [Polarion](https://pypi.org/project/polarion/) which is a module and you can just do `Polarion(url, username, password)`?

**Comment by thrix** [comment]
@smwltr I do not much, we can just expose in the env those vars from the tmt env before importing. Seems cleaner to me as the user controls Pylero via env vars passed to Testing Farm, so let's not translate that to Polarion plugin params in the tmt code. Keeping it as env vars is more reasonable I would say.

**Comment by smwltr** [comment]
I see. So no need to mod Pylero then. That's good. So some `os.environ` calls here maybe https://github.com/teemtee/tmt/blob/68bee3e8042aade29c279b52bc53854365480d59/tmt/export.py#L73

@KwisatzHaderach , what do you think?

**Comment by KwisatzHaderach** [comment]
Yeah, I already discussed this with @thrix, the call for os.environ.update needs to be somewhere where you can get self.opt('environment') or whichever way TF sends the variables into tmt.

**Comment by psss** [comment]
After discussion with @thrix we agreed that it would be best to store credentials and similar stuff in the `tmt` process environment variables and that Testing Farm will add a new API key for providing those. This should not require any changes on the `tmt` side. Optionally, we can implement also a new `tmt` option, let's say `--process-environment` which would allow to easily load process environment variables from a file.

**Comment by psss** [comment]
So after the discussion the whole necessary implementation to make this working should happen on the Testing Farm side and currently there does not seem to be a clear use case for the extra `--process-environment` option, thus closing.
