### ISSUE TITLE
Document clearly what is the purpose and use case of {to|from}_{serialized|raw|dict} methods added recently

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#1518]
Classes like `SerializableContainer` solve genuine issues, but in an unusual way that's new for tmt developers. It may be unclear and puzzling why so many new methods were added, and what's their purpose and use cases.

**Comment by happz** [comment]
@psss I added this issue to 1.18 milestone right away - while working on links, I noticed how these methods start to spread, and I think you'd appreciate nice documentation :)

Any tips for the best place? I'd like to add a paragraph or two, something along the lines "if you see in code: * from_raw() ..., * from_serialized() ..., etc.". A docstring of `tmt.base` or `tmt.utils`? Or https://tmt.readthedocs.io/en/latest/contribute.html#introduction which now contains the recent guidance WRT error messages?

**Comment by psss** [comment]
Probably does not make sense to repeat the same info in each and every docstring. What about adding a new section around here?

 * https://tmt.readthedocs.io/en/latest/classes.html#attributes

This page already contains some kind of hints for developers.
