### ISSUE TITLE
Implement dynamic ref evaluation

### ISSUE THREAD

**Issue by kkaarreell** [teemtee/tmt#1532]
Using branches for tests brings multiple challenges. Let's name a few:

- test owner may use various branching strategies and the required strategy may even change in time (if previous strategy turns out to be wrong)
- test plan owner may not be notified about a change in test branches
- there can be multiple test plans consuming tests from a single test repository and it would be impractical to update each plan. Ideally, a required change would be done on one (test repo) side so that it would be completely transparent to test plans.
- one test plan can consume tests from multiple test repositories and each test repository can implement different branching strategy (or none) and new branches can be created at different time.

Below is what I believe would be the best way how to implement test branching support into tmt, along with test plan parametrization using context described in https://github.com/teemtee/tmt/issues/1513. The different is that while Issue 1513 supports ref parametrization within a source plan/repo and thus enables processing of the `.fmf/dynamic_ref.fmf` file (more on that below), dynamic ref evaluation should allow identification of the right branch using rules defined in the test repository itself. This is a main difference as it means the `ref` evaluation logic is not implemented on the test plan side (consumer) but on the tests repo side (test maintainer/producer). 

I propose to store the evaluation logic in a dedicated text file in the referenced tests repository and stored in its main branch. For the purpose of this PR let's say it would be `.tmt/dynamic_ref.fmf`. It's sole presence in the referenced repository would mean that dynamic evaluation will be used, unless a specific `ref` has been provided in the test plan already. This way we can (during test plan loading) download just one small file and evaluate it instead of downloading whole repository and evaluating (or extending) test plan `fmf` tree. `.tmt/dynamic_ref.fmf` itself would consist of the `adjust` sectio, to simplify its processing and make it more accessible to users. In that section the branch selection logic will be implemented (as outlined in Issue 1513) by defining a value of variable named e.g. `DYNAMIC_REF` through rules using `context` used for the test plan. In the end the non-empty value of `DYNAMIC_REF` variable would be used for `ref` value in the parent test plan (main branch otherwise).

This approach addresses issues listed above. Rules are flexible and under control of test repo maintainer, the same person that implements the branching. Any change in branching must be reflected only in a single file and is completely transparent to consuming test plans. Test plan may not even have to care about test branching strategy, the only thing to keep in mind would be to populate required contexts (which can be documented in comments of the `.tmt/dynamic_ref.fmf` file).

Example how it could look like in particular.

`.tmt/dynamic_ref.fmf` file in tests repository defines `DYNAMIC_REF` using the `build_branch` context. In practice, I expect additional context may be used, especially `distro` context but in order to keep this example short only one context will be used.
```
$ cat dynamic_ref.fmf 
# this logic assumes that a context "build_branch" is defined, pointing to a source branch of the tested build
adjust:
   - when: build_branch is not defined
     environment:
       DYNAMIC_REF: main
     because: no build branch is defined
     continue: false
   - when: build_branch == c9s
     environment:
       DYNAMIC_REF: rhel-9-main
     because: use rhel-9-main branch for c9s testing
     continue: false
   - when: build_branch is defined
     environment:
       DYNAMIC_REF: $@{build_branch}   # this is assignment of the build_branch value, see issue 1513 for details
     because: using the provided BUILD_BRANCH as test branch
```

The test plan consuming tests can look like this:
```
$ cat tier1-swtpm.fmf 
summary: run Tier1 keylime e2e tests with swtpm and revocation notifier enabled

discover:
  how: fmf
  url: https://github.com/RedHat-SP-Security/keylime-tests.git
#  ref: main   # no ref is used so that dynamic_ref.fmf takes effect
  test:
    # setup swtpm repo
    - /functional/basic-attestation-on-localhost

execute:
  how: tmt
```

**Comment by kkaarreell** [comment]
Example how it could look like
```
$ cat dynamic_ref.fmf 
# this logic assumes that a context "build_branch" is defined, pointing to a source branch of the tested build
adjust:
   - when: build_branch is not defined
     environment:
       DYNAMIC_REF: main
     because: no build branch is defined
     continue: false
   - when: build_branch == c9s
     environment:
       DYNAMIC_REF: rhel-9-main
     because: use rhel-9-main branch for c9s testing
     continue: false
   - when: build_branch is defined
     environment:
       DYNAMIC_REF: $@{build_branch}
     because: using the provided BUILD_BRANCH as test branch
```
and plan
```
$ cat tier1-swtpm.fmf 
summary: run Tier1 keylime e2e tests with swtpm and revocation notifier enabled

discover:
  how: fmf
  url: https://github.com/RedHat-SP-Security/keylime-tests.git
  ref: https://raw.githubusercontent.com/RedHat-SP-Security/keylime-tests/tree/main/dynamic_ref.fmf
  test:
    # setup swtpm repo
    - /functional/basic-attestation-on-localhost

execute:
  how: tmt
```

**Comment by psss** [comment]
As discussed on the meeting today, I'd suggest to support also detecting the dynamic ref from the main branch of the git repository which should make the `discover` step config a bit more concise the user. If needed, direct referencing the remote file can be supported as well. Instead of requiring file of a given name, we could possibly support specifying the file name in the `ref` key:

```yaml
discover:
    how: fmf
    url: https://github.com/RedHat-SP-Security/keylime-tests.git
    ref: .branching.fmf
```

This would allow choosing for example a hidden file if one prefers to keep the git repository root clean.

**Comment by kkaarreell** [comment]
> As discussed on the meeting today, I'd suggest to support also detecting the dynamic ref from the main branch of the git repository which should make the `discover` step config a bit more concise the user. If needed, direct referencing the remote file can be supported as well. Instead of requiring file of a given name, we could possibly support specifying the file name in the `ref` key:

I am not against it but I would afraid of possible collisions between branch name and a presence of a file having same filename. Probably it would be necessary to use some specific syntax (`ref: @.branching.fmf`).

**Comment by psss** [comment]
Special syntax for the dynamic reference file sounds good.

**Comment by kkaarreell** [comment]
@psss @lukaszachy 
I was playing with tmt a bit and sort of implemented this feature using the code below. But there are at least three issues:
 1. I don't know if this approach is correct (but seem to work)
 2. I don't know where to get the current context (see that the context is hardcoded in the patch below)
 3. Full implementation still requires an adjust to be able to modify environment variables using context, as requested in https://github.com/teemtee/tmt/issues/1513 (there is some patch too but it is ugly and possibly not even functioning properly).

```
--- /usr/lib/python3.6/site-packages/tmt/steps/discover/fmf.py.orig	2022-10-12 20:54:58.324739134 +0200
+++ /usr/lib/python3.6/site-packages/tmt/steps/discover/fmf.py	2022-10-12 21:23:57.481319277 +0200
@@ -307,6 +307,39 @@
                 if not self.opt('dry'):
                     shutil.copytree(directory, self.testdir, symlinks=True)
 
+        # Check for dynamic_ref file presence
+        # either following special syntax ref: @filepath
+        if ref and ref[0] == '@':
+            dynref_filepath = os.path.join(self.testdir, ref[1:])
+        # or using the default .tmt/dynamic_ref.fmf
+        else:
+            dynref_filepath = os.path.join(self.testdir, ".tmt/dynamic_ref.fmf")
+        # dynamic ref check is enabled if ref is not defined or starts with @
+        if (not ref or ref[0] == '@'):
+            if os.path.exists(dynref_filepath):
+                self.debug(f"Dynamic ref file '{dynref_filepath}' was found")
+                # there is a dynamic_ref.fmf file
+                # read it and get the value of DYNAMIC_REF variable
+                dynref_plan = tmt.utils.yaml_to_dict(tmt.templates.DEFAULT_PLAN)
+                with open(dynref_filepath, encoding='utf-8') as datafile:
+                    data = tmt.utils.yaml_to_dict(datafile.read())
+                dynref_parent = fmf.Tree({'summary': 'unused'})
+                dynref_node = fmf.Tree({'execute': None}, name="dynamic_ref", parent=dynref_parent)
+                dynref_node.update(data)
+                dynref_node.adjust(fmf.context.Context('distro = fedora-36'))
+                dynref_var = dynref_node.get("environment", "DYNAMIC_REF")
+                if '=' in dynref_var:
+                    dynref_var = dynref_var.split('=')[1]
+                ref = dynref_var
+            # there is no dynamic ref file
+            else:
+                # if dynamic ref file was specified using @ but not found raise an exception
+                if ref and ref[0] == '@':
+                    raise tmt.utils.DiscoverError(
+                        f"Dynamic ref file '{dynref_filepath}' was not found")
+                else:
+                    self.debug(f"Dynamic ref file '{dynref_filepath}' was not found")
+
         # Checkout revision if requested
         if ref:
             self.info('ref', ref, 'green')
```

**Comment by kkaarreell** [comment]
Small update.. I think I made it work altogether, however my concerns regarding the approach are still valid.
Anyway, to present how it works.

This is a test plan
```
summary: dynref demo plan

discover:
    how: fmf
    url: "https://github.com/kkaarreell/dynref_test.git"
```
This is the `/.tmt/dynamic_ref.fmf` file
```
environment:
  DYNAMIC_REF: foo

adjust:
  - when: branch is defined
    environment:
        DYNAMIC_REF: $@{branch}
    continue: false
  - when: branch is not defined
    environment:
        DYNAMIC_REF: main
```
Both can be seen in https://github.com/kkaarreell/dynref_test.git

Now some tests:
```
$ tmt run discover -vvv 
/var/tmp/tmt/run-110

/plans/default
    discover
        how: fmf
        order: 50
        directory: /home/ksrot/devel/github/dynref_test
        ref: main
        hash: 4022324
        summary: 0 tests selected
        warning: No tests found, finishing plan.

$ tmt -c branch=zzz run discover -vvv 
/var/tmp/tmt/run-111

/plans/default
    discover
        how: fmf
        order: 50
        directory: /home/ksrot/devel/github/dynref_test
        ref: zzz

stderr (1/1 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: pathspec 'zzz' did not match any file(s) known to git

Failed to run command: git checkout -f zzz Reason: Command returned '1'.
```
As you can see proper evaluation is being followed.

Changes made in tmt source files are:
```
--- /usr/lib/python3.6/site-packages/tmt/steps/discover/fmf.py.orig	2022-10-12 20:54:58.324739134 +0200
+++ /usr/lib/python3.6/site-packages/tmt/steps/discover/fmf.py	2022-10-12 22:58:21.802091746 +0200
@@ -307,6 +307,39 @@
                 if not self.opt('dry'):
                     shutil.copytree(directory, self.testdir, symlinks=True)
 
+        # Check for dynamic_ref file presence
+        # either following special syntax ref: @filepath
+        if ref and ref[0] == '@':
+            dynref_filepath = os.path.join(self.testdir, ref[1:])
+        # or using the default .tmt/dynamic_ref.fmf
+        else:
+            dynref_filepath = os.path.join(self.testdir, ".tmt/dynamic_ref.fmf")
+        # dynamic ref check is enabled if ref is not defined or starts with @
+        if (not ref or ref[0] == '@'):
+            if os.path.exists(dynref_filepath):
+                self.debug(f"Dynamic ref file '{dynref_filepath}' was found")
+                # there is a dynamic_ref.fmf file
+                # read it and get the value of DYNAMIC_REF variable
+                dynref_plan = tmt.utils.yaml_to_dict(tmt.templates.DEFAULT_PLAN)
+                with open(dynref_filepath, encoding='utf-8') as datafile:
+                    data = tmt.utils.yaml_to_dict(datafile.read())
+                dynref_parent = fmf.Tree({'summary': 'unused'})
+                dynref_node = fmf.Tree({'execute': None}, name="dynamic_ref", parent=dynref_parent)
+                dynref_node.update(data)
+                dynref_node.adjust(fmf.context.Context(**self._fmf_context()))
+                dynref_plan = tmt.Plan(node=dynref_node, run=None, skip_validation=True)
+                dynref_plan._expand_node_data(dynref_node.data)
+                dynref_var = dynref_node.get("environment").get("DYNAMIC_REF", None)
+                ref = dynref_var
+            # there is no dynamic ref file
+            else:
+                # if dynamic ref file was specified using @ but not found raise an exception
+                if ref and ref[0] == '@':
+                    raise tmt.utils.DiscoverError(
+                        f"Dynamic ref file '{dynref_filepath}' was not found")
+                else:
+                    self.debug(f"Dynamic ref file '{dynref_filepath}' was not found")
+
         # Checkout revision if requested
         if ref:
             self.info('ref', ref, 'green')
```
```
--- /usr/lib/python3.6/site-packages/tmt/base.py.orig	2022-09-05 11:16:38.000000000 +0200
+++ /usr/lib/python3.6/site-packages/tmt/base.py	2022-10-12 22:35:35.749535478 +0200
@@ -1082,7 +1082,19 @@
     def _expand_node_data(self, data):
         """ Recursively expand variables in node data """
         if isinstance(data, str):
-            return os.path.expandvars(data)
+            # expand env variables
+            data_expanded_vars = os.path.expandvars(data)
+            # do a backup of env variables since we are going to rewrite it temporarily
+            env_backup = os.environ.copy()
+            os.environ.clear()
+            # convert context values to string and define env variables using context keys and values
+            list_context_string = [(a, ','.join(b)) for (a,b) in self._fmf_context().items()]
+            os.environ.update(dict(list_context_string))
+            # convert $@{} to ${} and expand contexts  using temporarily defined environment variables
+            data_expanded_context = os.path.expandvars(data_expanded_vars.replace('$@', '$'))
+            # restore previously backed up environment variables
+            os.environ.update(env_backup)
+            return data_expanded_context
         elif isinstance(data, dict):
             for key, value in data.items():
                 data[key] = self._expand_node_data(value)
@@ -1160,6 +1172,8 @@
 
     def _fmf_context(self):
         """ Return combined context from plan data and command line """
+        # I was getting an error that context does not exist without the following line
+        self._plan_context = self.node.get('context', dict())
         combined = self._plan_context.copy()
         combined.update(self._context.obj.fmf_context)
         return combined
```

**Comment by happz** [comment]
@kkaarreell just a quick note, I haven't read the original discussion yet, so just something I spot: I think your implementation lacks one `os.environ.clear()` before the final restoration, possibly leaking new variables into `os.environ` (`.update()` would restore shared keys, but wouldn't remove added ones).

Could you try `tmt.utils.modify_environ`? It's supposed to do exactly what you're after, and simplify code a lot:

```python
with tmt.utils.modify_environ(dict(list_context_string)):
  return os.path.expandvars(data_expanded_vars.replace('$@', '$'))
```

Not tested, just a guess it could ease the review.

**Comment by kkaarreell** [comment]
@happz It really does, thank your. And finally I understand why that function has been implemented as an iterator. Elegant.
