### ISSUE TITLE
tmt tests import --polarion --polarion-case-id doesn't work

### ISSUE THREAD

**Issue by yizhanglinux** [teemtee/tmt#1553]
Hello
I'm trying to test the import from polarion feature, but seems it doesn't work, could you help check it, thanks.

```
(tmt) [yizhan@fedora34 test_devs_setup]$ tmt tests import --polarion --polarion-case-id 23c510fc-9d2d-4365-b280-fc3b95117fd0  -v
Checking the '/home/yizhan/Work/Code/RHEL/CKI/kernel-tests/storage/ssd/test_devs_setup' directory.
Unable to find Makefile
```

Thanks
Yi

**Comment by KwisatzHaderach** [comment]
You can specify --no-makefile, but you need to have either a makefile and/or a restraint file for the import to work.
Also the id is not correct, it was supposed to work with work item id, like 'RHELKERNEL-12345', however I just checked the code and it will actually work with that id as well.

Maybe now it's the time to start supporting imports from Polarion only (no makefile or restraint), what do you think @psss ?

**Comment by pellecchialuigi** [comment]
I was just for creating an new issue to request that feature: **tmt polarion integration without metadata legacy files.**
For new tests we don't have such kind of files available and we are working on a task that will request several new test cases in Polarion!
I checked the existing issues and I found that one.
@psss could we take that into consideration for incoming work on tmt?
thanks

**Comment by KwisatzHaderach** [comment]
Right, you are in luck, I'm already working on this as part of my work on https://github.com/teemtee/tmt/issues/1925
