### ISSUE TITLE
test run with plan doesn't work when I add polarion report.

### ISSUE THREAD

**Issue by yizhanglinux** [teemtee/tmt#1554]
Hello
I want to create a test run and update the test results after the test is executed, but seems it doesn't work, the test case was not executed and only `report` phase was executed, could anyone help check it?

```
$ cat ssd-remote-testrun.fmf
summary: test plan
discover:
  - name: tier1
    how: fmf
    url: https://gitlab.com/yizhanglinux/kernel-tests
    ref: dev-220928-storage-ssd-tmt-migrate
    test:
      - /storage/ssd/test_devs_setup
execute:
    how: tmt
provision:
    how: connect
    guest: hostname
    user: ROOT
    password: PASSWORD

$ tmt run plan --name /storage/ssd/plan/ssd-remote-testrun  report --how polarion --project-id RHELKERNEL --file b.xml --testrun-title storage_ssd_testrun_test1
/var/tmp/tmt/run-014

/storage/ssd/plan/ssd-remote-testrun
    report
        how: polarion
        xUnit file saved at: b.xml
        Polarion upload can be done manually using command:
        curl -k -u <USER>:<PASSWORD> -X POST -F file=@<XUNIT_XML_FILE_PATH> <POLARION_URL>/polarion/import/xunit
        summary: no results found

total: no results found
```

**Comment by KwisatzHaderach** [comment]
Not sure, but I think you specifying report from command line overrides steps defined in plan, IMO adding -a after run should solve this, as that will run all the steps.

**Comment by psss** [comment]
Yes, using `tmt run --all plan --name ... report --how polarion ...` should fix the problem. Reporting results is also possible after the run is finished in the following way:

```
tmt run plan --name ...
tmt run --last report --how polarion ...
```

See also the [Select Steps](https://tmt.readthedocs.io/en/stable/examples.html#select-steps) section for more detailed info about how the steps selection works.

**Comment by yizhanglinux** [comment]
yes, it works now, thanks all for the help, close this issue now.
