### ISSUE TITLE
Update the overview of essential classes

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#1559]
The class structure overview has not been updated for some time:

* https://tmt.readthedocs.io/en/stable/classes.html#class-structure

Would be nice to include all recently added classes, e.g. `StepData` and friends. We probably do not need each and every class listed there but the overall structure of essential classes helps to more quickly understand how things work.

**Comment by idorax** [comment]
To get the class hierarchy, `pydoctor` can be used to create it, e.g.
```bash
pip install pydoctor

mkdir /tmp/doc
git clone https://github.com/teemtee/tmt.git /tmp/doc/tmt
cd /tmp/doc
pydoctor --make-html --html-output=/tmp/tmt-docs-pydoctor tmt/tmt
```

**Comment by idorax** [comment]
The new `Common` tree looks like:
```
Common
├── Clean
├── Core
│   ├── Plan
│   ├── Story
│   └── Test
├── Guest
│   ├── GuestContainer
│   ├── GuestLocal
│   └── GuestSsh
│       ├── GuestArtemis
│       └── GuestTestcloud
├── InstallBase
│   ├── InstallDnf
│   │   └── InstallYum
│   └── InstallRpmOstree
├── Phase
│   ├── Action
│   │   ├── Login
│   │   └── Reboot
│   └── BasePlugin
│       ├── GuestlessPlugin
│       │   ├── DiscoverPlugin
│       │   │   ├── DiscoverFmf
│       │   │   └── DiscoverShell
│       │   ├── ProvisionPlugin
│       │   │   ├── ProvisionArtemis
│       │   │   ├── ProvisionConnect
│       │   │   ├── ProvisionLocal
│       │   │   ├── ProvisionPodman
│       │   │   └── ProvisionTestcloud
│       │   └── ReportPlugin
│       │       ├── ReportDisplay
│       │       ├── ReportHtml
│       │       ├── ReportJUnit
│       │       └── ReportPolarion
│       └── Plugin
│           ├── ExecutePlugin
│           │   └── ExecuteInternal
│           │       └── ExecuteUpgrade
│           ├── FinishPlugin
│           │   ├── FinishAnsible
│           │   └── FinishShell
│           └── PreparePlugin
│               ├── PrepareAnsible
│               │   └── FinishAnsible
│               ├── PrepareInstall
│               ├── PrepareMultihost
│               └── PrepareShell
├── Run
├── Status
├── Step
│   ├── Discover
│   ├── Execute
│   ├── Finish
│   ├── Prepare
│   ├── Provision
│   └── Report
└── Tree
```

**Comment by happz** [comment]
There will be some changes after #1457, I'd therefore wait for type annotations to be done. Or maybe automating this particular step, so we wouldn't have to remember it needs to be done :)

**Comment by idorax** [comment]
> There will be some changes after https://github.com/teemtee/tmt/pull/1457, I'd therefore wait for type annotations to be done. Or maybe automating this particular step, so we wouldn't have to remember it needs to be done :)

It's a good idea to automating it, @happz, can we just write a simple bash script or a Python script to create the class trees?
