### ISSUE TITLE
Decouple logging from objects and base classes

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#1565]
Logging is baked into many classes, anything based on `tmt.utils.Common` has methods like `debug` and `info` that handle verbosity checks, indentations, colors, and logging into file *and* console. While having those methods is absolutely handy, the fact code is embedded into every class makes it much harder to parametrize it, influence, or redirect the output. I believe this will become painfully visible when we start cutting into parallelization where observability is crucial, and several possible modes of output have been suggested already (everything in a single stream/file vs per thread stream/file, "window" for each thread on the same screen, interleaving, prefixing, `screen` or `tmux` integration, `multitail`, etc.) - extending the current implementation of logging might be near to impossible.

My proposal would be to decouple logging from `Common` class:

* every object derived from `Common` would be given a logger object when instantiated. This may very well be the very same logger every time - the dependency injection does not mean every `Common` instance would have its own logger instance.
* `Common` may still provide helper methods in its namespace, proxying calls to the logger
* https://docs.python.org/3/library/logging.html is very capable, I'd avoid inventing anything but custom handlers and formatters - `logging` would do the heavy lifting.
* when needed, code may spawn custom loggers to suit the needs of the situation. Imagine the multihost scenario, with parallel execution of 2 "threads" (client & server, for example):
  * the user has no special needs? Give both "threads" current logger, they would emit their output into the same channels (log file & console) interleaved.
  * too messy? Clone logger for each thread, and add custom formatter adding a prefix -> threads emit to same channels, but each line is prefixed with some kind of thread ID (while their master is left unprefixed).
  * is the flavor of the week threads logging into their own files while the console is shared? Clone logger, leave console handler untouched, and give each logger its own handler pointing to a dedicated log file under workdir.
  * a single log is fine, but the user wants to attach `screen` or `tmux` to observe the console output of each thread? Clone logger, leave logfile handler untouched, and add a custom handler that spawns ptty for `screen` to attach to (or does similar magic...).

The thing is, as long as `Common` and its child classes work with a given "logger" object only, the behavior of the logging can be easily changed from outside without `Common` needing a change. Separation of concerns, dependency injection, all those cool buzzwords, it would provide very clear advantages.

A more or less smooth transition could start with mimicking the current implementation: single global logger, a handler pointing to a logfile in workdir, a (custom) handler for console output (based on `click.echo()`), every `Common` instance is given this single logger. Custom formatter would be fully capable of supporting `indent`, `shift`, `color`, and other parameters `tmt` logging helpers offer. Custom `Filter` could handle verbosity transparently.

There is a custom logger-like implementation in `fmf.utils`, but I'd argue it's up to tmt codebase to control logging, and fmf API should be open to being given a logger to use. Using its own default logger is fine as long as no better one has been provided by library user. Every `from fmf.utils import log` in fmf code will become a problem for tmt control over where and what is logged - `Tree(..., logger=a_logger_prepared_by_tmt)` needs to be a common practice, because that particular creation of a `Tree` instance might be required to log into a specific file or stream, and multiplexing global `log` object won't be able to handle this kind of functionality. Mutable global state strikes again :)

**Comment by happz** [comment]
@psss @lukaszachy @thrix @FrNecas what do you think, guys? I can start hacking on this right away - I even wanted to dip my toes into the parallelization already, running `prepare` and other steps at the same time, but the logging keeps sneaking in everywhere I move, ruining any kind of reconciliation. So I thought it might be a good start to resolve this first, and with annotations being almost ready, it could be fairly safe (fingers crossed...)

**Comment by psss** [comment]
@happz, thanks much for putting this together! The outline looks good to me and from what I can see it should provide enough flexibility and extensibility for the future. I agree with using the `logging` module as much as possible together with handlers & formatters and avoid reinventing stuff.

It makes sense especially because some parts of the code (e.g. those related to `tmt test export` or handling `beakerlib` libraries) do not use objects inheriting from `Common` which causes problems. It would be nice to have verbose and debug logging working for these areas consistently as well.

So all in all `+1` from me to clean up this part. We just need to ensure that the `verbose` and `debug` levels are correctly handled, for example propagation of `tmt run -v` to `tmt run discover -v`.

**Comment by happz** [comment]
@psss The patch is starting to do what I wanted, I'm able to pass some debug tests, and output matches output made by unpatched tmt most of the time, but, one more question: are we fine with sending all logging output to stderr from now on? The current behavior is not as clear as what I'm getting from my patch by default, thanks to Python's logging using `sys.stderr` by default, and tmt often mixes together an output and diagnostics aka logs. This could be a problem for commands that do actually have output - unlike `tmt run`, `tmt test story --format=rst` produces a genuine output, and still might need to emit debugging messages here and there.

So my proposal would be "all logs go to stderr, output to stdout if there's any". This would require changes to plenty of tests, I suppose (`tmt run ... | tee` would need an update to follow stderr, e.g. `2>&1 >/dev/null | tee`), but I'd argue it'd be worth the effort. Users and developers would be presented with a less fuzzy picture, IMO.

If not, then we need a solution not just for `tmt * export` family of subcommands, but also for `tmt * ls` or `tmt * show`, as their output might be easily intermixed with logging on stdout, making it hard to use.

**Comment by psss** [comment]
Ack for consistently sending all debugging stuff to `stderr`. The output of `tmt * ls`, `tmt * show` should go to `stdout`. For `tmt * export` it depends: For simple export to `yaml` or `dict` it should clearly be `stdout`, not sure for `tmt test export --how nitrate`, probably report the progress to `stderr`?

As far as `tmt run` is concerned, we are reporting progress of what's happening with a few exceptions like `tmt run provision --how minute --list-images` which should clearly go to `stdout`. But to make this nicely and consistently working we should probably send all the output that is never (or rarely) expected to be consumed by users to `stderr`.

@lukaszachy, @thrix, @FrNecas, any thoughts here?

**Comment by happz** [comment]
WRT expirt to Nitrate/polarion: IIUIC, their export does not result in actual printable output, but plenty of logging and progress messages, plus changes in remote services. I’m not aware of any output one might redirect into a file and say “this is the test exported to nitrate”. So nothing for stdout, AFAICT. Progress and logs, yes, thise would go to stderr (now the are done by click.echo(), to puzzle us even more).

WRT list image/flavor - absolutely, that’s output, therefore stderr.

The rule of thumb I’m following - can I pipe the output to another command, not messed up with logging?
