### ISSUE TITLE
Review of uses of `# type: ignore`

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#1567]
(Blocked by the enablement of follow_imports in mypy.ini, blocked by finishing base.py annotations https://github.com/teemtee/tmt/pull/1457)

* `mypy` should complain us about pointless and no-longer-necessary uses
* for some of the rest, we might have already issues under https://github.com/teemtee/tmt/issues/1411 - this covers changing some classes to generic types to achieve more fitting annotations
* some of the remaining ones can be amended, with more work, let's file issues for those
* and the rest would just have to stay with us.

In general, if there's an issue related to a `type: ignore` comment, let's mention it in code, in a comment (e.g. Will be fixed with https://github...), and if the waiver is to stay and won't be fixed, let's add a comment explaining why it's there to stay.

**Comment by psss** [comment]
This should now be unblocked as both #1598 and #1457 are merged.
