### ISSUE TITLE
HW and SW requirements - distro compatibility

### ISSUE THREAD

**Issue by mmacura311** [teemtee/tmt#1582]
When running tmt upgrade plans and tests using testing-farm, there is sometimes a challenge getting proper hardware to run rhel upgrades, especially on non-x86 architectures.
Leapp utility is checking for hw compatibility on the target rhel version and if not met, the upgrade is inhibited.
Currently the user has no control of which hardware is provisioned by the tooling and in case the provided machine is not compatible with rhel-(X+1) version, the upgrade will not proceed.

This ticket is a RFE to add such functionality to tmt and later to testing-farm (and whatever piece of ifrastructure machinery lies inbetween).

historical context:
When running upgrade tests using beaker, beaker accepts following xml syntax

```
<hostRequires>
  <and>
    <system>
      <compatible_with_distro osmajor="RedHatEnterpriseLinux9" arch="x86_64"/>
    </system>
  </and>
  <system_type value="Machine"/>
</hostRequires>
```
      
even multiple compatible_with_distro tags are possible. eg requesting a machine with rhel-6 that is compatible all the way up to rhel-9

```
<distroRequires>
        <and>
                <distro_name op="=" value="RHEL-6.10"/>
                <distro_variant op="=" value="Server"/>
                <distro_arch op="=" value="x86_64"/>
        </and>
</distroRequires>
<hostRequires>
        <and>
                <system>
                        <compatible_with_distro osmajor="RedHatEnterpriseLinux7" arch="x86_64"/>
                </system>
                <system>
                        <compatible_with_distro osmajor="RedHatEnterpriseLinux8" arch="x86_64"/>
                </system>
                <system>
                        <compatible_with_distro osmajor="RedHatEnterpriseLinux9" arch="x86_64"/>
                </system>
        </and>
</hostRequires>
```

if using bkr wow the command looks as following
`bkr wow --distro rhel-6.10 --arch x86_64 --compatible rhel-7.0 --compatible rhel-8.0 --compatible rhel-9.0 --reserve`

Example of what is needed from tmt:
```
provision:
    how: beaker
    family: rhel-7
    tag: released
    compatible: rhel-8
    compatible: rhel-9
```
Open points: I'm not sure if "provision" is right section for this to be added. Also the beaker implementation had also a architecture key-value pair. I do not think is necessary as we do not have any case where we would need cross-arch compatibility (that does not make much sense, does it?)
I'm open to discussion and suggestions.

**Comment by mmacura311** [comment]
One more thing that comes to mind:
this feature should be compatible with the upgrade plugin. In the upgrade's plugin upgrade plan when the "compabitility" key is declared, I would expect that this is resolved by tmt prior requesting the machine. This way the the "user" that is using upgrade-plugin does not have to care about this configuration in it's own plan/test, but can be handled in the upgrade plan itself.

**Comment by psss** [comment]
Thanks for describing the use case in detail. I believe a natural place for this type of requirement would be the [hardware](https://tmt.readthedocs.io/en/latest/spec/plans.html#hardware) section of the `provision` step. The config could look like this:

```yaml
provision:
    how: beaker
    image: rhel-7
    hardware:
        compatible:
          - rhel-8
          - rhel-9
```

Regarding respecting the `provision` step of the upgrade plan: Currently only selected keys of the `discover` step are propagated and the rest of the upgrade plan is ignored. @FrNecas, please correct me if I'm wrong. Enabling `provision` step from the remote upgrade plan should be possible but I guess this will need some more substantial changes (and discussion).
