### ISSUE TITLE
Test phases of a beakerlib test not counted properly when scheduling a single test multiple times

### ISSUE THREAD

**Issue by kkaarreell** [teemtee/tmt#1615]
Having a single beakerlib test case multiple times in a tmt test plan
```
discover:
  test:
    - foo
    - foo
    - foo
```
runs the test multiple times correctly, however test phases are not counted correctly. The counter is not reset when one test iteration ends and keeps increasing. This is not happening when running a test manually multiple times via `./test.sh`.
So let's say a test has 4 phases. In the output one will see the following:
```
$ tmt run -vvv ...
...
::   Duration: 4s
::   Phases: 4 good, 0 bad
::   OVERALL RESULT: PASS (unknown)
...
::   Duration: 4s
::   Phases: 8 good, 0 bad
::   OVERALL RESULT: PASS (unknown)
...
::   Duration: 4s
::   Phases: 12 good, 0 bad
::   OVERALL RESULT: PASS (unknown)
```

**Comment by kkaarreell** [comment]
@sopos FYI

**Comment by sopos** [comment]
The problem is that the BEAKERLIB_DIR points to the same location for all the test instances. While this is good for the case of reboot during the test, it it bad for more independent test instances.
We need to create separate directories in the workdir for individual test instances, I think.

**Comment by kkaarreell** [comment]
I guess tmt should know that it is going to reboot inside a test so any test start where reboot wasn't scheduled previously should have a new workdir.

**Comment by sopos** [comment]
yeap, seems to me like a duplicate of it

**Comment by kkaarreell** [comment]
I am closing the issue, it has been resolved through https://github.com/teemtee/tmt/issues/1614 and I can confirm that the problem is now gone.
