### ISSUE TITLE
Documentation: add version od TMT to documentation when moved form idea to implemented stae

### ISSUE THREAD

**Issue by jscotka** [teemtee/tmt#1647]
Hi,
As we've discussed with @psss, would be beneficial to see when adding new features when it was incorporated into TMT.
So please add there also version TMT when it was added.
Usecases:
  - be able to debug why something does not work well.
  - be able to use some older version of TMT if important, and see which features are supported. e.g. older distros, where there are no new releases of TMT

**Comment by psss** [comment]
We could include this information as a restructured text `note` in the `description` of the relevant `story` or, perhaps, introduce a new core key `note` which would be automatically rendered at the end of `story` when generating the docs. Thoughts?

**Comment by jscotka** [comment]
I've also have in mind to add it into RST directly, not sure if add core attribute `note` somehow differs from `description`, but why not.

**Comment by happz** [comment]
If included in the `description` block, and if Sphinx-flavored RST would be acceptable, then we can use a few more fitting directives, `versionadded`, `versionchanged`, `deprecated`. See https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded

**Comment by psss** [comment]
Outlined a simple example in #1651.
