### ISSUE TITLE
Prune the run workdir during the `finish` step

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#1707]
Based on recent problems with disk space usage discussed in TFT-1735 and as one of possible ways how to address #645 I propose to prune the workdir by default at the end of the `finish` step and remove all files which are not "interesting" for user review. I suggest to keep only the following files and directories for each plan:

```
.
├── data
├── discover
│   ├── step.yaml
│   └── tests.yaml
├── execute
│   ├── data
│   ├── results.yaml
│   └── step.yaml
├── finish
│   └── step.yaml
├── prepare
│   └── step.yaml
├── provision
│   ├── guests.yaml
│   └── step.yaml
└── report
    └── step.yaml
```

These are basically data generated by tests, step data which could be useful for config review and step api data such as `tests.yaml`, `guests.yaml` and `results.yaml`. In addition to these we should probably keep also the `log.txt` file which contains detailed debugging information. On the other hand, this file can be quite large because of all the details.

A new `tmt run --keep` option would allow to keep the whole run directory for future use if desired.

**Comment by martinpitt** [comment]
Thanks @psss ! That's indeed not too far from what I have in https://gitlab.com/testing-farm/infrastructure/-/merge_requests/95 -- i.e. we both remove the whole `tree/`. I also remove the whole `discover/`, as I didn't find the `step.yaml` and `test.yaml` files particularly interesting -- the are completely derived from the source's plans, and don't contain any variable runtime information. Out of interest, why are they useful?

As it will take a bit to implement this in tmt, I propose that we do a quick fix on the TF side to prune these files, and once `tmt` starts doing that, we can simplify the code again. Thanks!

**Comment by happz** [comment]
+1 for keeping those `*.yaml` & `log.txt`, I find them very useful. Yes, it can be a large file, with all the debugging, but it's extremely useful when things do not work out as expected, all executed commands are there, all decisions taken.

@martinpitt those `*.yaml` files are used by tmt internally, as tmt allows re-using a given workdir, sort of a save/restore-and-run-again functionality. Probably of no use to a general user, it's all transparently handled by tmt, I'd put them in the same area as `log.txt` when the run's done - useful for debugging.

**Comment by martinpitt** [comment]
BTW, no doubt about `log.txt` -- that is one of the most important files. I was just wondering about discover/{step,test}.yaml. @happz: Right, these may be useful for debugging tmt itself, but not necessarily for a user to debug a failed test. OTOH, `log.txt` is useful for package/test developers.

**Comment by psss** [comment]
> I'd put them in the same area as `log.txt` when the run's done - useful for debugging.

Yes, I feel it in the same way: Not necessary for user when doing just a regular log review but can be very useful for debugging when something goes wrong. For example, to check `tests.yaml` to ensure that all test metadata have been correctly gathered.

**Comment by happz** [comment]
> BTW, no doubt about `log.txt` -- that is one of the most important files. I was just wondering about discover/{step,test}.yaml. @happz: Right, these may be useful for debugging tmt itself, but not necessarily for a user to debug a failed test. OTOH, `log.txt` is useful for package/test developers.

Seems like we're getting a set of files that are useful for debugging tmt, but much less for a generic tmt user who knows nothing about tmt internals. As another level of pruning, it might make sense to add some kind of "developer-or-CI-system" option which would keep these files around, and remove them with the rest of not so important bits from the workdir otherwise.

Those `*.yaml` files are fairly small, if `log.txt` is kept, I'd keep them around too, assuming one keeps `log.txt` for possible debugging and may need these files as fell, as they complete the picture of what tmt did and how. Preserving them doesn't cost that much (especially when the biggest pile of files, directories, inodes and space - tree - has been removed, freeing a lot of resources).

**Comment by martinpitt** [comment]
Ack, agreed -- the most pressing issue is indeed to get rid of the two source tree copies. The few yaml files there don't hurt at all, I was just curious for what they are useful. Thanks!

**Comment by lukaszachy** [comment]
Possible problem: When user reruns some steps and finish already ran -> will have to make sure to rerun discover each time.

**Comment by psss** [comment]
Yes, in some respect this affects the current status as well: For example, it's necessary to run `provision` again in order to be able to execute tests on the guest which has been already cleaned up if `finish` has completed its tasks. On the other hand, the common use case like `tmt run --last report` should be working just fine.
