### ISSUE TITLE
Podman issue: systemstack called from unexpected goroutine

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#1735]
Recently the error appeared several times during testing:

 * [centos-stream-9](https://artifacts.dev.testing-farm.io/0fd2ed0d-dd29-4fb1-b128-02cc3a365988/)
 * [fedora-37](https://artifacts.dev.testing-farm.io/326d9585-4fa3-44d9-9eee-c6221f93f205/)

Log looks like this:

```
        summary: 1 preparation applied
    execute
        how: tmt
        order: 50
        exit-first: False
    finish
        container: stopped
        container: removed
        prune: Prune plan workdir '/var/tmp/tmt/run-001/plans/defined'.
        summary: 0 tasks completed
Failed to run command: None Reason: Command returned '-5'.

stderr (1 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal: systemstack called from unexpected goroutine

:: [ 13:37:31 ] :: [   FAIL   ] :: Command 'tmt -c distro=centos-8 run -arvvv provision -h container -i centos:stream8 plan --name defined test --name without 2>&1 | tee /tmp/tmp.5pyD0gOcfM' (Expected 0, got 2)
```

Let's see if the error becomes more frequent...

**Comment by jnovy** [comment]
Suggest containcting golang toolset team for investigation.

**Comment by lukaszachy** [comment]
`Failed to run command: None` ? Why `None`?

**Comment by derekparker** [comment]
Is there any way to get the full stacktrace from the fatal call?

**Comment by psss** [comment]
Not sure how to achieve this. Any suggestions welcome. It seems that the `fedora-37` failure happened during [start](https://github.com/teemtee/tmt/blob/main/tmt/steps/provision/podman.py#L62) where we basically call `podman image exists`, `podman pull` and `podman run`.

**Comment by psss** [comment]
Another possibly related error appeared [here](https://artifacts.dev.testing-farm.io/90195849-7488-472d-9acf-69ba591f40fc/) on `fedora-rawhide`:

```
    provision
        how: container
        image: fedora
    fail: Failed to run command: None Reason: Command returned '125'.
Failed to run command: None Reason: Command returned '125'.

stderr (1/1 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: copying system image from manifest list: parsing image configuration: Get "https://cdn.registry.fedoraproject.org/v2/fedora/blobs/sha256:9538a60368f65b52c44a612bbe694a0bfdeb57f081dee4f9888fe7825c6488b9": dial tcp: lookup cdn.registry.fedoraproject.org: no such host
```

**Comment by psss** [comment]
Today [failed](https://artifacts.dev.testing-farm.io/c6c84e91-bed7-4fea-bad9-1b9f95be0582/) again on `centos-stream-9`.

**Comment by psss** [comment]
One more [instance](https://artifacts.dev.testing-farm.io/37c634de-c14c-40e1-a4a7-8415ada13dca/) from today.

**Comment by derekparker** [comment]
@psss which version of Go is being used in the latest example?

**Comment by psss** [comment]
@derekparker, actually the `golang` package is [not installed](https://artifacts.dev.testing-farm.io/a0a30468-f744-4b17-8a6b-228d328ccd91/) on the guest. The failure seems to be coming from `podman`.

**Comment by derekparker** [comment]
@psss Sorry, my question wasn't clear, I meant to ask which version of Go was used for compilation.

Is there any way you could inject the environment variable `GOTRACEBACK=system` into the build to get more information?

**Comment by psss** [comment]
From the [install log](https://artifacts.dev.testing-farm.io/37c634de-c14c-40e1-a4a7-8415ada13dca/guest-setup-920d03bb-818d-4d6d-88d5-56c962492620/artifact-installation-920d03bb-818d-4d6d-88d5-56c962492620/2-Install-packages.txt) I can see the package was `podman-4.3.1-1.fc37.x86_64.rpm` which is koji build [2087535](https://koji.fedoraproject.org/koji/buildinfo?buildID=2087535) and from its [root log](https://kojipkgs.fedoraproject.org//packages/podman/4.3.1/1.fc37/data/logs/x86_64/root.log) it seems `golang-1.19.2-1.fc37.x86_64` was used. Is this sufficient?

**Comment by psss** [comment]
One more [failure](https://artifacts.dev.testing-farm.io/538f187f-40e7-48b7-b9ba-650c5ac3c042/), today on `centos-stream-9`.

**Comment by derekparker** [comment]
I've filed an upstream issue to get more insight.

**Comment by psss** [comment]
Thanks much, @derekparker!

**Comment by psss** [comment]
Today's [failure](https://artifacts.dev.testing-farm.io/546e1a03-7754-4a47-a242-46fb8d1e7892/) on `rawhide` provided the following error message:

```
time="2023-01-17T09:41:56Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
fatal: systemstack called from unexpected goroutine
```

Not sure whether this is related.

**Comment by psss** [comment]
The failure did not show for a while. Closing for now.
