### ISSUE TITLE
.git dir is not copied to SUT

### ISSUE THREAD

**Issue by phracek** [teemtee/tmt#1744]
Is there any reason, why `.git` directory is not copied to SUT?
https://github.com/teemtee/tmt/blob/main/tmt/steps/discover/shell.py#L283

I am asking because our container test suite needs `git` command to work with GitLab repository.

Just for info:
https://github.com/teemtee/tmt/commit/6a4c652c3a34b8134bd01d0db9dbd15dff304eb7#diff-65eb76145e750897efecb46c5d03da42a7d45595405582045389062c1d6bbb60R17

In our test suite (https://github.com/sclorg/container-common-scripts/blob/master/build.sh#L136), we call `git rev-parse --short HEAD` but we received:
```
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by phracek** [comment]
We are using Testing Farm for upstream projects, where we clone our repositories by our self, for GitLab issue it is not working properly. Witout git repository, we are not able to run test suite which was working before. I don't know if it is a regression, but working with GitLab projects, which are already `git` repositories and syncing them to guest Testing Farm system w/o `.git` repository is not a right approach.

**Comment by lukaszachy** [comment]
We need to add `--sync-repo` option  to the 'shell' plugin as well (fmf plugin has it)

**Comment by phracek** [comment]
Do you have an ETA, of when it will be available for testing?

**Comment by idorax** [comment]
To add `--sync-repo` option to the `shell` plugin, we need adding method `options()` to class `DiscoverShell`.

**Comment by idorax** [comment]
Hi @phracek, would you please share the related `fmf` pieces and the whole `tmt` command you used? I'd like to manually test the fix I proposed, thanks!

**Comment by phracek** [comment]
@idorax The whole tmt command is run from GitLab by the OSCI team. See here https://gitlab.com/redhat/rhel/containers/nodejs-10/-/merge_requests/8.

The link to the testing farm job is here: http://artifacts.osci.redhat.com/testing-farm/343c968a-eb78-4717-876f-be5dcfd3d512
