### ISSUE TITLE
tmt.Tree().plans() fails with Assertion error, missing context_object

### ISSUE THREAD

**Issue by KwisatzHaderach** [teemtee/tmt#1746]
$ipython3
Python 3.9.13 (main, May 24 2022, 21:28:44) 

In [1]: import tmt

In [2]: tmt.Tree().plans()
AssertionError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 tmt.Tree().plans()

File /usr/local/lib/python3.9/site-packages/tmt-1.19.0-py3.9.egg/tmt/base.py:2141, in Tree.plans(self, keys, names, filters, conditions, run, links, excludes)
   2138     sources = None
   2140 # Build the list, convert to objects, sort and filter
-> 2141 plans = [Plan(node=plan, run=run)
   2142          for plan in [
   2143              *self.tree.prune(keys=local_plan_keys, names=names, sources=sources),
   2144              *self.tree.prune(keys=remote_plan_keys, names=names, sources=sources),
   2145     ]]
   2147 plans = self._filters_conditions(
   2148     sorted(plans, key=lambda plan: plan.order),
   2149     filters, conditions, links, excludes)
   2150 if Plan._opt('shallow'):

File /usr/local/lib/python3.9/site-packages/tmt-1.19.0-py3.9.egg/tmt/base.py:2141, in <listcomp>(.0)
   2138     sources = None
   2140 # Build the list, convert to objects, sort and filter
-> 2141 plans = [Plan(node=plan, run=run)
   2142          for plan in [
   2143              *self.tree.prune(keys=local_plan_keys, names=names, sources=sources),
   2144              *self.tree.prune(keys=remote_plan_keys, names=names, sources=sources),
   2145     ]]
   2147 plans = self._filters_conditions(
   2148     sorted(plans, key=lambda plan: plan.order),
   2149     filters, conditions, links, excludes)
   2150 if Plan._opt('shallow'):

File /usr/local/lib/python3.9/site-packages/tmt-1.19.0-py3.9.egg/tmt/base.py:1043, in Plan.__init__(self, node, run, skip_validation, raise_on_validation_error, **kwargs)
   1039 # Expand all environment and context variables in the node
   1040 with tmt.utils.modify_environ(self.environment):
   1041     self._expand_node_data(node.data, {
   1042         key: ','.join(value)
-> 1043         for (key, value) in self._fmf_context().items()})
   1045 # Initialize test steps
   1046 self.discover = tmt.steps.discover.Discover(
   1047     plan=self, data=self.node.get('discover'))

File /usr/local/lib/python3.9/site-packages/tmt-1.19.0-py3.9.egg/tmt/base.py:1184, in Plan._fmf_context(self)
   1182 """ Return combined context from plan data and command line """
   1183 combined = self.context.copy()
-> 1184 assert self._context_object is not None  # narrow type
   1185 combined.update(self._context_object.fmf_context)
   1186 return combined

AssertionError: 

even though I can do `tmt plans ls` or `tmt plans show` without issues.
I have tmt from git main branch.

**Comment by happz** [comment]
A fix *for this particular issue* is trivial, https://github.com/teemtee/tmt/pull/1747

The question is, is this use case supported? How much is `tmt` package supposed to be usable as an importable library? There might be - there *are* - other places where the existence of CLI "context" object is assumed.

**Comment by KwisatzHaderach** [comment]
We got to it with @psss when debugging trying to create tests for some clickable_urls. As this works fine for tests and stories I would expect also plans to work the same.

**Comment by happz** [comment]
Riiight, importing tmt bits from tests does indeed make sense :)
