### ISSUE TITLE
tmt does not run test with local changes applied, but the changed test is uploaded

### ISSUE THREAD

**Issue by zdohnal** [teemtee/tmt#1787]
Hi,

I use

```
$ tmt run -avvv --skip finish execute --how tmt --interactive test --name . provision --how minute --image rhel8 login
```

for running the locally changed test and log into the machine, but the changed test is only uploaded to the machine, but not run:

```
$ tmt run -avvv --skip finish execute --how tmt --interactive test --name . provision --how minute --image rhel8 login
...
:: [ 07:28:04 ] :: [   PASS   ] :: Start dbus (Expected 0, got 0)
:: [ 07:28:09 ] :: [   PASS   ] :: dbus-send for HP officejet (Assert: expected 0, got 0)
...

[root@zdohnal-1mt-rhel-8-8-0-20230101-0-47642-2023-01-10-12-24 tree]# cd Sanity/dbus-send/
[root@zdohnal-1mt-rhel-8-8-0-20230101-0-47642-2023-01-10-12-24 dbus-send]# ./runtest.sh
...
:: [ 07:28:39 ] :: [   PASS   ] :: Start dbus (Expected 0, got 0)
:: [ 07:28:39 ] :: [   PASS   ] :: busctl for GetBestDrivers (Assert: expected 0, got 0)
...
```

$ rpm -q tmt
tmt-1.21.dev-1.20230109211253122320.main.18.g02a333a.fc37.noarch

Is it a bug or should I use an additional option to the tmt command?

**Comment by psss** [comment]
What do you exactly mean by "uploaded but not run"? I see you are pasting the output of the test execution, so the test must have been executed.

Are you reusing the same tmt run and want to upload changed test code to the guest and execute it again? If that is the use case, you need to add `discover --force` to re-discover the test code and `execute --force` to re-execute the modified test. See also the [Debugging Test](https://tmt.readthedocs.io/en/latest/examples.html#debug-tests) examples.

**Comment by zdohnal** [comment]
> What do you exactly mean by "uploaded but not run"? I see you are pasting the output of the test execution, so the test must have been executed.

@psss my workflow is:

1. make changes in the test locally (I don't commit changes until I know they're fine)
2. want to check how the test performs in tmt, so I use the command above to run it on testing machine and then log into it

So currently tmt runs the test as there weren't any changes (local changes are ignored), but once I check the file which were uploaded to the machine - the files at ```/var/tmp/tmt/run-007/plans/all/tree``` - there are the files with local changes.

IIRC tmt was able to upload the current, locally changed test files the same way and run them right away as 1minutetip can...

> See also the [Debugging Test](https://tmt.readthedocs.io/en/latest/examples.html#debug-tests) examples. The [Aliases](https://tmt.readthedocs.io/en/latest/examples.html#aliases) might come handy as well.

Thanks for the links, but it seems my use case is a little bit different.

**Comment by psss** [comment]
> So basically my question why the uploaded files are not run at the first time :)

That should not be the case. Perhaps, one question: Are you using a specific `ref` in the `discover` step config?

**Comment by zdohnal** [comment]
Ok, omejzlik sent me and updated tmt command, which now does what I want without changing url in plans/all.fmf:

For future reference or alias:

```
$ tmt run -avvv --skip finish plan --default --skip finish execute --how tmt --interactive test --name . provision --how minute --image <image> login
```

or my function in ~/.bashrc:

```
tmt-run() {
  if [ -z "$1" ]
  then
    echo "Error: specify the image - rhel8/rhel9/f36/f35... ."
    return 1
  fi  
  tmt run -avvv --skip finish plan --default --skip finish execute --how tmt --interactive test --name . provision --how minute --image $1 login
}
```

**Comment by psss** [comment]
The examples above have duplicated `--skip finish` option.

> Ok, omejzlik sent me an updated tmt command, which now does what I want without changing url in plans/all.fmf:

Good. Just wonder: What is the use case for the current plan. Shouldn't it be rather fixed?
