### ISSUE TITLE
Cannot use mypy for 3rd party plugins as tmt is missing py.typed marker

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#1796]
Would by nice if 3rd party can use tmt type declarations.

Currently it fails with `src.py:17: error: Skipping analyzing "tmt": module is installed, but missing library stubs or py.typed marker  [import]`

See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker

**Comment by happz** [comment]
Ha, `.py.typed` **was** in my initial drafts, but didn't make it to the final annotation patches.
