### ISSUE TITLE
Retry vagrant plugin installation on failure

### ISSUE THREAD

**Issue by pvalena** [teemtee/tmt#182]
vagrant provision install missing plugins using, but it would be handy not to rely on first try; in case there are some network issues.

https://github.com/psss/tmt/blob/4ffc9c342c428695a54b20d958138a70a06655f9/tmt/steps/provision/vagrant.py#L235

**Comment by psss** [comment]
The `vagrant` plugin has been removed a long time ago and there are currently no plans to reintroduce it.
