### ISSUE TITLE
Override test duration from plan

### ISSUE THREAD

**Issue by pellecchialuigi** [teemtee/tmt#1843]
As a tester, I may need to modify some libraries that the test uses.
Those instrumentations can significantly change the test duration and I need to be able to run those tests in that scenario without requesting changes in the test fmf file.
A possible solution could be to override the duration using a mathematical operation.
example: duration: *3
example: duration: +1h

**Comment by lukaszachy** [comment]
Outcome of the discussion on the hacking session:

Create new attribute which will allow to change the duration: either to set explicit value or mathematical operation on existing value ( +1s, +1m, +1h, *1.2 )

Attribute could be used in `discover` phases where it will affect tests gathered in that phase as well as in `execute` step where it will affect all discovered tests.

**Comment by lukaszachy** [comment]
Use case we should cover: One arch is slower than the others so:
```
adjust:
 - when: arch == x86_64
   duration: '*2'
```

**Comment by lukaszachy** [comment]
Lets' aim for next release.

**Comment by psss** [comment]
Has the essential part of the use case been covered by #1972? Currently [duration](https://tmt.readthedocs.io/en/latest/spec/tests.html#duration) allows to provide multiple values:

```
# Combination & repetition of time suffixes (total 4h 2m 3s)
duration: 1h 3h 2m 3
```

So it's possible to use context `adjust` to extend it with a custom value. Is the multiplication support important enough to dive into this now?

**Comment by lukaszachy** [comment]
Unfortunatelly we are still missing way how to modify duration from the PLAN, which is necessary when
- one cannot modify test repo
- plan changes duration significantly (e.g. experiment on very slow machine, or running with profiling, custom LD_PRELOAD....)

**Comment by psss** [comment]
Ah, I see, the plan part is here essential.

**Comment by happz** [comment]
@lukaszachy is this issue going to land in 1.29? I'd propose postponing once more to 1.30.

**Comment by lukaszachy** [comment]
Started https://github.com/teemtee/tmt/discussions/2430

**Comment by lukaszachy** [comment]
Status comment: 
- [ ]  #2845.
- [ ] fmf feature to call adjust with explicit set of rules (in #2430), PR TBD
- [ ] finally changes to tmt to have attribute in discover to specify the rules for above and call it - PR TBD

Not sure if 1.33 is feasible as the third point will require fmf release to happen first.
