### ISSUE TITLE
Invalid PATH to logs in results.yaml with `result:custom`

### ISSUE THREAD

**Issue by comps** [teemtee/tmt#1879]
Suppose I have a test called `/oscap-scan`, which has `main.fmf` like
```yaml
test: ./test.sh
result: custom
```
and `test.sh` like
```bash
#!/bin/bash
touch "$TMT_TEST_DATA/my-log.txt"
cat > "$TMT_TEST_DATA/results.yaml" <<EOF
- name: /some/subtest
  result: fail
  log:
  - my-log.txt
EOF
```

I then run this via `tmt run -av report -h html -o` to generate + open a HTML report, which looks fine:

![image](https://user-images.githubusercontent.com/1620988/221661797-9de389e1-ffbb-4540-aa86-3a60aeac0718.png)

The link at the bottom works, it points to `/var/tmp/tmt/run-062/log.txt` which exists and is valid.

However the `my-log.txt` link itself is a 404, because it points to
* `/var/tmp/tmt/run-062/plans/example/execute/my-log.txt`

but the file is actually in
* `/var/tmp/tmt/run-062/plans/example/execute/data/oscap-scan/data/my-log.txt`

---

This unfortunately isn't trivial to fix - the `html.py` loop happens across results, not tests:
```python
        # Write the report
        filename = Path('index.html')
        self.write(
            filename,
            data=template.render(
                results=self.step.plan.execute.results(),
                base_dir=self.step.plan.execute.workdir,
                plan=self.step.plan))
```
and the jinja2:
```html
        <td class="log">
        {% for log in result.log %}
            <a href="{{ base_dir | linkable_path | urlencode }}/{{ log | urlencode }}">{{ log | basename }}</a>
        {% endfor %}
```

An easy fix would be to simply require that logs for a particular result are always under the prefix of that result's `name`, meaning the log should be actually placed into `$TMT_TEST_DATA/some/subtest/my-log.txt`, and then we could simply do `base_dir ~ '/' ~ result.name` to get there.

(If I'm reading the code correctly.)

However the way the `log` is specified in the `result:custom` documentation really suggests it should be in `TMT_TEST_DATA` and copying out the logs into a special structure, when they possibly never started in that structure, might be extra work for the test author.

Fixing the code to always take logs relative to `TMT_TEST_DATA` would however likely require somehow iterating over tests (not results) and somehow associating a list of results to each test.

**Comment by lukaszachy** [comment]
Thanks for the report. The `results.yaml` is the culprit here as it  doesn't process the log path, for which we say that `PATH is the test log output path, relative to the execute step working directory.

IMO it doesn't make sense for `report` plugins to care about the origin of the results.
The processing of result:custom should take care of the path changes.

**Comment by comps** [comment]
Where would the test get this "execute step working directory"? Looking at https://tmt.readthedocs.io/en/stable/overview.html#variables , none of them seem to be anything similar.

Wouldn't it be better to maybe store `TMT_TEST_DATA` in each `class Result` instance (in some relative form), so that report can use it when processing a list of results?

Thanks.

**Comment by happz** [comment]
Didn't we discuss this - or a similar - issue recently? It sounds very familiar, at least the "loading custom results need to fix log paths" bit. IIRC, we were about to modify `check_custom_results()` to change loaded paths to be relative to a different directory before adding loaded results on the pile with other `Result` instances.

**Comment by lukaszachy** [comment]
We did. But I can't find an issue for that.

However I (now) think we should avoid troubles for us and ask custom results to be always inside TMT_TEST_DATA. Mainly to avoid possibility to overwrite foreign logs  (either by mistake or malicious intent). That would make it easier for `check_custom_results()` to make the `PATH` "relative to to execute workdir" as per the definition of the results.yaml file.

User of course could use TMT_PLAN_DATA (just these two locations are supposed to be synced back to host) however in the we would need to check if log belongs to the test or is unique across run ... I'd prefer to avoid doing that.

How much resistance would appear if the custom results path has to start with TMT_TEST_DATA and relative paths will be forbidden?

**Comment by happz** [comment]
> How much resistance would appear if the custom results path has to start with TMT_TEST_DATA and relative paths will be forbidden?

I for one would try to stick with relative paths. In CI lands, at least in our experience, tmt and other tools are often isolated in a container, with a working directory mounted into the container, therefore the absolute path of a log file inside the container and on the guest would be different (e.g. `/WORKDIR` inside is `/var/lib/jenkins/jobs/ci-foo/workspace-2/`). Easy to work with as long as absolute paths do not sneak in.

I like the "log path shall be relative to `$TMT_TEST_DATA`" rule, it doesn't seem like a big burden to me.

**Comment by lukaszachy** [comment]
Change the description as this affects all report plugins.

For now the situation is quite not friendly:
If the log is created as `$TMT_TEST_DATA/log.txt` then the log path has to be set to either `$TMT_TEST_DATA/log.txt` or `/data/<plan>/<test>/data/log.txt`  

The later is per specification but I'm not sure if one can access plan name (or test name) easily.

**Comment by lukaszachy** [comment]
> I for one would try to stick with relative paths. In CI lands, at least in our experience, tmt and other tools are often isolated in a container, with a working directory mounted into the container, therefore the absolute path of a log file inside the container and on the guest would be different

I meant that absoulte path in custom results. The PATH in resulting results.yaml will be relative to the execute dir as is it now and Results class will take care of the translation.

How about accepting both then?
If absolute it has to start with $TMT_TEST_DATA (otherwise an error will happen) or relative to the TMT_TEST_DATA.

So for `$TMT_TEST_DATA/log.txt` one could use either
`log: [ log.txt ]`  or `log: [ $TMT_TEST_DATA/log.txt ]`, with the $TMT.. expanded of course.

**Comment by happz** [comment]
> > I for one would try to stick with relative paths. In CI lands, at least in our experience, tmt and other tools are often isolated in a container, with a working directory mounted into the container, therefore the absolute path of a log file inside the container and on the guest would be different
> 
> I meant that absoulte path in custom results. The PATH in resulting results.yaml will be relative to the execute dir as is it now and Results class will take care of the translation.
> 
> How about accepting both then? If absolute it has to start with $TMT_TEST_DATA (otherwise an error will happen) or relative to the TMT_TEST_DATA.
> 
> So for `$TMT_TEST_DATA/log.txt` one could use either `log: [ log.txt ]` or `log: [ $TMT_TEST_DATA/log.txt ]`, with the $TMT.. expanded of course.

Yes, that would require `check_custom_results()` to "normalize" paths, but that's doable, it's aware of `TMT_DATA_PATH` value, it can make paths relative. My comment was mostly WRT the eventual `results.yaml`, so this should work out nicely.

**Comment by comps** [comment]
> The later is per specification but I'm not sure if one can access plan name (or test name) easily.

That was my problem after you mention it being relative to execute workdir - the test would have to essentially parse out `data/[^/]+/data` from `TMT_TEST_DATA`, remove any prefix before the match, and prepend it to log name, which seems kind of unreasonable. There is no `TMT_TEST_NAME` or even `TMT_EXECUTE_WORKDIR` that could easily be prepended.

Expecting logs to be relative to `TMT_TEST_DATA` makes sense and is intuitive - where else would the test put them? It should already provide `results.yaml` there and tmt apparently guarantees that `TMT_TEST_DATA` will be transfered to the host running `tmt`, it maybe doesn't seem to make that guarantee about an execute workdir.

It's also where `tmt-report-result` copies logs and files to, so any external tools that allow the user access to logs outside of TMT will probably already have a link to it.

It also makes sense for the paths to be relative to it, the documentation of the `result:custom` format mentions simple log names, not absolute paths. Even if the thought was that the user could reference existing files on the target system to be copied out by tmt, ie. `log: /var/log/something.log`, it seems reasonable for a test author to copy these to `TMT_TEST_DATA`, again like with `tmt-report-result`.

My specific usecase is
![image](https://user-images.githubusercontent.com/1620988/221826434-0aa7f3b2-f28e-40f4-a46f-f8647dde0190.png)
where I would like to store logs inside `TMT_TEST_DATA` under ie. `package_aide_installed/oval.xml`, and the report (using only basename of this path) allows for this nice display.
```yaml
- name: /stig/package_aide_installed
  result: fail
  log:
  - package_aide_installed/oscap-vebose.log
  - package_aide_installed/oval.xml
```

**Comment by lukaszachy** [comment]
The outcome of discussion on hacking session:

Logs are expected to be stored in TMT_TEST_DATA (or its subdirs) - it is the location where `results.yaml` with custom results has to be stored.

The `log` attribute of custom results.yaml has to contain a relative path (unix path) from this data dir (e.g. from result.yaml)
