### ISSUE TITLE
tmt better Polarion testrun report support

### ISSUE THREAD

**Issue by jencce** [teemtee/tmt#1910]
1. In https://tmt.readthedocs.io/en/stable/spec/plans.html#polarion,  testrun-title field value actually match to testrun-id in Polarion. This is wrong and needs fixing badly.  

In Polarion. testrun-id is generated automatically with a time stamp format, testrun-title is message with meaningful information.

Now tmt automatically uploads a testrun with empty testrun title.

 

2. support setting Poalrion testrun plannedin field: matches to poalrion xunit importer property: polarion-custom-plannedin

 

3. support setting  Poalrion testrun assignee field: matches to poalrion xunit importer property: polarion-custom-assignee

4. support setting  Poalrion testrun subsystem field: matches to poalrion xunit importer property: polarion-custom-poolteam

**Comment by KwisatzHaderach** [comment]
Thanks for reporting this, I'm on PTO for the following week, but I'll take a look after.

The id is wrong, you are right there, I did not know about the ID being autogenerated when not provided, for me it usually autogenerated the same value I provided as title so when coding this I did not care that much which of the two is filled, but I will fix to actually be a title.

For the others, sure no problem, only thing is all these values (maybe not assignee) will need to be provided from cmdline/fmf file as there is no way I can divine a poolteam or a planned in value.
