### ISSUE TITLE
incremental import test case from polarion

### ISSUE THREAD

**Issue by jencce** [teemtee/tmt#1925]
We have multiple test cases in Polarion mapping to the same test case source code in git repo.
```
TC-001 fio nfsv4.0
TC-002 fio nfsv4.1
```
There source code is under:
```
git/stress/fio
```
When importing from polarion like 
```
tmt test import -n --no-nitrate  --polarion --polarion-case-id TC-001
```
It modifies or creates main.fmf.

Now I'm importing the second one:
```
tmt test import -n --no-nitrate  --polarion --polarion-case-id TC-002
```
It overrides the TC-001 data in main.fmf.

But I want to keep them both.

Now, it can be manually done by saving the first main.fmf and combining with the second one, like:
```
enabled: true
component:
  - kernel
 xxxx
/nfsv40:
    summary: xxx
    description: xxx
    xxx
/nfsv41:
    summary: xxx
    description: xxx
    xxxx
```

Can this be achieved internally by tmt importing test incrementally? When importing to a main.fmf which contains an existing test, organizing the new main.fmf in a hierarchy way. It would save human manual efforts significantly.

**Comment by KwisatzHaderach** [comment]
@jencce what is the expectation here? one test case in tmt linked to multiple test cases in Polarion or multiple test cases in tmt each linked to their respective Polarion test case?

what you are doing/suggesting is in fact matching the second option, however it will execute the same test multiple times (possibly parametrised depending on your code) and this is already done for nitrate and is looking doable, I don't like to create multiple cases like this if it just runs the same test n times

the first option is what I would like to do, but this is not currently supported at all and would probably include creating something like 'virtual test cases' when (just my immediate idea) it would have different summary/description/id/etc but only execute once and export into all relevant cases at once, same for report, this would be definitely quite a large effort and am not sure if other tmt stakeholders would agree with this, will bring this up on our regular meeting, looks like an interesting use case

**Comment by jencce** [comment]
> @jencce what is the expectation here? one test case in tmt linked to multiple test cases in Polarion or multiple test cases in tmt each linked to their respective Polarion test case?
> 
> what you are doing/suggesting is in fact matching the second option, however it will execute the same test multiple times (possibly parametrised depending on your code) and this is already done for nitrate and is looking doable, I don't like to create multiple cases like this if it just runs the same test n times
> 
Thanks for looking into it!

Yes I mean the second option. For some testsuite, with different parameters, it will test on completely different scenarios. It is not just simply repeating the same test. In this situation it makes sense to me that each test in tmt linked to their respective Polarion test case.

Like I said now it's achievable by manually editing main.fmf. What I'm asking here is to make this manually effort easier. It's a good to have thing from my perspective and I respect tmt team's work priority.

**Comment by KwisatzHaderach** [comment]
How are you differentiating this in tests? Are you just checking TMT_TEST_NAME?
What we have in nitrate is an 'Arguments' field that is used for pulling env variables from.

Just trying to lower the scope if the arguments wouldn't be necessary, in Polarion only field that would make sense for this IMO is 'TCMS Arguments' anyway.

**Comment by KwisatzHaderach** [comment]
@jencce any more feature requests for this regarding the test case differentiation?

I've started to implement this so a short note: there is already a finished way to create the files in the import code from nitrate times so the test cases will be created as separate files named with their Polarion work item IDs, virtually the same as the way you are describing except the name, even if I were to use Polarion title it wouldn't be good in my opinion, the title can be very long and spaces would need to be converted to other characters anyway, so using work item ID seems more usable...you can rename the files after if you are depending on that
if you have suggestions for this I'd like to hear (see) them

**Comment by jencce** [comment]
In a hierarchy fmf, the tests are named by composer, like my first comment:
/testx/nfsv4.0
/testx/nfsv4.1

Do you men there will be multiple fmf files under one testcase in your implementation?
If yes, could the name be passed via command line parameter? It would be more meaningful.

**Comment by KwisatzHaderach** [comment]
right now, I have it coded so the name is primarily the polarion case id, secondary option (used when passing `--no-link-polarion`) is taking the summary/polarion title and making it into a filename by replacing spaces with underscores

what you are suggesting would change the way it's used, you would then have to pass something like:
`--polarion-case-id 'TEST-123:nfsv4.0' --polarion-case-id 'TEST-321:nfsv4.1'`
instead of just giving the case ids like:
`--polarion-case-id TEST-123 --polarion-case-id TEST-321`
can this name value be somehow saved in polarion so it can be pulled with an argument like `--name-field tcmsnotes`?

although maybe having the name together with the id would make sense as well, what do you think @jencce?
