### ISSUE TITLE
Handle all context dimension values case insensitive

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#1953]
In order to allow easier integration with tools which use a different spelling for distro names let's ignore case of the context dimension values. For reference, here's the original motivation from @kkaarreell:

> Hello, I want to ask regarding adjust rules syntax. What we are dealing with right now is its case sensitivity. We are implementing GitHub workflow and while composes to be used by Testing Farm are named like `Fedora-XX`, the usual way of specifying `--distro` context is lowercase (at least tmt documentation is using it at various places). This is quite unfortunate because one has to convert `Fedora-XX` to `fedora-XX` in the workflow. Or, use `Fedora-XX` in tmt metadata, however it goes somehow against the "common" practice. What would be your recommendation? Should we always covert it to lowercase in our GitHub workflow when defining `--context` or something else?

The plan is to call `fmf.Tree.adjust()` with `case_sensitive=False` once the feature teemtee/fmf/issues/186 is implemented.

**Comment by thrix** [comment]
moved to 1.28, as this depends on fmf changes
