### ISSUE TITLE
Add customer link when export test case to polarion

### ISSUE THREAD

**Issue by HuijingHei** [teemtee/tmt#1956]
When export test case to polarion, by default 
- the `Automation Script` (property of the test case on polarion ) will show git repo link.
- `hyperlink` test script that has the direct link to the fmf file.

What we want to do is add customer link that is an external url, it is different from current repo link.

**Comment by KwisatzHaderach** [comment]
Decided on hacking session: Add new relation to link attribute and use this field in polarion export and tmt show. PR with specification and implementation will be created by me in the following days/weeks.

Most likely will look something like this (naming can change):
```
link:
  - test-script: https://github.com/some/repo/and/path/to/test/script
```
