### ISSUE TITLE
Guide doc mentiones pre-commit with `rev: main`

### ISSUE THREAD

**Issue by martinhoyer** [teemtee/tmt#1962]
[Checking data validity section](https://tmt.readthedocs.io/en/latest/guide.html#checking-data-validity) shows users how to add a tmt lint to their pre-commit config:  

> You can set up [pre-commit](https://pre-commit.com/#install) to do it for you. Add to your repository’s .pre-commit-config.yaml:
> ```
> repos:
> - repo: https://github.com/teemtee/tmt.git
>   rev: main
>   hooks:
>   - id: tmt-lint
>   ```

Using moving branch in pre-commit is not a good practice and will throw warnings at people.  

I would either dynamically use the latest release version in the documentation,  
or add a line to the doc to run `pre-commit autoupdate --repo https://github.com/teemtee/tmt.git` after adding the hook like it is now.

**Comment by lukaszachy** [comment]
Right. The `autoupdate`  will work better than fixing the release version each release...

**Comment by lukaszachy** [comment]
On the other hand... Let's go with latest release and figure out bumping that value with readthedocs..
