### ISSUE TITLE
Custom test results 'name' always has to start with `/`

### ISSUE THREAD

**Issue by martinhoyer** [teemtee/tmt#1963]
tmt expects users to follow the custom results.yaml [examples](https://tmt.readthedocs.io/en/latest/spec/tests.html#result) in the docs, which all include `/` in 'name' field and after switching to 'Latest' version of the docs, it does indeed include the following line:  
> each test name, referenced in the file via name key, would be prefixed by the original test name.

I would propose to either 
 - add an example of how it looks in report and explain that name needs to start with slash
 or 
 - add a check in the results parser to see if the name indeed starts with `/` and add it if not.

Example of how it currently looks with slash-less name:

```
- name: something
  result: pass
```
in results.yaml generated as part of "/tests/some_test". 
Result:
```
report
    how: display
        pass /tests/some_testsomething
```

Not having to worry about the leading slash can also mean one less step in generating the results in some tests/test frameworks.

Related to https://github.com/teemtee/tmt/issues/1671 I guess.

**Comment by happz** [comment]
Ok, so let's find out what tmt should do:

* report an error and refuse to ingest result where `name` lacks the leading slash, or
* add the leading slash if it's missing.

@psss @lukaszachy @thrix or anyone else cares to chime in? Fixing the behavior and/or docs would be trivial.

Note for me: add the missing test, finally...

**Comment by lukaszachy** [comment]
I'd prefer tmt to add warning into the note of the result and fix the custom result name.
