### ISSUE TITLE
The Review Challenge

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#1976]
As mentioned on the hacking session, during the month of April we want to improve the speed of the pull request review. The queue is quite long and it would be nice to get more contributors familiar with the code in order to make the `tmt` development more fluent. The Review Challenge has three levels:

Review at least one pull request:

* in the month —
* every week — @KwisatzHaderach, @thrix, @janhavlin, @HuijingHei 
* each day — @psss, @happz, @lukaszachy

@4N0body5, @adiosnb, @dkarpele, @frantisekz, @guy9050, @happz, @hegerj, @HuijingHei, @idorax, @jscotka, @juk, @kkaarreell, @KwisatzHaderach, @mkoncek, @pcahyna, @pfdaly, @pvalena, @RHEmployee, @Tiboris, @ukulekek, @ZelenyMartin, which level are you going to join? :)

**Comment by lukaszachy** [comment]
Each day counts with weekends and PTOs?

I'd be in for 5 per week.

**Comment by psss** [comment]
Yeap, each work day, ~5 days per week.

**Comment by psss** [comment]
### Week One

* happz ... 11
* janhavlin ... 3
* lukaszachy ... 5
* psss ... 11
* thrix ... 7

37 pull request reviews in total.

**Comment by happz** [comment]
> ### Week One
> * happz ... 11
> * janhavlin ... 3
> * lukaszachy ... 5
> * psss ... 11
> * thrix ... 7
> 
> 37 pull request reviews in total.

I wonder, how exactly are these numbers computed? I'm not really sure I reviewed 11 PRs. I did comment on a lot of them, sure, every time I see an empty comment box, I tend to comment, but marking 11 PRs as "approved" seems too much.

**Comment by psss** [comment]
I just used `did --github-pull-requests-reviewed` for this. As I mentioned on the meeting, the query is not perfect, and github mentions some irrelevant ones but I didn't want to spend much time looking into this in detail. I quickly checked my pull requests and they seemed ok. Here's the full output:

Status report for the week 14 (2023-04-03 to 2023-04-09).

* psss - Pull requests reviewed on github: 11
    * teemtee/tmt#1974 - Increase minimal severity of `ShellCheck` defects
    * teemtee/tmt#1969 - Document current workaround for running scripts
    * teemtee/tmt#1968 - Avoid warning from installing tmt as pre-commit
    * teemtee/tmt#1967 - Install `beakerlib` before running `ShellCheck`
    * teemtee/tmt#1965 - Add test checking repeated test execution results
    * teemtee/tmt#1943 - Rename `Guest.full_name` to `Guest.multihost_name`
    * teemtee/tmt#1931 - Add Kickstart to provision plugin
    * teemtee/tmt#1920 - Display guest full name in `html` plugin report
    * teemtee/tmt#1912 - Extract "run a command" functionality into a stand...
    * teemtee/tmt#1909 - Display guest full name in `display` plugin report
    * teemtee/tmt#1646 - Add the remote plan with polarion tests

* lukaszachy - Pull requests reviewed on github: 5
    * teemtee/tmt#1970 - Update the `CODEOWNERS` file with more granularity
    * teemtee/tmt#1969 - Document current workaround for running scripts
    * teemtee/tmt#1965 - Add test checking repeated test execution results
    * teemtee/tmt#1920 - Display guest full name in `html` plugin report
    * teemtee/tmt#1909 - Display guest full name in `display` plugin report

* happz - Pull requests reviewed on github: 11
    * teemtee/tmt#1971 - Freeze the `yq` version to fix `el8` installation
    * teemtee/tmt#1968 - Avoid warning from installing tmt as pre-commit
    * teemtee/tmt#1965 - Add test checking repeated test execution results
    * teemtee/tmt#1950 - Extract just tar files in dist-git-source
    * teemtee/tmt#1947 - Add test for template-based export plugin
    * teemtee/tmt#1943 - Rename `Guest.full_name` to `Guest.multihost_name`
    * teemtee/tmt#1931 - Add Kickstart to provision plugin
    * teemtee/tmt#1920 - Display guest full name in `html` plugin report
    * teemtee/tmt#1912 - Extract "run a command" functionality into a stand...
    * teemtee/tmt#1909 - Display guest full name in `display` plugin report
    * teemtee/tmt#1896 - Push using `sudo rsync` when necessary

* thrix - Pull requests reviewed on github: 7
    * teemtee/tmt#1967 - Install `beakerlib` before running `ShellCheck`
    * teemtee/tmt#1965 - Add test checking repeated test execution results
    * teemtee/tmt#1947 - Add test for template-based export plugin
    * teemtee/tmt#1943 - Rename `Guest.full_name` to `Guest.multihost_name`
    * teemtee/tmt#1920 - Display guest full name in `html` plugin report
    * teemtee/tmt#1912 - Extract "run a command" functionality into a stand...
    * teemtee/tmt#1896 - Push using `sudo rsync` when necessary

* janhavlin - Pull requests reviewed on github: 3
    * teemtee/tmt#1947 - Add test for template-based export plugin
    * teemtee/tmt#1943 - Rename `Guest.full_name` to `Guest.multihost_name`
    * teemtee/tmt#1920 - Display guest full name in `html` plugin report

**Comment by happz** [comment]
Right, I did not think about `did`. But, it does list PRs that I did not review, half of the PRs listed I *wrote*, not reviewed. #1909, #1912, #1920, …

**Comment by psss** [comment]
Hm, I reported the problem to GitHub in 2019, still without being addressed. But what we could do is to explicitly omit pull requests created by the owner:

 * https://github.com/teemtee/tmt/pulls?q=reviewed-by%3Ahappz+closed%3A2023-04-03..2023-04-10+-author%3Ahappz

@happz, does the list look ok now?

**Comment by happz** [comment]
> Hm, I reported the problem to GitHub in 2019, still without being addressed. But what we could do is to explicitly omit pull requests created by the owner:
> 
> * https://github.com/teemtee/tmt/pulls?q=reviewed-by%3Ahappz+closed%3A2023-04-03..2023-04-10+-author%3Ahappz
> 
> @happz, does the list look ok now?

Absolutely, this looks much more like what actually happened :) Thank you!

**Comment by HuijingHei** [comment]
`every week` looks good to me, thanks!

**Comment by idorax** [comment]
Hi @psss, two PRs every month look good to me as **1)** I don't have enough confidence in understanding TMT code and **2)** I don't exactly know how to write Pythonic code.

**Comment by happz** [comment]
I'm afraid the `closed` filter will mess with the statistics. This week, I reviewed 4 PRs, approving 3 of them, and proposing changes in the last one. Only one of these PRs would show in the report because only one of these PRs has been merged & closed. When merging slips into the next week, numbers won't reflect the reality of the current one, and so on. It seems to me it's not possible to get just reviewed PRs in a given date range...

**Comment by psss** [comment]
Yes, in this respect the github filter is quite limited... I was not able to find anything better.

**Comment by psss** [comment]
### Week Two

Adding stats for the second week. As the github query is not completely precise, feel free edit the comment to make it aligned with reality.

* psss: 9
    * teemtee/tmt#1995
    * teemtee/tmt#1991
    * teemtee/tmt#1985
    * teemtee/tmt#1981
    * teemtee/tmt#1978
    * teemtee/tmt#1972
    * teemtee/tmt#1961
    * teemtee/tmt#1954
    * teemtee/tmt#1891

* happz: 8
    * teemtee/tmt#1995
    * teemtee/tmt#1991
    * teemtee/tmt#1985
    * teemtee/tmt#1981
    * teemtee/tmt#1978
    * teemtee/tmt#1972
    * teemtee/tmt#1961
    * teemtee/tmt#1891

* lukaszachy: 7
    * teemtee/tmt#1993
    * teemtee/tmt#1991
    * teemtee/tmt#1982
    * psss/did#304
    * teemtee/tmt#1978
    * teemtee/tmt#1961
    * teemtee/tmt#1891

* thrix: 3
    * teemtee/tmt#1991
    * teemtee/tmt#1982
    * teemtee/tmt#1954

* janhavlin: 1
    * teemtee/tmt#1985

* KwisatzHaderach: 1
    * teemtee/tmt#1972

**Comment by psss** [comment]
### Week Three

* @lukaszachy: 6
    * teemtee/tmt#2026
    * teemtee/tmt#2015
    * teemtee/tmt#2005
    * teemtee/tmt#2001
    * teemtee/tmt#1997
    * teemtee/tmt#1870

* @happz: 5
    * teemtee/tmt#2015
    * teemtee/tmt#2005
    * teemtee/tmt#2001
    * teemtee/tmt#2000
    * teemtee/tmt#1997

* @psss: 2
    * teemtee/tmt#2001
    * teemtee/tmt#2000

* @KwisatzHaderach: 1
    * teemtee/tmt#2026

* @thrix: 1
    * teemtee/tmt#2000

* @janhavlin: 1
    * teemtee/tmt#2000

16 pull request reviews in total.

**Comment by psss** [comment]
### Week Four

* @lukaszachy: 6
    * teemtee/tmt#2026
    * teemtee/tmt#2015
    * teemtee/tmt#2005
    * teemtee/tmt#2001
    * teemtee/tmt#1997
    * teemtee/tmt#1870

* @happz: 5
    * teemtee/tmt#2015
    * teemtee/tmt#2005
    * teemtee/tmt#2001
    * teemtee/tmt#2000
    * teemtee/tmt#1997

* @psss: 2
    * teemtee/tmt#2001
    * teemtee/tmt#2000

* @KwisatzHaderach: 1
    * teemtee/tmt#2026

* @thrix: 1
    * teemtee/tmt#2000

* @janhavlin: 1
    * teemtee/tmt#2000

16 pull request reviews in total.

**Comment by psss** [comment]
And here goes a rough summary for the whole month:

* @psss: 26
* @happz: 24
* @lukaszachy: 20
* @thrix: 19
* @janhavlin: 10
* @KwisatzHaderach: 3

Thanks to all who contributed their time to reviews :) Very much appreciated!
