### ISSUE TITLE
Add basic filtering for the `html` report

### ISSUE THREAD

**Issue by comps** [teemtee/tmt#2009]
The HTML report can get pretty busy with many (especially custom) results being reported.

![image](https://user-images.githubusercontent.com/1620988/233166708-76df0e87-b261-47ce-a281-e058d7730c31.png)

Implement some basic filtering functionality, ie. just basic Javascript-based element hiding, to make the HTML output more usable, with user input at the top of the page.

* A line of checkboxes, all checked on by default, for each status (`pass`, `fail`, `warn`, `info`, `error`), where unchecking a checkbox would hide result lines with that status
* A search text field, which would filter results by a substring match on their test name - ie. immediately or a second after the user stops typing, without having to press a button
* Ideally a second text field for filtering based on Note
* Maybe also something for test Duration (not shown on the picture)? .. It might be useful to see only long-running tests.

Also consider adding a new CLI option to the HTML reporting plugin, something like `--default-status fail,error` which would start with only `fail` and `error` checkboxes enabled, others disabled. This is to avoid overloading web browsers when there are 10000s of results (just 2 of our ~20 tests generate over 7000 results).

**Comment by comps** [comment]
To avoid external dependencies (like jQuery), the text fields could be probably implemented as HTML5 `input` field events, https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event , supported in browsers for 10+ years now.

**Comment by lukaszachy** [comment]
We could also show (maybe collapsed by default) tags and summary (see https://gitlab.com/testing-farm/oculus/-/issues/16)

Now - Who wants to implement this?

**Comment by cortesana** [comment]
Hello, @lukaszachy - I want to implement this. I don't seem to be able to assign this issue to myself, however I will link the PR to it when it is ready.

**Comment by comps** [comment]
For the record, this is how I originally envisioned it,
![image](https://user-images.githubusercontent.com/1620988/235138146-166847a5-8c17-42ca-9d75-ba27c3660c7e.png)
