### ISSUE TITLE
Use consistent format for all multiword keys

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#2054]
Keys to be fixed: `serialnumber`, `starttime` and `endtime`.

So far we haven't been using camel case or multiword for any key names (except for `serialnumber` which slipped through the cracks and should be fixed IMO). Can we keep the naming consistent (e.g. always use dashes for separating multiword options and yaml keys and underscores when the key name is to be used in python code)?

_Originally posted by @psss in https://github.com/teemtee/tmt/pull/1911#discussion_r1169662418_

**Comment by lukaszachy** [comment]
Linked PR moved to 1.27 so lets do the same for the issue

**Comment by happz** [comment]
@psss things start to move. It needed some refactoring and polishing of the existing code, then a second layer changing the keys.
