### ISSUE TITLE
Simplify creating of the source tarball

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#2145]
Currently `Makefile` takes care of preparing the source tarball. Only relevant files from the git repository are selected and packaged. Several custom adjustments are done before creating the archive:

* Inject version and git hash into `tmt/__init__.py`
* Create man page from `README.rst` and `doc/header.txt`

Because of this we currently need to upload the tarball to github release attachments. It would be nice, if this manual step is removed. The most straightforward way seems to be to use the `%pypi_source` macro in spec file and upload the archive to pypi. This means that `python -m build` should be used to prepare the archive (take care of selecting the needed files and apply our custom adjustments). Here are some related links:

* https://setuptools.pypa.io/en/latest/userguide/datafiles.html
* https://github.com/packit/packit/blob/main/packit.spec#L15
* https://github.com/packit/packit/blob/main/.github/workflows/pypi-publish.yml#L20

As this will require changes to `setup.py` we could use this opportunity to get rid of it and migrate all python building configuration to `pyproject.toml`.

**Comment by psss** [comment]
There seem to be multiple options how to do the building itself:

 * https://python-poetry.org/
 * https://hatch.pypa.io/
 * https://flit.pypa.io/

From the `rpm` build perspective we just need to include an additional file in the release tarball. Packit is doing just this in their [github workflow](https://github.com/packit/packit/blob/main/.github/workflows/pypi-publish.yml#L20):

    python -m pip install build
    python -m build

@happz, @martinhoyer, @lukaszachy, @thrix, would be probably good sit down together for a few minutes and discuss what would be needed and what should be the next steps, hm?

**Comment by martinhoyer** [comment]
> ```
> python -m pip install build
> python -m build
> ```

You don't need to use build and github actions (or twine).
For example it can be as easy as
```
hatch build
hatch publish
```

**Comment by psss** [comment]
You mean running locally? We would like to connect it with the `release` trigger on github so that when a new release is published everything (almost) happens automagically.

**Comment by martinhoyer** [comment]
> You mean running locally?  

In CI. Not very sophisticated I admit :) gitlab-ci:
```
publish:
  image: python:3
  needs:
    - test
    - lint
  script:
    - pip install hatch
    - hatch build
    - hatch publish
```

**Comment by martinhoyer** [comment]
Leaving a few notes about the package managers/build-backends. ..

**Flit**
 - As described [here](https://github.com/pypa/flit/issues/613#issuecomment-1354350595), having no advantage over hatch, both of which are PyPA projects, except being simple/lighweight. 
 - Might not be as future-proof as others?
 - Supports Python 3.6, while other tools and backends are 3.7+ (probably not relevant to tmt)

**Hatch**
 - Faster cli, see [hyperfine](https://github.com/pypa/hatch/blob/hatch-v1.5.0/.github/workflows/test.yml#L76-L108) [results](https://github.com/pypa/hatch/actions/runs/5305412442/jobs/9602353179) against others.
 - Compared to Poetry and PDM does not use (custom) lockfile for dependencies.
 
Standardized "lockfile" format was rejected in [PEP-665](https://peps.python.org/pep-0665/) with more discussion [here](https://discuss.python.org/t/pep-665-take-2-a-file-format-to-list-python-dependencies-for-reproducibility-of-an-application/11736/197)
I'm a fan of this project's contribution guide doc: https://github.com/juftin/browsr/blob/main/docs/contributing.md, where the maintainer(s) are making things easy for devs with usage of hatch scripts (in pyproject.toml). But even here, they are using pip-tools to generate requirements.txt files, which does not seem..optimal. 
What I'm trying to say - before selecting build-backend, it might be worth deciding whether or not to use lockfiles.

**Poetry**
 - Popular
 - Being used in testing-farm projects
 - Does not support [PEP-621](https://peps.python.org/pep-0621/) i.e. the project metadata are in 'custom' format under `[tool.poetry]` in pyproject.toml
 
 **PDM**
 - Same feature-set as Poetry?
 - Adhering to PEP standards
 - Built with [PEP-582](https://peps.python.org/pep-0582/) in mind, which was rejected.

**setuptools**
 - Supports PEP-621 from version 61.0.0 (Apr 2022)
 - de-facto standard?
 - build-backend (needs separate tools for build and publish)

**Comment by adiosnb** [comment]
In our team, we use the [versioneer](https://pypi.org/project/versioneer/) project to inject the current version into a build. It reads version tags directly from git and concatenates `+n` for a number of commits from the last tag or '`dirty` into the version string if necessary.

**Comment by LecrisUT** [comment]
Note that in order to support F36 and rhel9, pep621 does not work. Packit chose hatchling for this reason. And since tmt uses click, the man files can be generated with click-man. Packit also moved some files to `importlib.resources`, but other than the bash-completion file, I don't see other ones that need to be installed like that.

**Comment by martinhoyer** [comment]
> Note that in order to support F36 and rhel9, pep621 does not work.

I assume you refer to rhel-9 having python3-setuptools-53.0.0-12 rpm, while PEP-621 requires >= 61.0.0?  Good point though.

hatchling, flit-core and pdm-pep517 are PEP-621-compatible backends and are in el9 EPEL.
flit-core is even in el8 epel, being compatible with Python 3.6 fwiw. 

@psss I'm not 100% clear about how the rpm packaging works here, but presume Packit stopped building for epel8, after [switching to hatchling](https://github.com/packit/packit/releases/tag/0.75.0). If you want to preserve el8 compatibility, flit might be the only choice then.

**Comment by LecrisUT** [comment]
> @psss I'm not 100% clear about how the rpm packaging works here, but presume Packit stopped building for epel8, after [switching to hatchling](https://github.com/packit/packit/releases/tag/0.75.0). If you want to preserve el8 compatibility, flit might be the only choice then.

Good point. By the time that was implemented, packit had already stopped updating rhel8  due to various incompatibilities. Last rhel8 build is [`0.59`](https://src.fedoraproject.org/rpms/packit) apparently. [flit-core](https://src.fedoraproject.org/rpms/python-flit-core) does not seem to have epel9, and I am surprised that [hatchling](https://src.fedoraproject.org/rpms/python-hatchling) still worked with version `0.25`

[Here](https://github.com/packit/packit/pull/1913#issuecomment-1499511831) is the comment on packit regarding a few bakends.

**Comment by martinhoyer** [comment]
> [Here](https://github.com/packit/packit/pull/1913#issuecomment-1499511831) is the comment on packit regarding a few bakends.

Very nice comment, +1

> If you want to preserve el8 compatibility, flit might be the only choice then.

I've played a little with el8, py36 and flit today, the wheel, sdist builds fine, but the problem with rpm building is actually pyproject-rpm-macros(or lack of compatible version). It can sort of be done with some horrible hacks, but what's the point...

So, if we want to keep building el8 rpms, we cannot get rid of setup.py.
If it would be up to me I'd drop el8 rpms and let el8 users install the package from pypi :shrug: .
Even better, let them do `dnf install python38-pip && python3.8 -m pip install tmt` :eyes: 

I'm happy to work on this if we go the pep-621-way fwiw.
