### ISSUE TITLE
Specification > Plans > discover > fmf shows unintuitive example

### ISSUE THREAD

**Issue by ZelenyMartin** [teemtee/tmt#2179]
This example in the documentation shows multiple `discover` keys in one block of code which is not even a valid YAML and could mislead tmt users. It would be better to have it rendered as 5 separated block of codes with examples.

https://github.com/teemtee/tmt/blob/a60ac6f332181cc5c07d69fc894eeb44c3ef6c6d/spec/plans/discover.fmf#L205-L234

rendered doc: https://tmt.readthedocs.io/en/stable/spec/plans.html#fmf

**Comment by idorax** [comment]
I'm working it as it seems pretty simple to fix it.
