### ISSUE TITLE
Simplify `reportportal` plugin tests using `yq`

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#2183]
I guess, here we could use `yq`, as we already do in some other tests, to more easily extract data from `yaml` files. But this is not blocking, we can simplify later.

_Originally posted by @psss in https://github.com/teemtee/tmt/pull/2088#discussion_r1246537498_

**Comment by idorax** [comment]
Hi @4N0body5, I once updated some test scripts by using `yq` in https://github.com/teemtee/tmt/pull/2001. If you don't have time to fix this issue, please assign it to me, I can help to simplify the tests. Else I'm glad to help to review your PR :-)

**Comment by 4N0body5** [comment]
Thank you @idorax .. Already started on [reportportalAPI_test](https://github.com/teemtee/tmt/blob/reportportalAPI_test/tests/report/reportportal/test.sh) branch, only struggling there with `\` symbol, so I'll be happy for any tips.
I'll probably create a PR, so you feel free to look at it and share your ideas.
