### ISSUE TITLE
`dnf5` detection on rawhide

### ISSUE THREAD

**Issue by LecrisUT** [teemtee/tmt#2205]
Is the `dnf5` detection correct here?
https://github.com/teemtee/tmt/blob/72a7a5305cfc908f6810ae2bc97530b031bcac1a/tmt/steps/provision/__init__.py#L290-L291

On rawhide dnf5 executable got renamed to `dnf`, so would it be detected properly there? I am concerned if there are further tests that eliminate `dnf` based on assumptions that it is `dnf4`.

This is regarding some testing-farm failures on rawhide builds where the used has a `prepare.install.package` step:
https://matrix.to/#/!cfWVeczGVJbiKSlrwi:fedoraproject.org/$g3lhy9JK78YoD_eljF86X2cqPFeYaWytH7XC0vo3RWc?via=libera.chat&via=fedora.im&via=matrix.org

**Comment by lukaszachy** [comment]
@LecrisUT Where was it renamed?  I've checked today's nightly build with dnf5-5.0.15-4.fc39 and it provides both `/usr/bin/dnf5` as well as `/usr/bin/dnf`, so the detection should work properly.

**Comment by LecrisUT** [comment]
Sorry, you're right both are provided. In the linked chat they have confirmed that Testing-Farm is using `tmt 1.24.0`. Oh, and I see that in `1.24.1` there is a different logic of checking the `dnf` version:
https://github.com/teemtee/tmt/blob/e0afc4c18da0fd50f847a04db94000f5f822eca5/tmt/steps/provision/__init__.py#L277-L278

**Comment by lukaszachy** [comment]
Thank you for the confirmation.
We hotfixed 1.24.1  but with rpm only patch to work with new dnf. Pypi/upstream has the fix only with 1.25.0 .
