### ISSUE TITLE
rsync command is failing on execute task#2 in case task#1 did not clean mount files on single node test

### ISSUE THREAD

**Issue by Yarboa** [teemtee/tmt#2207]
running the following command results rsync failure

tmt  --on-plan-error continue --environment RELEASE_NAME=ER3  execute provision --how connect -u root -p password -g host -P 22 discover  plans --name plans/sst_kernel_ft/memory

execute task #2: upstream_er on default-0                                                                                                                                      

result the following error
 Cause number 1:                            
                                               
        Command 'rsync -s -R -r -z --links --safe-links --delete -e 'sshpass -p password ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oServerAliveInterval=60 -oServerAliveCountMax=5 -oIdentitiesOnly=yes -p22 -oPasswordAuthentication=yes -S/tmp/tmp2oqvtk9r' /var/tmp/tmt/run-016/plans/sst_kernel_ft/memory/plan root@testhost:/' returned 23. 
        
running the following command in DUT

```
mount | grep /var/tmp/tmt
bz843035_1 on /var/tmp/tmt/run-016/plans/sst_kernel_ft/memory/plan/discover/internal_er/tests/general/memory/regression/reg-suit/tmp.lP2qqXrawp/bz843035 type fuse.bz843035_1 (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
```

shows there is mounted directory.

Expected result:
run the above command and release the mount before calling rsync

**Comment by lukaszachy** [comment]
I'm afraid this is outside of tmt responsibility. 
There are many possibility how rsync or ssh can get broken and IMO tmt cannot be expected to repair guests.

**Comment by psss** [comment]
I would agree with @lukaszachy here. I'd say here it should be responsiblity of the test to clean up the mount after it's done or create the mount outside of the tmt run workdir so that `rsync` does not fail. Closing. Feel free to reopen of you disagree.
