### ISSUE TITLE
Make ``tmt init`` add .fmf directory into git index

### ISSUE THREAD

**Issue by pemensik** [teemtee/tmt#2219]
It happened multiple times to me, that I forgot to add ``.fmf/version`` file into git repository, after I did ``tmt init`` in my dist-git repository clone.

Please consider automatically adding it into git, if the current directory is part of git repository. It would be most of time true for me. Just like ``fedpkg new-sources``, it should try to help me not to forget adding this with a test.

It might be configurable per user/system. I would want it for every my repository. I expect I would not be alone. I can always do ``git  reset `` in unlikely cases, when this is not wanted.

**Comment by psss** [comment]
Yeah, understood. Sounds like a reasonable enhancement. Let's make it configurable. Not sure about the default. Probably not modifying git index would be a bit safer. But I can also see that many people run into forgetting about the file completely. Let's gather more thoughts and try in `1.27`.

**Comment by lukaszachy** [comment]
tmt init is now more cautious and will warn if fmf root already exists in current work dir so I'd say that if one successfully runs 'tmt init' in git repo they really want to add it to the git. IMO we could default to 'add to the git' but it should be visible from the tmt init output.

**Comment by therazix** [comment]
I'm currently working on it and I have a question. How exactly it should be configurable? Would a simple environment variable be sufficient?

**Comment by psss** [comment]
> tmt init is now more cautious and will warn if fmf root already exists in current work dir so I'd say that if one successfully runs 'tmt init' in git repo they really want to add it to the git. IMO we could default to 'add to the git' but it should be visible from the tmt init output.

This is a fair point. Makes sense. Let's default to this behavior and add configurability if/when there's a real need for it, hm?

**Comment by psss** [comment]
> I'm currently working on it and I have a question. How exactly it should be configurable? Would a simple environment variable be sufficient?

After @lukaszachy's comment I'd even say let's enable it without config. But @therazix, if you feel it would be better, I'd say an environment variable would be just enough.
