### ISSUE TITLE
The `versionadded` directive is causing problems

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#2233]
In addition to rst2man even pypi upload has failed on this directive, present in README.rst.

Seems that just sphinx is able to render it.

**Comment by lukaszachy** [comment]
See https://github.com/teemtee/tmt/actions/runs/5718758003/job/15495231169

**Comment by psss** [comment]
Summary from the hacking session:

 * Keep the `README` as a place for a short introduction and basic links ... used as github intro, pypi decription
 * Move the details to a separate `overview` page ... to be the source for the man page and online overview

**Comment by thrix** [comment]
moved to 1.28, there is no assignee, but the next steps should be clear
