### ISSUE TITLE
Migrate from pkg_resources to importlib.resources

### ISSUE THREAD

**Issue by martinhoyer** [teemtee/tmt#2259]
This is needed for Python 3.12 (see failing rawhide jobs)
`importlib.resources.files` have been introduced in 3.9, so it shouldn't be a problem now tmt is >=3.9 only.

Example:
from:
```
SCRIPTS_SRC_DIR = Path(pkg_resources.resource_filename(
    'tmt', 'steps/execute/scripts'))
```
to:
```
SCRIPTS_SRC_DIR = importlib.resources.files('tmt') / 'steps/execute/scripts'
```
Instead of `Path` object, you'll get `Traversable` object. (pathlib.Path is instance of Traversable)

This causes a small issue with type checking. It can be solved by using importlib_resources everywhere and use `from importlib_resources.abc import Traversal` when type checking, however there is no importlib-resources package in EPEL9.
@happz What do you think? 

When playing with it I noticed other related things that could be improved, like replacing some `os` usages with `pathlib`:
```
    schema_dirpath = Path(pkg_resources.resource_filename('tmt', 'schemas'))

    try:
        for dirpath, _, filenames in os.walk(
                schema_dirpath, followlinks=True):
            for filename in filenames:
                filepath = Path(dirpath) / filename
                ```
to:
```
    schema_dirpath = importlib.resources.files('tmt') / 'schemas'

    try:
        for filepath in schema_dirpath.glob('**/*ml'):
```

I'm happy to work on this if needed.

Also happy to work on converting other usage of `os` to pathlib ;)

**Comment by happz** [comment]
Would it make sense to have some kind of compat wrapper for this functionality? One other thing is, we do have our own subclass of `pathlib.Path`, `tmt.utils.Path`, and it would be nice to stick to it anywhere `Path` pops up. It might also help with versions, IIUIC, we can't use `importlib.resources` outside of Fedora, but we should really use it because of Fedora. Something like this, with proper check, when `importlib.resources` is not available, fall back to the old ways?

```python
def resource_path(name: str) -> tmt.utils.Path:
  if sys.version > python3.9:
    return tmt.utils.Path(importlib.resources.files('tmt')) / 'steps/execute/scripts'

  return tmt.utils.Path(pkg_resources.resource_filename('tmt')

SCRIPTS_SRC_DIR = resource_path('tmt') / 'steps/execute/scripts'
```

I'd prefer to stick to one `Path` class in tmt code, one possibility would be we no longer need a custom class. The the concern about consistency would be no longer valid, but the availability of `importlibe.resources` still applies, right?

> Also happy to work on converting other usage of `os` to pathlib ;)

Yeah, that would be nice. There are some in library code, although I think there were some `os.path` functions that were pretty useful, `splitext` maybe? I recall seeing it and thinking, well, changing it to `Path` would make the code worse, as the place had no effect on the rest of tmt or something like that. I'll try to find it.

**Comment by happz** [comment]
Got it:

```python
    # Story.create:
    @staticmethod
    def create(
            *,
            name: str,
            template: str,
            path: Path,
            force: bool = False,
            dry: Optional[bool] = None,
            logger: tmt.log.Logger) -> None:
        """ Create a new story """
        if dry is None:
            dry = Story._opt('dry')

        # Prepare paths
        (directory, story) = os.path.split(name)
        directory_path = path / directory.lstrip('/')
        has_fmf_ext = os.path.splitext(story)[1] == '.fmf'
        story_path = directory_path / (story + ('' if has_fmf_ext else '.fmf'))
```

I was thinking, the `name` is not a path, not yet. It will serve as a basis for a path, `directory_path = path / directory.lstrip('/')`, but replacing `os.path.split` didn't feel right.

**Comment by martinhoyer** [comment]
To clarify,` importlib.resources.files` is in py39 and works in el9 without additional dependencies.
Don't think the fallback to pkg_resources is needed.

Sidenote: isn't `platform.python_version()` the "correct" way to get version (compared to `sys`)?

The custom Path - I haven't looked too closely into it, but with py39+ it shouldn't be needed?

**Comment by happz** [comment]
> To clarify,` importlib.resources.files` is in py39 and works in el9 without additional dependencies. Don't think the fallback to pkg_resources is needed.

Aha, then I misunderstood. Very well then.

> Sidenote: isn't `platform.python_version()` the "correct" way to get version (compared to `sys`)?

Probably. We were using `sys` as recommended by mypy, but we were using it for version-based imports of types. Not necessarily the best way elsewhere.

> The custom Path - I haven't looked too closely into it, but with py39+ it shouldn't be needed?

I'm afraid this is not governed by Python version, but the functionality. See `tmt.utils.Path.relative_to()` - `pathlib.Path` raises `ValueError` for some inputs, namely parallel trees: `Path('/etc').relative_to('/var')` will fail with `pathlib.Path`, but works with `os.path.relpath` and it's what `tmt.utils.Path.relative_to` implements. If we can fix places where this is used to not depend on the `relpath`-like behavior, we could get rid of our `Path`.

On the other hand, I quite like it :) It's a clear, compatible replacement, it has `unrooted()` method often used for converting test names to paths, and I don't have to think deeper about various paths tmt manages. I guess there will be some `relative_to()` call with a workdir and wortree or something like that - to sort that out, one might have to learn way more about how all those paths are related, and I'm still lacking in this area.
