### ISSUE TITLE
Expose tmt version as an environment variable for tests to inspect

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#2267]

**Comment by idorax** [comment]
Hi @happz, I'm very interested in this issue because when I try to use `tmt --verison` in my development environment, it always fails.  e.g.
```bash
(tmt) huanli@FOO:dev$ type tmt
tmt is hashed (/home/huanli/.virtualenvs/tmt/bin/tmt)
(tmt) huanli@FOO$ tmt --version
tmt version: running from the source
```

To expose tmt version as an environment variable, what about `TMT_VERSION`?

**Comment by idorax** [comment]
After looking into the `tmt.__version__`, it is set via `Makefile`.

> (tmt) huanli@FOO:dev$ tmt --version
> tmt version: running from the source

```bash
(tmt) huanli@FOO:dev$ find . -name "*.spec" | xargs grep "Version"
Version: 1.25.0
(tmt) huanli@FOO:dev$ find tmt -name "*.py" | xargs grep "running from the source"
tmt/__init__.py:__version__ = 'running from the source'
(tmt) huanli@FOO:dev$ find . -name "Makefile" | xargs grep "running from the source"
./Makefile:REPLACE_VERSION = "s/running from the source/$(VERSION) ($(COMMIT))/"
(tmt) huanli@FOO:dev$ grep "REPLACE_VERSION" Makefile
REPLACE_VERSION = "s/running from the source/$(VERSION) ($(COMMIT))/"
	sed -i $(REPLACE_VERSION) $(TMP)/$(PACKAGE)/tmt/__init__.py
	sed -i $(REPLACE_VERSION) tmt/__init__.py
```

@happz, if we use `TMT_VERSION` to expose the tmt version, we need to have

```python
TMT_VERSION = tmt.__version__
```

in `execute` step, right?

**Comment by happz** [comment]
Yeah, that was my initial idea. There's a method somewhere in the internal execute plugin which is responsible for preparing, I'd add this one there as well.

**Comment by idorax** [comment]
> Yeah, that was my initial idea. There's a method somewhere in the internal execute plugin which is responsible for preparing, I'd add this one there as well.

@happz, I filed a PR to add
```python
combined["TMT_VERSION"] = tmt.__version__
```

to file [tmt/base.py](https://github.com/teemtee/tmt/blob/main/tmt/base.py#L1580). Please help to review, if it's not the correct location to expose `TMT_VERSION`, please let me know and I'll update it accordingly, thanks!

**Comment by schrht** [comment]
@idorax Hi Vector, it is nice to have this feature available in TMT, and we do need it as early as possible. Thank you for helping this. Please let us know when we can have the feature in the latest version of TMT. Have a great day!

**Comment by happz** [comment]
@schrht The patch can be merged within a week, at max, which would make it available from the `main` branch if you use tmt from this repo. Given the monthly cadence of tmt releases, 1.27 with the patch should get out in early September, making it available with rpm-packages tmt installations. Then a week or two for 1.27 to appear in Testing Farm.

**Comment by schrht** [comment]
@happz Thank you for the information!!
