### ISSUE TITLE
Prepare step variables are not available in execute step

### ISSUE THREAD

**Issue by juk** [teemtee/tmt#2276]
In some use cases, QE needs to export env variables in prepare step so these variables are available during the execution step.
The below example was used to confirm that exported variables were not available for test script during execution:

Test plan
```
$ cat rpm-verify.fmf
summary: RPM verify on a kernel package
prepare:
    how: shell
    script: source ./security/rpm-verify/plans/setup_env.sh
discover:
    how: fmf
    test:
        - /security/rpm-verify/tests/rpm-verify
execute:
    how: tmt
environment-file:
        - ./security/rpm-verify/plans/tmt.env
```
Preparing an env
```
$ cat setup_env.sh
#!/bin/bash

export MYVAR1="my_env_var1"
export MYVAR2="my_env_var2"
echo "MYVAR1=$MYVAR1"
echo "MYVAR2=$MYVAR2"
```

Test code
```
    rlPhaseStartSetup
        rlLog "MYVAR1: $MYVAR1"
        rlLog "MYVAR2: $MYVAR2"
        rlShowRunningKernel
        rlRun "rpm -qa kernel*"
    rlPhaseEnd
```

Test output
```
14:32:40                 out: ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
14:32:40                 out: ::   Setup
14:32:40                 out: ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
14:32:40                 out: 
14:32:40                 out: :: [ 14:32:40 ] :: [   LOG    ] :: MYVAR1: 
14:32:40                 out: :: [ 14:32:40 ] :: [   LOG    ] :: MYVAR2: 
14:32:40                 out: :: [ 14:32:40 ] :: [   LOG    ] :: Kernel version: 6.5.0-0.rc6.43.fc39.x86_64
14:32:41                 out: :: [ 14:32:40 ] :: [  BEGIN   ] :: Running 'rpm -qa kernel*'
```

**Comment by happz** [comment]
Interesting. It's definitely possible, `execute` is sort of a privileged kid, and I'd say yes, if there are envvars on the plan level, `prepare` (and `finish`) should have access to them.

**Comment by psss** [comment]
Just to clarify the original use case: It's about the backward-compatible variables `$SERVERS` and `$CLIENTS` used for multihost testing. One of the possible workarounds is this:

```shell
source "$TMT_TOPOLOGY_BASH"

SERVERS="${TMT_ROLES[server]}"
CLIENTS="${TMT_ROLES[client]}"

echo SERVERS="$SERVERS" >> $TMT_TOPOLOGY_BASH
echo CLIENTS="$CLIENTS" >> $TMT_TOPOLOGY_BASH
```

Would it make sense to introduce something like `$TMT_PLAN_ENVIRONMENT_FILE` variable which would point to a file which would be sourced before running the `execute` step?

**Comment by happz** [comment]
IIUIC, the original issue is mostly about the "sharing" of variables between the `prepare` and `execute` steps. `TMT_TOPOLOGY_*` are definitely not shared, probably never will, but, is there a path, on the guest, which `prepare`, `execute` and `finish` could use to exchange files?

**Comment by psss** [comment]
> but, is there a path, on the guest, which `prepare`, `execute` and `finish` could use to exchange files?

Yes, I guess the `$TMT_PLAN_DATA` variable could be used as a workaround for this. Just store arbitrary content there and source it in the test script.

In order to prevent too many changes in existing tests, the generic approach using the `$TMT_PLAN_ENVIRONMENT_FILE` variable could support sourcing the file with variables and provide the variables to the test automatically so that individual tests do not have to source it. @juk, what do you think about this approach?

**Comment by psss** [comment]
Not clear agreement on the proposed solution, waiting for feedback in https://issues.redhat.com/browse/KQE-93, moving to `1.29`.
