### ISSUE TITLE
summary: 0 tasks completed?

### ISSUE THREAD

**Issue by guoguojenna** [teemtee/tmt#2302]
Hello, 

My tests always finished with this summary "summary: **_0_** tasks completed".  It's always 0 tasks. I am wondering what tasks mean here? Which kind of tests can finish with non-zero tasks?

Thanks,
Zhaojuan

**Comment by lukaszachy** [comment]
Finish allows 'ansible' and 'shell' methods. Task means any action these methods do.
```
finish:
  how: shell
  script: echo closing
```
does `summary: 1 task completed`.

In the 'prepare' it is called `preparation applied`. If you have some ideas about how to call it for 'finish' step...

**Comment by guoguojenna** [comment]
> finish:
>   how: shell
>   script: echo closing

Clear now, thank you!
