### ISSUE TITLE
Add `device` key into the `hardware` specification

### ISSUE THREAD

**Issue by juk** [teemtee/tmt#2337]
As proposed in  [hw spec: add a new key: device #1759 ](https://github.com/teemtee/tmt/pull/1759/files) the 'device' would have a few properties:
`driver`: the kernel module name
`device-id`: the device identifier
`vendor-id`: vendor's unique identifier
`description`: string with a device name

```
    device:
        description: C51 [GeForce 6150 LE]
        device-id: 0241
        driver: nouveau
        vendor-id: 10de
```

@lkotek raised a few interesting points in the PR that would be great to discuss and adjust PR accordingly

```
Just an idea that crossed my mind that we can maybe take into consideration, because this PR will add new very generic item, but there are already some existing hardware specifications like cpu, disk, network etc.

    Should we consider these just like some special cases of device?
    Should the disk (for example) be just a wrapper (or syntax sugar) for device in the future?
    Should the network (for example) inherit its keys from device and add some specific ones for network?
    Or should we keep and treat existing hardware "devices" and new device from this PR completely separately?
```

**Comment by juk** [comment]
@psss @happz @thrix - any thoughts? I'd like to move forward on adding the `device` key

**Comment by happz** [comment]
> Just an idea that crossed my mind that we can maybe take into consideration, because this PR will add new very generic item, but there are already some existing hardware specifications like cpu, disk, network etc.
>
>     Should we consider these just like some special cases of device?

I'd say yes. A shortcut so to say. I think of these as less powerful but more accessible & natural ways of requesting the most common features.

>    Should the disk (for example) be just a wrapper (or syntax sugar) for device in the future?

Syntax sugar is a fitting description.

>    Should the network (for example) inherit its keys from device and add some specific ones for network?

Probably not in this direction, but I'd expect `device` of "NIC"-like types to include keys `network` entries support.

>    Or should we keep and treat existing hardware "devices" and new device from this PR completely separately?

Probably not completely, I'd treat them as two slightly different ways of describing the same device. I would prefer the `network` and `disk` to be the primary fields for most of the users, while it's absolutely true for some, these would not be powerful enough - I don't see us adding a dedicated `rtc` key, for example, then `device` would be used, while when I need just a slightly bigger disk, `disk[0].size` would be much easier to grasp for me than `device`. We need to keep in mind there are the complete Shakespeare works and also the abridged version that fits into 120 minutes :)

WRT the `device` proposal, we should resolve a field-level conflict between `network`, `system`, and `device`. They all deal with "vendor", "device": there's `vendor-name` and `device-name` in `network`, and `vendor` and `model` in `system`. `device` would be adding `vendor-id` and `device-id`. We really should pick one naming scheme, even if it means fixing the current specification should the `vendor-id` win.

There's a similar situation in CPU lands, we have `model` vs `model-name` and `family` vs `family-name`, i.e. the machine-readable, ID-like field is one unsuffixed, and the human-readable, string representation gets `-name` suffix. For `device`, `network` and `system`, this leads me to `vendor` + `vendor-name`, `device` (PCI ID) & `device-name` (device description aka name, "C51 [GeForce 6150 LE]" from the proposal), `model` & `model-name`.

This would spell a fix for `system`, to switch `vendor` to `vendor-name` and `model` to `model-name` in the example given in tmt specs, plus this for the `device`:

```yaml
driver: the kernel module name
device: the device identifier
device-name: device name as a string
vendor: vendor's unique identifier
vendor-name: vendor name as a string

device:
    device-name: C51 [GeForce 6150 LE]
    device: 0241
    driver: nouveau
    vendor: 10de
```

**Comment by thrix** [comment]
@lkotek @juk any comments on above?

**Comment by lkotek** [comment]
> @lkotek @juk any comments on above?

Not really, I think the approach, @happz described in his comment, is very reasonable.

**Comment by juk** [comment]
@happz @thrix @lkotek will update https://github.com/teemtee/tmt/pull/1759/files to reflect the schema proposed in https://github.com/teemtee/tmt/issues/2337#issuecomment-1727321565

Thank you!

**Comment by happz** [comment]
Here's the fix for `system`, plus a bit of docs: https://github.com/teemtee/tmt/pull/2431
