### ISSUE TITLE
Provisioning should support Beaker pool enforcement/exclusion

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#2346]
In Beaker jobs, this is possible to request/exclude a specific **Beaker** pool (not to be confused with **Artemis** pools):

```
system-pool: !virtkvm-gating
system-pool: virtkvm-gating
```

First, it's a feature sought by current Beaker users, and it probably shouldn't be hard to extend the Beaker plugin/mrack to support this.

Second, I'm not sure how to support this with Artemis, and to what extent this should be decoupled from `how: beaker`. As Artemis can and does wrap Beaker service too, it can certainly accept constraints of this kind and propagate them to Beaker behind the curtain. Feels like something generic enough for `hardware`, but it's not actual HW requirements, more like an organizational aspect... Anyway, adding HW labels, open for discussion.

**Comment by psss** [comment]
@skycastlelily, would you be possibly interested in this? We consider this for 1.38 or 1.39.

**Comment by skycastlelily** [comment]
Sure,will look into and work on it tomorrow:)

**Comment by psss** [comment]
That's great, proposing for `1.38` then. Thanks!

**Comment by skycastlelily** [comment]
Here are the merge requests :)
https://github.com/teemtee/tmt/pull/3271 
https://gitlab.com/testing-farm/artemis/-/merge_requests/1283

**Comment by thrix** [comment]
Seems nothing else to do here on tmt side, closing.
