### ISSUE TITLE
Provide unit formatting that shows unit symbols instead of their full names

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#2410]
In theory, it's easy, there's support for formatting in Pint: `f"{foo:~D}"` - `~` makes Pint emit a symbol, i.e. `MB` instead of `megabyte`.

Unfortunately, this support comes with Pint 0.18, and the best one we get from RPMs is 0.17.1.

**Comment by psss** [comment]
> Unfortunately, this support comes with Pint 0.18, and the best one we get from RPMs is 0.17.1.

@happz, just checked that for `el9` there's still older version `python3-pint-0.16.1-3.el9.noarch`. Is that ok? I see that the latest [update](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-3bf8aa89cc) was created by @lukaszachy, so, perhaps, he could package more recent one as well?

**Comment by happz** [comment]
> > Unfortunately, this support comes with Pint 0.18, and the best one we get from RPMs is 0.17.1.
> 
> @happz, just checked that for `el9` there's still older version `python3-pint-0.16.1-3.el9.noarch`. Is that ok? I see that the latest [update](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-3bf8aa89cc) was created by @lukaszachy, so, perhaps, he could package more recent one as well?

Today I realized support for `~D` comes with 0.18, but a mere `~` should be already supported. And that's pretty much all we need so far, we might try to improve it later, but so far it looks much better than full names.

**Comment by happz** [comment]
WRT packaging - I wouldn't mind, but let me first try covering `tmt.hardware` with pyright, and test it with both newer and older Pint versions, to be sure @lukaszachy wouldn't package something that would be impossible or impractical to use.

**Comment by psss** [comment]
> Today I realized support for `~D` comes with 0.18, but a mere `~` should be already supported.

I see. Nice!

> WRT packaging - I wouldn't mind, but let me first try covering `tmt.hardware` with pyright, and test it with both newer and older Pint versions, to be sure @lukaszachy wouldn't package something that would be impossible or impractical to use.

Yeah, makes sense.
