### ISSUE TITLE
Whiteboard cannot be set by user while provisioning with beaker

### ISSUE THREAD

**Issue by guoguojenna** [teemtee/tmt#2447]
Currently the value of Whiteboard is string like ' tmt-008-jpqJPFTI '. Can users set it to a different one?
https://beaker.engineering.redhat.com/jobs/8506748

Thank you,
Zhaojuan

**Comment by happz** [comment]
I'm afraid the answer is "no", users cannot set Beaker job whiteboard.

**Comment by guoguojenna** [comment]
> I'm afraid the answer is "no", users cannot set Beaker job whiteboard.

Ok. I think it's a useful feature. Hope it can be added someday.

**Comment by idorax** [comment]
The whiteboard of beaker job is updated by [tmt/steps/provision/mrack.py#L336](https://github.com/teemtee/tmt/blob/main/tmt/steps/provision/mrack.py#L336) , e.g.
```python
   330	        def create_host_requirement(self, host: Dict[str, Any]) -> Dict[str, Any]:
   331	            """ Create single input for Beaker provisioner """
   332	            hardware = cast(Optional[tmt.hardware.Hardware], host.get('hardware'))
   333	            if hardware and hardware.constraint:
   334	                host.update({"beaker": self._translate_tmt_hw(hardware)})
   335	            req: Dict[str, Any] = super().create_host_requirement(host)
   336	            req.update({"whiteboard": host.get("tmt_name", req.get("whiteboard"))})
   337	            return req
```

Let's try to add property `whiteboard` to `BeakerGuestData` and try to get the `whiteboard` from L336.
