### ISSUE TITLE
Discrepancy with `arch` in hardware requirements and plugin options

### ISSUE THREAD

**Issue by thrix** [teemtee/tmt#2451]
Currently, `arch` is special, it is part of the `plugin` options but it also part of the `hardware` field. 

This is currently confusing the users, as they insert `arch` into hardware requirements and TF breaks on it:

See for example this run from RH ranch:
http://artifacts.osci.redhat.com/testing-farm/124143cd-7bb9-4dc8-afa6-9486da98c485/

The current documentation:
https://tmt.readthedocs.io/en/stable/spec/plans.html (note the `arch` field in the provision plugin options)
https://tmt.readthedocs.io/en/stable/spec/hardware.html#arch (note the `arch` field under `hardware`)

As discussed with @happz we should resolve this discrepancy. We are thinking, that user wise, it would make most sense to keep the `arch` field only in `hardware`, what makes most sense for user interface, and leave the special handling of `arch` on the provision plugins.

**Comment by psss** [comment]
Summary from the hacking session:

* update the documentation to match the reality (arch currently not supported under hardware)
* long term we would like to have arch under the `hardware` key to keep consistency

**Comment by psss** [comment]
Covered by #2552.
