### ISSUE TITLE
Trees are no longer pickleable

### ISSUE THREAD

**Issue by t184256** [teemtee/tmt#2503]
TMT trees are no longer pickleable.

https://github.com/teemtee/tmt/blame/445479d64acfc70b0ef7e100a09c88233c9ec52f/tmt/log.py#L93

I'm caching a large amount of adjusted trees, now I have to remove the `_logger` from them to cache them.

**Comment by t184256** [comment]
Both of the wrappers don't need to be local functions, one could be an identity transform, and the other could be a `tmt.utils.remove_color` directly, w/o wrapping.

**Comment by happz** [comment]
Interesting use case. I agree, the code can be simpler, and it might be a trivial patch, let's see whether it can be fixed quickly enough for 1.30.
