### ISSUE TITLE
tmt reportportal plugin should be using API v2

### ISSUE THREAD

**Issue by kkaarreell** [teemtee/tmt#2505]
The plugin is currently using API v1. It would be better to swtich to v2 though.
I tried to change the value in tmt code and the launch import (including adding attributes based on define context) worked at the first sight. One difference I have noticed is that for `v1` tmt prints URL of the imported launch while for `v2` nothing is printed.

There may be also other differences which I have not spotted.

**Comment by kkaarreell** [comment]
@4N0body5 FYI

**Comment by 4N0body5** [comment]
Resolved by #2305
