### ISSUE TITLE
rhts-report-result not backwards compatible

### ISSUE THREAD

**Issue by sbertramrh** [teemtee/tmt#2592]
The tmt implementation of this function causes the following error when a fourth value, METRIC, is not passed.

`out: /usr/local/bin/rhts-report-result: line 65: $4: unbound variable`

The 4th parameter should be optional. By requiring the 4th, it is not backwards compatible. 
```
if [[ "$0" == *"rhts-report-result"* ]]; then
    TESTNAME=$1
    TESTRESULT=$2
    outputFile=$3
    METRIC=$4
    check_report_file
fi

```

Seen in version 1.29.0

**Comment by BeeGrech** [comment]
https://restraint.readthedocs.io/en/latest/restraintd.html?highlight=rhts-report-result#rstrnt-report-result

> Report Pass/Fail/Warn, optional score
