### ISSUE TITLE
Accessing `context` within the test

### ISSUE THREAD

**Issue by LecrisUT** [teemtee/tmt#2613]
An example use-case, I want `rpminspect` to skip `metadata` when `initiator == packit` because the copr metadata always fails. This would work with `adjust`, but in more complicated cases, I would like a more general approach that I can use at runtime.

- I have tried using the `$@`, but this i not expanded within `environment`:
  ```yaml
  environment:
    CONTEXT_INITIATOR: $@{initiator}
  ```
- I have tried looking for any other source where `context` are stored at runtime, but there doesn't seem to be any

Some potential solutions:
- Expand all `environment` nodes. This would be tricky if there is recursive dependence
- Add `context` to `TMT_TEST_METADATA`
- Export `TMT_CONTEXT_*` variables by default

**Comment by lukaszachy** [comment]
The decision is to store used `context` into  `TMT_TEST_METADATA` file.

**Comment by LecrisUT** [comment]
Only the `TMT_TEST_METADATA` or deeper down in `Core._update_metadata`?

**Comment by happz** [comment]
I'd add it somewhere here, combining `test._metadata` with context without changing what's in `test._metadata`. That should preserve test metadata for whoever would be interested in using them, not spoiling them with context that would added just to expose it to the test.
