### ISSUE TITLE
Find a better name for tmt `try`

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#2658]
All commands can be shortened to a single character but 'tests' and 'try'.

```
$ tmt t ls
Usage: tmt [OPTIONS] COMMAND [ARGS]...
Try 'tmt --help' for help.

Error: Did you mean tests or try?
```

Am I the only one who curses above error message every week?

**Comment by hegerj** [comment]
Not the only one. `tests` is by far the most used command for me and I use(d) `t` almost exclusively (including aliases and bash history). I suggest changing `try` to `experiment` or `evaluate` as 'e' seems to be free.

**Comment by psss** [comment]
Hmmm, I understand the one-letter use case, it's a pity there's the `t` letter collision. But the three-letter `try` seems so nicely fitting for the action of quickly trying something, try some test, try some distro... and can be written fast. I don't like `tmt experiment` or `tmt evaluate`, they seem to me just too long and not fitting the action. The one-letter abbreviation `e` does not help me either.

Also, from the long-term point of view, I'm afraid it's just not possible to say every `tmt` command will start with a different letter. We have to be prepared that there would be new commands and that the abbreviations will overlap.

**Comment by lukaszachy** [comment]
No point crying over spilled milk, closing.
