### ISSUE TITLE
New environment variable for link to detailed artifacts

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#2660]
When tests are executed in the Testing Farm it would be nice if `report` plugins would be provided a link to the job artifacts so that the generated report includes the link and user can easily get to the detailed logs. Here are some variable names brainstormed on the stakeholder session:

    TMT_REPORT_ARTIFACTS_URL
    TMT_REPORT_ARTIFACTS_URL_ROOT
    TMT_REPORT_COMMON_ARTIFACTS_URL

Testing Farm would provide this variable to `tmt run` so that the report plugin could pick it. Variable would be provided in the process environment, not as the `tmt run --environment`, for example like this:

    TMT_REPORT_ARTIFACTS_URL=https://artifacts... tmt run ...

In addition to the main link, it would could also useful to provide a direct link to test data directory from each test result. But that can be left for future improvements.

**Comment by thrix** [comment]
1. what is the difference between `TMT_REPORT_ARTIFACTS_URL` and `TMT_REPORT_COMMON_ARTIFACTS_URL` ?
2. we would provide this environment variable to the `tmt` process (not to the tmt run command), maybe make it more clear, i.e. `VAR1=VAL tmt run ...` vs `tmt run -e VAR1=VAL1`.

**Comment by psss** [comment]
> 1. what is the difference between `TMT_REPORT_ARTIFACTS_URL` and `TMT_REPORT_COMMON_ARTIFACTS_URL` ?

I was just brainstorming possible names. Here the `COMMON` part was proposed just to prevent possible collision with other future plugin names and keep consistent naming `TMT_<step>_<plugin>_<variable>`

> 2. we would provide this environment variable to the `tmt` process (not to the tmt run command), maybe make it more clear, i.e. `VAR1=VAL tmt run ...` vs `tmt run -e VAR1=VAL1`.

Yeah, this is consistent with how other plugin environment variables are provided. Will update the issue description.
