### ISSUE TITLE
rpminspect is failing in case of added files

### ISSUE THREAD

**Issue by thrix** [teemtee/tmt#2680]
I do believe this is quite expected for the updates:

https://artifacts.dev.testing-farm.io/a3b3ba24-4b1d-4e28-b043-ef62abb6128a/

Maybe we could configure rpminspect to not fail on this check?

![tmt-rpminspect](https://github.com/teemtee/tmt/assets/633969/00b3053c-0de8-44f3-bbe7-996d14aaea9c)

**Comment by lukaszachy** [comment]
Fixed by Michal:
https://src.fedoraproject.org/rpms/tmt/pull-request/119
https://src.fedoraproject.org/rpms/tmt/pull-request/118
