### ISSUE TITLE
the  guest auto destroy even if add '--skip finish'

### ISSUE THREAD

**Issue by guazhang** [teemtee/tmt#2764]
provision guest with beaker, the test server auto returned   even if add '--skip finish' in tmt cmd.

tmt  run -dvvv --all --skip  finish  provision --insert -h beaker --hardware 'memory >= 4 GiB' --arch x86_64 --image RHEL-9.5.0-20240312.88   plan --name plan/reserve

**Comment by idorax** [comment]
Hi @guazhang, would you please copy and paste your `.fmf` file and the output after running:

```bash
tmt run -dvvv --all --skip finish provision --insert -h beaker --hardware 'memory >= 4 GiB' --arch x86_64 --image RHEL-9.5.0-20240312.88 plan --name plan/reserve
```

Then I can help to take a look, thanks!

**Comment by idorax** [comment]
Hi @guazhang, why did you close this issue? If you add a justification to this issue, it would be very helpful for us to understand the context, thanks!

**Comment by guazhang** [comment]
sorry, I forget add some comments here.
the cmd `tmt run -dvvv --all --skip finish provision --insert -h beaker --hardware 'memory >= 4 GiB' --arch x86_64 --image RHEL-9.5.0-20240312.88 plan --name plan/reserve` works well.

I package the tmt cmd and add a function that auto return beaker server if all case run pass. 
I forget comment it.
