### ISSUE TITLE
tmt doesn't seem to survive a job that takes longer than the krb ticket validity

### ISSUE THREAD

**Issue by rh-mcermak** [teemtee/tmt#2774]
I'm running jobs that take more than 12 hours.  These are upstream testsuites.  I seem to be facing mrack krb auth problems in this case where the test execution time exceeds the krb ticket validity.

I've tested this with a plain sleep 12h.  It fails.  Try to run a 12h sleep with tmt using beaker.  The test itself will pass, but then the test system fails to return to beaker:

1710960393 [2024-03-20 19:46:33]         value = ctx.invoke(self._result_callback, value, **ctx.params)
1710960393 [2024-03-20 19:46:33]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1710960393 [2024-03-20 19:46:33]       File "/home/mcermak/.local/share/hatch/env/virtual/tmt/a-r_hJmE/dev/lib/python3.11/site-packages/click/core.py", line 783, in invoke
1710960393 [2024-03-20 19:46:33]         return __callback(*args, **kwargs)
1710960393 [2024-03-20 19:46:33]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
1710960393 [2024-03-20 19:46:33]       File "/home/mcermak/.local/share/hatch/env/virtual/tmt/a-r_hJmE/dev/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
1710960393 [2024-03-20 19:46:33]         return f(get_current_context(), *args, **kwargs)
1710960393 [2024-03-20 19:46:33]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1710960393 [2024-03-20 19:46:33]       File "/home/mcermak/tmt/tmt/cli.py", line 508, in finito
1710960393 [2024-03-20 19:46:33]         click_context.obj.run.go()
1710960393 [2024-03-20 19:46:33]       File "/home/mcermak/tmt/tmt/base.py", line 3559, in go
1710960393 [2024-03-20 19:46:33]         raise tmt.utils.GeneralError(
1710960393 [2024-03-20 19:46:33]     tmt.utils.GeneralError: plan failed
1710960393 [2024-03-20 19:46:33] 
1710960393 [2024-03-20 19:46:33] The exception was caused by 1 earlier exceptions
1710960393 [2024-03-20 19:46:33] 
1710960393 [2024-03-20 19:46:33] Cause number 1:
1710960393 [2024-03-20 19:46:33] 
1710960393 [2024-03-20 19:46:33]     <Fault 1: "<class 'bkr.server.identity.IdentityFailure'>: Anonymous access denied">
1710960393 [2024-03-20 19:46:33] 
1710960393 [2024-03-20 19:46:33]         Traceback (most recent call last):
1710960393 [2024-03-20 19:46:33]           File "/home/mcermak/tmt/tmt/base.py", line 3555, in go
1710960393 [2024-03-20 19:46:33]             plan.go()
1710960393 [2024-03-20 19:46:33]           File "/home/mcermak/tmt/tmt/base.py", line 2304, in go
1710960393 [2024-03-20 19:46:33]             self.finish.go()
1710960393 [2024-03-20 19:46:33]           File "/home/mcermak/tmt/tmt/steps/finish/__init__.py", line 198, in go
1710960393 [2024-03-20 19:46:33]             guest.remove()
1710960393 [2024-03-20 19:46:33]           File "/home/mcermak/tmt/tmt/steps/provision/mrack.py", line 781, in remove
1710960393 [2024-03-20 19:46:33]             self.api.delete()
1710960393 [2024-03-20 19:46:33]           File "/home/mcermak/tmt/tmt/steps/provision/mrack.py", line 452, in update_wrapper
1710960393 [2024-03-20 19:46:33]             return asyncio.run(func(*args, **kwargs))
1710960393 [2024-03-20 19:46:33]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1710960393 [2024-03-20 19:46:33]           File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
1710960393 [2024-03-20 19:46:33]             return runner.run(main)
1710960393 [2024-03-20 19:46:33]                    ^^^^^^^^^^^^^^^^
1710960393 [2024-03-20 19:46:33]           File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
1710960393 [2024-03-20 19:46:33]             return self._loop.run_until_complete(task)
1710960393 [2024-03-20 19:46:33]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1710960393 [2024-03-20 19:46:33]           File "/usr/lib64/python3.11/asyncio/base_events.py", line 654, in run_until_complete
1710960393 [2024-03-20 19:46:33]             return future.result()
1710960393 [2024-03-20 19:46:33]                    ^^^^^^^^^^^^^^^
1710960393 [2024-03-20 19:46:33]           File "/home/mcermak/tmt/tmt/steps/provision/mrack.py", line 618, in delete
1710960393 [2024-03-20 19:46:33]             return await self._mrack_provider.delete_host(self._bkr_job_id, None)
1710960393 [2024-03-20 19:46:33]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1710960393 [2024-03-20 19:46:33]           File "/home/mcermak/.local/share/hatch/env/virtual/tmt/a-r_hJmE/dev/lib/python3.11/site-packages/mrack/providers/beaker.py", line 400, in delete_host
1710960393 [2024-03-20 19:46:33]             return self.hub.taskactions.stop(
1710960393 [2024-03-20 19:46:33]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
1710960393 [2024-03-20 19:46:33]           File "/usr/lib64/python3.11/xmlrpc/client.py", line 1122, in __call__
1710960393 [2024-03-20 19:46:33]             return self.__send(self.__name, args)
1710960393 [2024-03-20 19:46:33]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1710960393 [2024-03-20 19:46:33]           File "/usr/lib64/python3.11/xmlrpc/client.py", line 1464, in __request
1710960393 [2024-03-20 19:46:33]             response = self.__transport.request(
1710960393 [2024-03-20 19:46:33]                        ^^^^^^^^^^^^^^^^^^^^^^^^^
1710960393 [2024-03-20 19:46:33]           File "/home/mcermak/.local/share/hatch/env/virtual/tmt/a-r_hJmE/dev/lib/python3.11/site-packages/bkr/common/xmlrpc3.py", line 473, in request
1710960393 [2024-03-20 19:46:33]             result = transport_class.request(self, *args, **kwargs)
1710960393 [2024-03-20 19:46:33]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1710960393 [2024-03-20 19:46:33]           File "/usr/lib64/python3.11/xmlrpc/client.py", line 1166, in request
1710960393 [2024-03-20 19:46:33]             return self.single_request(host, handler, request_body, verbose)
1710960393 [2024-03-20 19:46:33]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1710960393 [2024-03-20 19:46:33]           File "/home/mcermak/.local/share/hatch/env/virtual/tmt/a-r_hJmE/dev/lib/python3.11/site-packages/bkr/common/xmlrpc3.py", line 394, in single_request
1710960393 [2024-03-20 19:46:33]             return self.parse_response(response)
1710960393 [2024-03-20 19:46:33]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1710960393 [2024-03-20 19:46:33]           File "/usr/lib64/python3.11/xmlrpc/client.py", line 1354, in parse_response
1710960393 [2024-03-20 19:46:33]             return u.close()
1710960393 [2024-03-20 19:46:33]                    ^^^^^^^^^
1710960393 [2024-03-20 19:46:33]           File "/usr/lib64/python3.11/xmlrpc/client.py", line 668, in close
1710960393 [2024-03-20 19:46:33]             raise Fault(**self._stack[0])
1710960393 [2024-03-20 19:46:33]         xmlrpc.client.Fault: <Fault 1: "<class 'bkr.server.identity.IdentityFailure'>: Anonymous access denied">

**Comment by rh-mcermak** [comment]
Note that I do have a valid krb ticket at the point of this failure.  I've renewed it in the meantime during the testcase run.  And I've logged/tested that at any time during the test run I had *some* valid krb ticket (I've been periodically running bkr whoami).  But mrack seems to have troubles taking the renewed krb ticket into account.

**Comment by lukaszachy** [comment]
Any idea why I can't link #2775 as PR fixing this issue?
