### ISSUE TITLE
Add CPU vendor HW requirement

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#2837]
Following the `gpu.vendor` and `gpu.vendor-name`.

**Comment by idorax** [comment]
Hi @happz, the subject of this issue includes `CPU` but the description includes `gpu`, is `CPU` in the subject a typo?

**Comment by happz** [comment]
> Hi @happz, the subject of this issue includes `CPU` but the description includes `gpu`, is `CPU` in the subject a typo?

Both are correct: `gpu.vendor` and `gpu.vendor-name` are already defined, we need their counterparts for `cpu` block.

**Comment by qcheng-redhat** [comment]
> > Hi @happz, the subject of this issue includes `CPU` but the description includes `gpu`, is `CPU` in the subject a typo?
> 
> Both are correct: `gpu.vendor` and `gpu.vendor-name` are already defined, we need their counterparts for `cpu` block.

Hi @happz , for CPU, `lscpu` shows:
......
`vendor_id       : GenuineIntel`
......

So we just define `cpu.vendor `or also need` cpu.vendor-name` ?

**Comment by happz** [comment]
Looks like `vendor-name` is what we need the most, and we can ignore `vendor`. See this paragraph on how we differentiate between `foo` and `foo-name` when it comes to properties that are like IDs.
