### ISSUE TITLE
tmt-reboot does not work outside of execute step, i.e. in prepare/finish

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#2869]
`tmt-reboot` assumes it's running in the context of a test, but that's not true in `prepare` or `finish`. Plus there is no code in `prepare` or `finish` plugins that would be able to handle reboot and restart the phase.

**Comment by BeeGrech** [comment]
watching

relates to: VROOM-18747

**Comment by lukaszachy** [comment]
Isn't this duplicate of #902 ?

**Comment by happz** [comment]
Hm, I it, I was unable to find it.
