### ISSUE TITLE
Run test plans parallelly and make them not affect each other

### ISSUE THREAD

**Issue by guoguojenna** [teemtee/tmt#2981]
Submit tests by

```
TMT_SHOW_TRACEBACK=1 tmt -c distro=rhel-9  run provision -h beaker -i RHEL-9.5.0-20240530.48 tests --name .  -dddvvv
```

then several test plans were selected and will be run one by one. Could we make the test plans run parallelly, and make them not affect each other, that's to say, a failure of a test plan running does not quit the overall tmt run, the other test plans can run without interrupt.

**Comment by happz** [comment]
> then several test plans were selected and will be run one by one. Could we make the test plans run parallel,

Yes, we can, yes, we want to, but it's not as trivial as this answer :) But it's a feature we'd like to implement one day.

> and make them not affect each other, that's to say, a failure of a test plan running does not quit the overall tmt run, the other test plans can run without interrupt.

See `tmt run --on-plan-error=continue` - that should let other plans to continue even if some of the previous plans failed.

**Comment by guoguojenna** [comment]
> > then several test plans were selected and will be run one by one. Could we make the test plans run parallel,
> 
> Yes, we can, yes, we want to, but it's not as trivial as this answer :) But it's a feature we'd like to implement one day.
> 
> > and make them not affect each other, that's to say, a failure of a test plan running does not quit the overall tmt run, the other test plans can run without interrupt.
> 
> See `tmt run --on-plan-error=continue` - that should let other plans to continue even if some of the previous plans failed.

Good to know, thank you!
