### ISSUE TITLE
Feature schema missing `name`, `order`

### ISSUE THREAD

**Issue by martinhoyer** [teemtee/tmt#2984]
`tmt lint` reporting false positives when `order` or `name` is added to `feature`  prepare steps.

**Comment by LecrisUT** [comment]
Probably the schema files should be refactored a bit to use `definitions` and `one_of`. Maybe could try:
```yaml
definitions:
  feature:
    properties:
      how:
        type: string
        enum:
          - feature
      epel:
        type: string
        enum:
          - enabled
          - disabled
one_of:
  - $ref: "/schemas/core#/definitions/core"
  - $ref: "#/definitions/feature"
required:
  - how
```

Dunno how well these mix though, particularly `required` over there. Having some reference would definitely be helpful for plugin development.

**Comment by psss** [comment]
> Probably the schema files should be refactored a bit to use `definitions` and `one_of`.

Looks like a good idea. Let's cover that in a separate pull request.
