### ISSUE TITLE
RPM 4.20 change in directory structure changes expectations, thus making tests fail

### ISSUE THREAD

**Issue by stratakis** [teemtee/tmt#2987]
RPM 4.20 introduced https://github.com/rpm-software-management/rpm/issues/2078, which basically makes the %prep section of the rpmbuild process extract the sources to `BUILD/foo-<version>-build/foo-<version>/`  instead of `BUILD/foo-<version>/`, essentially changing the use case we had before with the $TMT_SOURCE_DIR variable.

This breaks expectations, for example our Cython rawhide package [testing](https://src.fedoraproject.org/rpms/Cython/blob/ccc0af15257ec093357c1f1fec83d86fac784e07/f/tests/testsuite/main.fmf) fails as the dir structure is wrong, while the same works for Fedora 40, where RPM doesn't have this feature.

We can fix it by changing the directories of course, but ideally a conditionalized value of $TMT_SOURCE_DIR depending on the feature existence would be non-disruptive. Currently way too many packages that we have set a CI for will fail due to this change.

**Comment by hroncok** [comment]
IMHO $TMT_SOURCE_DIR remains the same, but the sources are now unpacked one level deeper.

**Comment by stratakis** [comment]
> IMHO $TMT_SOURCE_DIR remains the same, but the sources are now unpacked one level deeper.

edited accordingly.

**Comment by lukaszachy** [comment]
I received some tips what to do, lets see.

**Comment by lukaszachy** [comment]
@pmatilai So I've tried the `builddir=$(dirname $(find /foo demo.spec))` but the 'demo.spec' isn't copied into _builddir.

rpm-4.19.91-6.fc41.x86_64
rpm-build-4.19.91-6.fc41.x86_64

```
$ cat demo.spec 
Name: demo
Version: 1.0
Summary: Trying discover with applied patches
Release: 1
License: MIT
BuildArch: noarch
Source0: no-tmt-2.tgz

%description
Some tests are being added by patches, lets discover them correctly

%prep
%autosetup -n no-tmt-2

%install

%changelog
* Thu Jun 1 2023 Lukas Zachar <lzachar@redhat.com> 0.1-1
```

And when I do `# rpmbuild -bp --define "_sourcedir $(pwd)" demo.spec  --define '_builddir /foo'` the created '/foo' contains no spec file.
 ```
# find /foo
/foo
/foo/demo-1.0-build
/foo/demo-1.0-build/SPECPARTS
/foo/demo-1.0-build/no-tmt-2
/foo/demo-1.0-build/no-tmt-2/all_in_one
```

Could the feasible workaround be the find where SPECPARTS directory is instead?

**Comment by AdamWill** [comment]
> I've now come across a case where a test unpacked an src.rpm, locally built it and ran the test-suite within.

We also have an entire standardized mechanism for doing this, which the change broke in the same way. https://bugzilla.redhat.com/show_bug.cgi?id=2290735

**Comment by pmatilai** [comment]
Yup, this is an entire pattern whose existence has taken us by surprise. We'll need to look into better supporting the use-case, but for the short-term, I came up with a trick to fish the contentious builddir from rpmbuild in what should be a compatible manner across old and new rpm versions. See https://github.com/rpm-software-management/rpm/issues/3147#issuecomment-2154192419
