### ISSUE TITLE
Exception when running Ansible preparation from CLI

### ISSUE THREAD

**Issue by mizdebsk** [teemtee/tmt#3051]
When trying to run `prepare --how ansible` from command line, tmt crashes with an exception.

I'm using latest tmt from main branch (commit 9717fc412d27256a10e7eef5319cc279ec3c4e2c).

Reproducer:

1. Initialize new tmt tree with `tmt init`

2. Write Ansible playbook as `hello.yml` with the following contents:

```
- hosts: all
  gather_facts: no
  tasks:
    - debug:
        msg: hello
```

3. Run the following command:

```
tmt run provision --how container --image fedora:rawhide prepare --how ansible --playbook hello.yml
```

Expected results:

Preparations are applied without error.

Actual results:

```
/var/tmp/tmt/run-001

/default/plan

plan failed

The exception was caused by 1 earlier exceptions

Cause number 1:

    Failed to load step data for PrepareAnsibleData: 

    The exception was caused by 1 earlier exceptions

    Cause number 1:
```

**Comment by happz** [comment]
@mizdebsk I didn't notice you also provided a fix, thanks for that. But... I don't want to sound ungrateful, yet I'd prefer my patch, there's also a bug in handling of `playbooks` key (which is still supported in fmf files), and includes an improvement to a library function that's exactly the right for the job.

**Comment by mizdebsk** [comment]
Thanks for your better fix @happz. I wrote my patch to make tmt work for me because I didn't expect any fix that quickly, but I'll happily switch to yours.
