### ISSUE TITLE
`tmt` cannot be installed on centos-stream-9?

### ISSUE THREAD

**Issue by LecrisUT** [teemtee/tmt#3102]
I have tried to spin up a centos-stream-9 container:
```console
$ podman pull centos:stream9
Trying to pull quay.io/centos/centos:stream9
```

But it seems some dependencies are missing
```console
# dnf install tmt
Error: 
 Problem: conflicting requests
  - nothing provides python3.9dist(pygments) >= 2.7.4 needed by tmt-1.34.0-1.el9.noarch from epel
```

How is testing-farm not breaking? What I can see in the artifact installation (`4-Install-packages.txt`) it seems to use `testing-farm-tag-repository`:
```
 python3-pygments                     noarch  2.7.4-4.el9                                                testing-farm-tag-repository  1.8 M
```

**Comment by happz** [comment]
You need CRB, according to https://tmt.readthedocs.io/en/stable/overview.html#install: `dnf config-manager --enable crb`

**Comment by LecrisUT** [comment]
Oh, I thought I've enabled it when going through https://www.redhat.com/sysadmin/install-epel-linux. Indeed I tried it again and it works now :shrug:
