### ISSUE TITLE
can't use several instances of tmt run in parallel

### ISSUE THREAD

**Issue by vkadlcik** [teemtee/tmt#3164]
If I run several instances of tmt in parallel, they all try to access their respective provisioned machine via `ssh -S/run/user/1000/tmt-default-0`. Example from `ps axuww`:
```
vkadlcik   18786  0.3  0.0  13984 10116 pts/12   S+   17:50   0:02 ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectionAttempts=5 -oConnectTimeout=60 -oServerAliveInterval=5 -oServerAliveCountMax=60 -oPasswordAuthentication=no -S/run/user/1000/tmt-default-0 -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectionAttempts=5 -oConnectTimeout=60 -oServerAliveInterval=5 -oServerAliveCountMax=60 -oPasswordAuthentication=no -S/run/user/1000/tmt-default-0 -MNnT root@dell-r640-067.bkr.lab.eng.rdu2.dc.redhat.com
vkadlcik   19861  0.0  0.0  13704  9816 pts/7    S+   17:58   0:00 ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectionAttempts=5 -oConnectTimeout=60 -oServerAliveInterval=5 -oServerAliveCountMax=60 -oPasswordAuthentication=no -S/run/user/1000/tmt-default-0 -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectionAttempts=5 -oConnectTimeout=60 -oServerAliveInterval=5 -oServerAliveCountMax=60 -oPasswordAuthentication=no -S/run/user/1000/tmt-default-0 -MNnT root@hpe-apollo-cn99xx-16.khw.eng.rdu2.dc.redhat.com
```
In other words, they all are accessing the very same machine - the one which was provisioned first.

I found this commit d549bd3aa3e2eb5e3e8ba984c1e293f97409253e that seems related. However my guess is it probably fixes just the multihost scenario within one and only tmt instance. Not several tmt instances in parallel.

The socket paths must distinguish parallel runs. Many solution are possible, e.g. their name could include the tmt run id or the hostnames (as recommended in https://man.openbsd.org/ssh_config#ControlPath). Maybe what I'd like most would be placing the socket in its related `/var/tmt/tmt/run-NNNN`; then I could easily find all the run data in one place.

**Comment by martinhoyer** [comment]
Thanks, this was discussed today and you rightly pointed to https://github.com/teemtee/tmt/commit/d549bd3aa3e2eb5e3e8ba984c1e293f97409253e.  
Will be fixed in the following release.  

@happz do you want me to work on this (+move it under provision) or do you already have PR ready as usual? ;)

**Comment by happz** [comment]
@martinhoyer an untested one, https://github.com/teemtee/tmt/pull/3165. It may fail tests, a lot.

**Comment by vkadlcik** [comment]
FWIW, I replaced  my `/usr/lib/python3.12/site-packages/tmt/steps/provision/__init__.py` of tmt-1.35.0-2.fc40.noarch with the suggestion above (https://github.com/teemtee/tmt/blob/f367e70699624eb4c7a33d41db02ce31e5d8eccc/tmt/steps/provision/__init__.py) and used it all day yesterday in various parallel batches. My problem is gone and I haven't seen any regression. Thanks, @happz!
