### ISSUE TITLE
Implement the check `result` key

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#3185]
Similarly to the `result` key it would be good to have a `check-result` key which would decide how the check results should affect the final result of a test, e.g. `respect` or `ignore`. The original result of the test execution itself should be stored in the `results.yaml` as well so that it can be inspected if needed.

There is an expectation that check results should by default affect the final result so that possible problems are revealed for example in Testing Farm viewer, so the default values should probably be `respect`.

**Comment by dennisbrendel** [comment]
General comment on the way check works: It calls `dmesg -c` (or `dmesg --read-clear`), so it also messes with the buffer, which can be unexpected for users. In addition it is not always reliable, because some tests also clear the buffer during runtime.

Are there concerns switching over to reading the journal instead? And fallback to `dmesg` when no systemd-journald is available?

**Comment by martinhoyer** [comment]
> General comment on the way check works: It calls `dmesg -c` (or `dmesg --read-clear`), so it also messes with the buffer, which can be unexpected for users. In addition it is not always reliable, because some tests also clear the buffer during runtime.
> 
> Are there concerns switching over to reading the journal instead? And fallback to `dmesg` when no systemd-journald is available?

Good point, thanks! [Check](https://tmt.readthedocs.io/en/stable/spec/tests.html#check) is a optional step and not necessarily 'dmesg'. For example, there can be "journal" check plugin implemented.

That said, it was discussed before. I'd like to look into incorporating `coredumpctl` tool as a "test check". 
In any case, this PR is not the right place for this discussion :)

**Comment by martinhoyer** [comment]
@psss I'm thinking whether it wouldn't make sense to have `ignore` option per each check instead. It could look like:
```
check:
  - how: avc
    enable: false
  - how: dmesg
    ignore: true
```
wdyt?

**Comment by happz** [comment]
@martinhoyer Would it make sense to use the `result` key, similarly to how is used in test metadata? I.e. if I wish to (temporarily) ignore a check, I'd set its `result` to `pass`, and so on. The benefit would be fewer new keys and concepts, and this `ignore` seems like a special case of `result`, https://tmt.readthedocs.io/en/stable/spec/tests.html#result

**Comment by martinhoyer** [comment]
@happz hmm not sure. Afaik we don't want to change the result of the check itself.  
Other idea is to allow check.enabled to be true/false/ignore, which could be nice from user perspective, but I assume quite funky under the hood.

Let's see if @psss wants check-result or is open to this per-check setting idea in the first place :)

**Comment by happz** [comment]
> @happz hmm not sure. Afaik we don't want to change the result of the check itself.

True, wrong place, `check-result` test key is the right one.

> Other idea is to allow check.enabled to be true/false/ignore, which could be nice from user perspective, but I assume quite funky under the hood.

That would be ugly, not just the implementation but also the specification.

> Let's see if @psss wants check-result or is open to this per-check setting idea in the first place :)

Per-check control can be added later, I believe, if needed.

**Comment by martinhoyer** [comment]
> Per-check control can be added later, I believe, if needed.

I was thinking more about doing one or the other. i.e. either specifying it as part of check object(s), or the original idea. I'm having a hard time visualizing it how it would work with subresults and when users would like to just do a simple `adjust` to affect all the checks...so if you say it's best to not worry about per-check for now I'm happy.  
btw: and other ideas for the key name?

**Comment by martinhoyer** [comment]
Thanks @happz! I'll work on it today.

**Comment by psss** [comment]
I'd agree with @happz that introducing new key like `ignore` or mixing `true/false/enabled` under the `enabled` key would not be a good idea. I would always suggest to keep consistency as much as possible.

Which leads to the interesting idea of not introducing a new key name `check-result` but rather keeping `result` with basically the same (or very similar) meaning, just putting it under the `check` field:

```yaml
test: test.sh
check:
  - name: avc
    result: xfail
```

This could be useful for covering expected `avc` failures with `xfail` for example. I have to admit that this approach sounds tempting to me. It would be nicely packaged close to the check definition itself, it would be consistent with the test `result` key as well.

I also see @happz's point, starting with a single "global" `check-result` also makes sense, although, my feeling is that the use case of completely disabling all checks will not be that common.

**Comment by happz** [comment]
> I would find it useful to have the setting per test. I am not an active `tmt` user currently, but I see our plans often have a mixture of tests where some would be expected to fail for some checks while others must not.

That should be supported in any case, the debate above is mostly about whether the control should be per test, or even more granular, per test check. The most granular way, "per test check", seems to be getting most support.

**Comment by dennisbrendel** [comment]
> The most granular way, "per test check", seems to be getting most support.

Yes :-)
