### ISSUE TITLE
Race condition in the `testcloud` plugin

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#3235]
Based on the recent results of the `/plans/provision/virtual/*` plans it seems the race condition is still there. Multihost tests quite frequently fail with:

    Failed to connect in 300s.

@frantisekz, in #3036 you've mentioned that the change opens way to address the problem in an atomic way. Would you have some time to look into this?

**Comment by psss** [comment]
Here's a [recent example job](https://artifacts.osci.redhat.com/testing-farm/f8652173-3a93-4d75-87af-f2c612c1aae4/) with the [full log details](https://artifacts.osci.redhat.com/testing-farm/f8652173-3a93-4d75-87af-f2c612c1aae4/work-preparelzoi94gk/plans/provision/virtual/prepare/execute/data/guest/default-0/tests/prepare/multihost-3/data/tmp-tmp.sm38eMweLF-log.txt).

**Comment by frantisekz** [comment]
Yeah, I had it upstream for some time: https://pagure.io/testcloud/c/6da8ed8c96e3f748f8c242dc168b45017be251f5?branch=master

I can bake out copr build at least if that'd help with testing? Release is currently held by https://pagure.io/testcloud/issue/191 from rewritten image code, I'll poke some more there to get that resolved.
