### ISSUE TITLE
Add support for user defined test templates

### ISSUE THREAD

**Issue by sopos** [teemtee/tmt#367]
`tmt tests create` should be able to use user defined templates similarly to `beaker-wizard -s template_name` where the template is defined in the `~/.beaker_client/wizard`

It should be possible to provide a template for the test code and the metadata as well, e.g. some basic set of `require`.

**Comment by lukaszachy** [comment]
Raising priority - for existing users of beaker-wizard it is easier to first run wizard and then import to tmt. Missing custom templates is not good for tmt.

Doing  `cp -r <old test> <new>` another way to get "templates".
But it would be great if tmt could to that on its own (including adding virtual cases).

**Comment by sopos** [comment]
I used to use `beaker-wizard` because it was able to fill most of the data out of a BZ. Now I simply copy existing test and change things. If the template was just static without any automatic data gathering from BZ/Jira/whatever I would stick with copying old test I think.

**Comment by psss** [comment]
This is one of the blockers to provide a comfortable & concise way to create new tests, blocking [TT-242](https://issues.redhat.com/browse/TT-242). Let's try to implement in 1.28.

**Comment by thrix** [comment]
@sopos what do you think, could you maybe contribute with this one.

Seems @psss and @lukaszachy have some ideas how it could be done reasonably.

**Comment by lukaszachy** [comment]
Would be nice if there could be several test cases created from single template. 
As I create tests for python (which exists as several, parallel installable components) I need to create several test cases. So my workflow at the moment is to have directory with skeleton files (test.sh, main.fmf, python3.fmf, python311.fmf ...) I copy to newly created test directory.

**Comment by happz** [comment]
Aaand one note from me, it'd be nice to use Jinja templates for templates, rather than having them hardcoded in `tmt.templates`. We can bundle the whole directory structure into tmt package, we can have subdirectories for various types of plans/tests and their skeleton files, etc.

**Comment by psss** [comment]
Forwarding an idea from @kkaarreell:

> If I may, I think it would be nice to support loading template from URL. A team could store component specific template in a test repository, ensuring it is always up to date.

Sounds like a useful feature to me.
