### ISSUE TITLE
Teach `tmt test create` to link relevant issues

### ISSUE THREAD

**Issue by sopos** [teemtee/tmt#368]
Similarly to `beaker-wizard -b BZ#` it would be convenient to let tmt prefill some values based on a bugzilla.

**Comment by psss** [comment]
I'm a little bit hesitant about this feature. From the past experience with `beaker-wizard` it seems that people quite often blindly take whatever `beaker-wizard` detects from Bugzilla which then resulted in weird test names (e.g. cut in the middle of the sentence), copy-pasted PURPOSE files which no one used.

Which information do you suggest to be detected from the bug? Perhaps there are still some useful data which could be auto-filled but as far as summary and description are concerned I would rather encourage/force users to write something reasonable.

**Comment by sopos** [comment]
It is mainly about the laziness. Actually I do not care of the name much so I'm one of those who blindly take anything. :-)

**Comment by pemensik** [comment]
I think main issue with prefilled name were inability to rename test later. Would that be also issue with tmt?

**Comment by lukaszachy** [comment]
Adding 'should' priority as this has been raised several times already.

**Comment by psss** [comment]
> I think main issue with prefilled name were inability to rename test later. Would that be also issue with tmt?

Yes, renaming is no problem. But I don't see benefit in defaulting to create an ugly name with possible future (and usually not very probable) possibility of change to something better. Why should we not create tests with nice names directly? I'd like to repeat my question:

> Which information do you suggest to be detected from the bug? Perhaps there are still some useful data which could be auto-filled but as far as summary and description are concerned I would rather encourage/force users to write something reasonable.

With the one-year experience with `tmt` I find it very useful to organize tests reasonably according to the area they cover. This allows for example to easily execute all tests related to given area which I have just modified with my patch:

    tmt run test --name execute

**Comment by brakogh** [comment]
With beaker-wizard, my workflow is:
1. cd <comp_git>
2. beaker-wizard -b <num>
3. modify or use provided test name, provide test type, description and test run time, confirm
4. vim <path>/runtest.sh and write test code

I'd like to have main.fmf and test.sh ready to write code with similar simple steps.

**Comment by kkaarreell** [comment]
I agree with @psss . Our old tests created using beaker-wizard didn't really provided descriptive test summary (what the actual test does) and  Jira ticket clearly can't.

**Comment by psss** [comment]
As discussed on today's stakeholders meeting, let's introduce a new option for specifying the related issue:

    tmt test create /tests/name --issue https://bugzilla.redhat.com/show_bug.cgi?id=1234567

By default I'd say `verifies` relation should be used. Optionally, it could be specified on the command line, for example:

    tmt test create /tests/name --relation=verifies --issue ...
    tmt test create /tests/name --relation=relates --issue ...

Or the naming could be more close to the `link` key, perhaps something like this?

    tmt test create /tests/name --link-verifies https://issues.redhat.com/browse/TT-123
    tmt test create /tests/name --link-relates https://issues.redhat.com/browse/TT-123

In order to use the default relation, the short `--link` version could be used:

    tmt test create /tests/name --link https://issues.redhat.com/browse/TT-123

Providing the full url allows to use different issue tracking systems rather than limiting the functionality to a single tool.

**Comment by psss** [comment]
This is one of the blockers to provide a comfortable & concise way to create new tests, blocking [TT-242](https://issues.redhat.com/browse/TT-242). Let's try to implement in `1.27` as it is an easy fix.

**Comment by idorax** [comment]
Hi @psss, I'd like to help to fix this issue.

>  It makes a perfect sense to me to create a link section pointing to the related bugzilla.

Do we just need to add one line to the fmf file? e.g.
```
link: https://issues.redhat.com/browse/TT-123
```
> By default I'd say verifies relation should be used. Optionally, it could be specified on the command line, for example:
>
> tmt test create /tests/name --relation=verifies --issue ...
> tmt test create /tests/name --relation=relates --issue ...


I'm not sure `relation` should be added too, please help to clarify, thanks!

**Comment by psss** [comment]
The newly created test should have the `link` with appropriate `relation` included in the `fmf` metadata. From the options brainstormed [above](https://github.com/teemtee/tmt/issues/368#issuecomment-1385625786) I'd vote probably for the shortest way for the most common use case (e.g. writing a test verifying an issue), so that:

    tmt test create /tests/name --link https://issues.redhat.com/browse/TT-123

would create a new test with the following link:

    link:
      - verifies: https://issues.redhat.com/browse/TT-123

We should also allow choosing a different relation if needed. For that I'd propose using:

    tmt test create /tests/name --relation relates --link https://issues.redhat.com/browse/TT-123

which would lead to:

    link:
      - relates: https://issues.redhat.com/browse/TT-123

What do you think?

**Comment by idorax** [comment]
The final solution is to support multiple links via `relation:target`.   For example,

1. Create one link without `relation`, which will use the default one - `relates`
   ```bash
   $ tmt test create /tests/foo1 -t shell --link foo
   ```
   which would lead to:
   ```yaml
   link:
     - relates: foo
   ```

2. Create one line with `relation`
    ```bash
    $ tmt test create /tests/foo1 -t shell \
      --link verifies:https://issues.redhat.com/browse/TT-123
    ```
    which would lead to:
    ```yaml
    link:
      - verifies: https://issues.redhat.com/browse/TT-123
    ```

3. Create multiple links
    ```bash
    $ tmt test create /tests/foo1 -t shell \
      --link foo \
      --link verifies:https://issues.redhat.com/browse/TT-123 \
      --link relates:https://issues.redhat.com/browse/TT-124
    ```
    which would lead to:
    ```yaml
    link:
      - relates: foo
      - verifies: https://issues.redhat.com/browse/TT-123
      - relates: https://issues.redhat.com/browse/TT-124
    ```
