### ISSUE TITLE
Improve help text of the `tmt --root` option

### ISSUE THREAD

**Issue by sopos** [teemtee/tmt#371]
`tmt --help` says `-r, --root PATH  Path to the tree root, '.' by default`, however it looks like `/` is the actual default.
```
$ tmt tests ls .
/Sanity/users-shell-script

$ tmt tests ls
/Functional/SoftwareRestrictionPoliciesTest12
/Functional/SoftwareRestrictionPoliciesTest7
/Regression/bz1721496-Stop-littering-STDOUT-output-for-dnf
/Regression/bz1746464-default-fapolicyd-policy-prevents-ansible-from-running
/Regression/bz1747494-suspicious-logs-on-service-start
/Regression/bz1757736-fapolicyd-blocks-dracut-from-generating-initramfs
/Regression/bz1765039-fapolicyd-fails-to-identify-perl-interpreter
/Regression/bz1817413-segfault-on-update
/Regression/bz1817969-Cannot-execute-gcore-from-gcc-toolset-9-when
/Sanity/FapolicydRules
/Sanity/cli-options
/Sanity/fuzzer-radamsa
/Sanity/selinux
/Sanity/sets
/Sanity/trust-db
/Sanity/users-shell-script

$ tmt tests ls /
/Functional/SoftwareRestrictionPoliciesTest12
/Functional/SoftwareRestrictionPoliciesTest7
/Regression/bz1721496-Stop-littering-STDOUT-output-for-dnf
/Regression/bz1746464-default-fapolicyd-policy-prevents-ansible-from-running
/Regression/bz1747494-suspicious-logs-on-service-start
/Regression/bz1757736-fapolicyd-blocks-dracut-from-generating-initramfs
/Regression/bz1765039-fapolicyd-fails-to-identify-perl-interpreter
/Regression/bz1817413-segfault-on-update
/Regression/bz1817969-Cannot-execute-gcore-from-gcc-toolset-9-when
/Sanity/FapolicydRules
/Sanity/cli-options
/Sanity/fuzzer-radamsa
/Sanity/selinux
/Sanity/sets
/Sanity/trust-db
/Sanity/users-shell-script
```
Based on the help text I would expect `tmt tests ls` to give the same result as `tmt tests ls .`

**Comment by psss** [comment]
Current working directory is used as the default place where to start looking for the metadata tree root. This is similar to how git detects root of the git repository. So this is working as expected. By default you always get all available objects, no filter is applied.

**Comment by sopos** [comment]
I see your point but first I think we do not need to mimic git in this way and second I do not understand the `-r` option then.

**Comment by psss** [comment]
The `--root` says where to start looking for metadata. For example you don't need to enter the git repo to check what available:

    cd
    tmt --root git/tmt

**Comment by sopos** [comment]
Ok, so it is a starting point for upwards traversal to find the actual root. May be the help text should be updated.

Anyway we can discuss what implicit behaviour is better and what to explicitly use `.` or `/`.

**Comment by sopos** [comment]
My behaviour assumption is base on the `ls` rather than `git` and `tmt tests ls` makes me think of that as `ls`.
May be we can change this issue to 'improve -r help text'. And have another one for the discussion about possible `.` vs. `/` change.

**Comment by valgrut** [comment]
What about to change it to the same text as --root option in docs/overview.rst is described?

There is "Path to the metadata tree, current directory used by default."
We could use it unchanged or change the description in help to something like:
- "Path to the metadata tree root, current directory used by default." or
- "Path to the root of the metadata tree, current directory used by default."

And I am not sure, if the second part (with default directory) is necessary here since '--root' option requires path. I know that is meant as the behavior when tmt is used without the option, but maybe by omiting this, description of this option would not be misleading.

**Comment by sopos** [comment]
I do not have any strong opinion here. I was just confused by the behavior vs the description. And the fact it is actually a path where the upwards traversal starts does not really fit the _root_ definition.

**Comment by ivet1987** [comment]
Looks as a good first issue for me if still valid :-D

**Comment by psss** [comment]
Covered by #1991.
