### ISSUE TITLE
Add Contacts to readme

### ISSUE THREAD

**Issue by pvalena** [teemtee/tmt#478]
IRC, and, maybe, additionaly create a mailing list?

( https://lists.fedoraproject.org/ maybe? )

**Comment by psss** [comment]
Not sure if it's worth creating a new mailing list. If needed I guess we can try the github [discussions](https://github.com/psss/tmt/discussions) feature? Regarding chat, so we have the `#tmt` channel at freenode, that can be added to documentation. Or, would it make sense to try something like Telegram? We have already experimented with a [channel](https://web.telegram.org/#/im?p=g465516144) there and it seems quite fine to me. Others, what do you think? @lukaszachy, @thrix, @hegerj, @FrNecas?

**Comment by hegerj** [comment]
I am probably not going to join new messaging service, unless it proves excellent, so I would rather use platform that we all already have access to (i.e. GitHub Discussions) if there is need for another communication channel.

**Comment by lukaszachy** [comment]
Hm,I like telegram as a fast, public way to reach/discuss e.g. on holidays. But at the same time I'm not really willing to provide same SLA:) 
What I hate on IRC is the lack of channel history.

Discuss feature seems like a good compromise to try.

Either way I didn't know about freenode's channel until this issue.

**Comment by pvalena** [comment]
Oh I can post history in automated way each day at midnight f.e. ;). And my irc is always running (multiple services).

Also, I guess, no SLA is expected for an IRC / community support.

Github discussions sounds great as well! I hope they send notifications (I didn't try it). Personally I'm against Telegram (or any 3rd party SW), although I've used Telegram in the past (and it even has a Fedora app, and a web client), but it's an additional service for me (one too much), so won't be participating.

**Comment by pvalena** [comment]
There is https://gitter.im/ in case there's any interest. Closing stale issue.
