### ISSUE TITLE
RFE: Support memory limits for Containers.

### ISSUE THREAD

**Issue by pvalena** [teemtee/tmt#498]
I think I'm failing on OOM in my container. Is there any way to allow for more memory usage?

(This is probably caused by userspace containers.)

**Comment by pvalena** [comment]
Alternatively, allow for additional args, like "`–oom-kill-disable=true`".

**Comment by psss** [comment]
As for now the `podman` plugin does not set memory limit and from the quick check using:

    tmt run -a provision -h container execute -vvv -h tmt -s free

it seems the whole amount of host memory is available inside the container.

**Comment by pvalena** [comment]
Right, it's using some userspace default, but's it seems to cause some OOM issues for me on Fedora rawhide.
Should I create a reproducer?

IMHO I simply expect the `memory: ...` to work.

**Comment by psss** [comment]
> Right, it's using some userspace default...

To me it seems the default is to provide all available host memory unless `--memory` is given (which is not the case for the `podman` plugin).

**Comment by pvalena** [comment]
I'll try to look into the reproducer, pinpoint the issue I'm experiencing, and create appropriate issue if it's somehow caused by TMT.

Let's change this into RFE (which I hope will resolve the issue I'm experiencing).

**Comment by pvalena** [comment]
Let's leave this up to the system. There's probably no expectation for TMT to support this as of now. I've not seen it's usage for containers since.
