### ISSUE TITLE
Implement option to login to tmt reserved machine after test into the correct test folder.

### ISSUE THREAD

**Issue by Athwale** [teemtee/tmt#519]
A common use case for testers using 1minutetip and Makefiles is to run a test which ends in 1mt allowing the user to log in after the test and experiment with the test code directly on the machine where the test can be modified, developed and rerun using "make run".

Tmt could allow something similar like tmt run execute -h tmt --login which would login after each finished test to the appropriate test directory on the guest.

**Comment by psss** [comment]
I believe this should be relatively easy to do, basically reuse the already implemented `login` command functionality under the `execute` step.
