### ISSUE TITLE
Bad transformed fmf id for pagure

### ISSUE THREAD

**Issue by jscotka** [teemtee/tmt#720]
it seems that there is some transformation of git sources for cloning and it does not work well.

it converted: `ssh://git.src...:32101/tests//cockpit` -> `https://git.src....:32101/tests//cockpit`

and this is not valid url for pagure instance

 when used git to distgit directly, it works as charm.

**Comment by psss** [comment]
So we do the best effort how to map git links which use authentication to those which are public here:

https://github.com/psss/tmt/blob/22082b8251b7daba533398d0bb35ed9a6644e825/tmt/utils.py#L959

It works fine with dist git links and external pagure fine. But the internal pagure seems to be tricky...

**Comment by jscotka** [comment]
proper one is: https://src....:443/tests/cockpit.git

**Comment by jscotka** [comment]
with @psss  we've discussed, that at least there could be some error in this case when matched git url:
like:
```python
if re.search("git\.src\.osci\.redhat\.com/", url):
     raise error("Use internal distgit for git")
```
