### ISSUE TITLE
Documentation: ambiguous paragraph in Specification / Tests / test

### ISSUE THREAD

**Issue by befeleme** [teemtee/tmt#738]
Both the wording and examples in [Specification / Tests / test](https://tmt.readthedocs.io/en/latest/spec/tests.html#test) create an impression that it is possible to run more tests with `test` key in one test file. But an attempt to do so results in *duplicate keys* error.
The possible way to execute more tests (or eg. parametrized test script) in a single file would be to nest the levels like this:
```
/foo:
    test: ./test.sh foo
/bar:
    test: ./test.sh bar
```
This could be changed in documentation to avoid ambiguity.

**Comment by lukaszachy** [comment]
This affects most of examples. E.g plans in https://tmt.readthedocs.io/en/latest/spec/plans.html#multihost

We need to make sure to split examples into working blocks (e.g. each example in its own block).

**Comment by psss** [comment]
As for now the story `example` key can contain just a single text and thus the export to `rst` can create just a single box. We could extend the `story` spec and export if needed. But for now, as a quick fix, I'd suggest to make it a bit more clear by using a comment for each example as proposed in #1122.
