### ISSUE TITLE
Implement socket connection for ssh

### ISSUE THREAD

**Issue by thrix** [teemtee/tmt#854]
Tools using SSH usually implement reusing of ssh connection via a socket which greatly speeds up the ssh commands. We should look into if this would be possible in tmt to gain the same benefit.

Some similar concepts used by other tools:
https://docs.ansible.com/ansible/latest/reference_appendices/config.html#envvar-ANSIBLE_PIPELINING
https://puppet.com/blog/speed-up-ssh-by-reusing-connections/

**Comment by RHEmployee** [comment]
Hello. Is this still free?
There is already master connection with multiplexing used in 1minutetip so I less or more understand that topic.

**Comment by FrNecas** [comment]
As far as I know, noone has expressed interest in working on this yet, I assigned it to you @RHEmployee

**Comment by RHEmployee** [comment]
Thank you.

**Comment by RHEmployee** [comment]
Hello.

After some digging. Putting all in one place to avoid fragmentation.

Looks like paramiko library doesn't support multiplexing:
https://github.com/paramiko/paramiko/issues/852
so ControlMaster seems to not be supported.

So I just fallback back to use CLI ssh, however this needs one process for master connection which going to run in background while tmt runs. Then cleanup is needed to avoid many processes on system which dies eventually but it takes some time.

There is one issue with openssh with -S argument however it's not directly openssh issue but it is issue of userland/kernel which doesn't allow sun_path longer than exact num of chars (256 or similar size which you can read: not enought).
https://github.com/openssh/openssh-portable/blob/master/mux.c#L2265

I still investigate in parallel other libs for ssh however main goal is to gain multiplexing.
Main source of material for further investigation is here:
https://medium.com/the-elegant-network/a-tale-of-five-python-ssh-libraries-19cb8b72c914

**Comment by RHEmployee** [comment]
WIP is now here:
https://github.com/psss/tmt/pull/900

it seems to work, but some code cleanup will be nice.

**Comment by RHEmployee** [comment]
Add support for ssh multiplexing has been merged. Closing.
