### ISSUE TITLE
non-x86 VMs are not supported

### ISSUE THREAD

**Issue by sharkcz** [teemtee/tmt#856]
`tmt` fails to provision a VM on my ppc64le system, because it expects `qemu-kvm` to be present, but this exists only on x86.
````
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1239, in invoke
    return _process_result([])
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tmt/cli.py", line 300, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 1404, in go
    plan.go()
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 765, in go
    step.go()
  File "/usr/lib/python3.9/site-packages/tmt/steps/provision/__init__.py", line 95, in go
    plugin.go()
  File "/usr/lib/python3.9/site-packages/tmt/steps/provision/testcloud.py", line 235, in go
    self._guest.start()
  File "/usr/lib/python3.9/site-packages/tmt/steps/provision/testcloud.py", line 447, in start
    self.instance.spawn_vm()
  File "/usr/lib/python3.9/site-packages/testcloud/instance.py", line 614, in spawn_vm
    self.write_domain_xml()
  File "/usr/lib/python3.9/site-packages/testcloud/instance.py", line 603, in write_domain_xml
    raise TestcloudInstanceError("Neither '/usr/bin/qemu-kvm' nor '/usr/libexec/qemu-kvm' was found.")
testcloud.exceptions.TestcloudInstanceError: Neither '/usr/bin/qemu-kvm' nor '/usr/libexec/qemu-kvm' was found.
````
see https://bugzilla.redhat.com/show_bug.cgi?id=1989891 for all details

**Comment by sharkcz** [comment]
also I have found `Fedora-Cloud-Base-34-1.2.x86_64.qcow2` downloaded on my F-34 ppc64le system, that won't work  ...

**Comment by frantisekz** [comment]
> thanks, if you need non-x86 resources for testing/development, let me know

That'd be awesome for testing, I'll ping you in a week of 20th September after my time off.

In the meantime, I've made some changes in testcloud to support non-x86 (ppc64le for now). One is merged already ( https://pagure.io/testcloud/c/9b978cb95994240a3d83094cf9b179c9822d186f?branch=master ), the other i in a PR form ( https://pagure.io/testcloud/pull-request/115 ). The testing was done in way of emulating ppc64le on x86_64, so I have no idea if it'll work on ppc host. 

In the PR, I am changing the virt type to 'qemu' without kvm if arch != x86_64, I understand that this shouldn't be necessary if the virt arch matches the host arch? If that's the case, I'll change that to switch kvm off only when user forces different arch.

Both changes are now in WIP copr if you wanted to give it a shot (plain testcloud only for now, tmt will need to be adjusted a bit):  https://copr.fedorainfracloud.org/coprs/frantisekz/testcloud-wip/

**Comment by smwltr** [comment]
Hi, I have done a bit of a hack of testcloud to boot an aarch64 qcow2 image - namely messing around with the definition and . @frantisekz , if I want to try your WIP, should I install both tmt and testcloud packages from your repo?

**Comment by frantisekz** [comment]
<Re-posting https://pagure.io/testcloud/issue/120#comment-779486 for visibility>

There is now very preliminary build of testcloud that supports both aarch64 and ppc64le on x86_64 (native, eg. aarch64 on aarch64 might work but I haven't tested that yet). Apart from that, I haven't tested user sessions either, so they may or may not work for now.

The copr is: https://copr.fedorainfracloud.org/coprs/frantisekz/testcloud-wip/

With that build, you can create x86_64/aarch64/ppc64 vms, eg. for Fedora 35:

```
$ testcloud instance create --arch aarch64 --timeout 3600 fedora:35
$ testcloud instance create --arch ppc64le --timeout 3600 fedora:35
```


Be sure to add timeout as the default values won't work too well for emulating a different arch (it doesn't take an hour, just didn't come to some sensible value yet). Also, you may need to wait a while after testcloud tells you the ssh command as the openssh service takes a few more secs to start up.

Also, aarch64 is currently UEFI only, Fedora works with that, I'll dig into it more if there is need for non-UEFI boot. To test both example commands above, you'll need following additional packages: edk2-aarch64 qemu-system-aarch64 qemu-system-ppc

I'll be glad for any testing, the code in the https://pagure.io/testcloud/pull-request/115 is a bit rough as of now, but should work reliably for basic scenarios outlined above.

**Comment by frantisekz** [comment]
@sharkcz can you try the copr mentioned above? There is also patched tmt, so eg.

```
$ tmt run --remove provision -vvv -h virtual -i fedora-35 -a aarch64 finish
$ tmt run --remove provision -vvv -h virtual -i fedora-35 -a ppc64le finish
$ tmt run --remove provision -vvv -h virtual -i fedora-35 -a s390x finish
$ tmt run --remove provision -vvv -h virtual -i fedora-35 -a x86_64 finish
```

should all work on any arch.

The builds included there should support x86_64, ppc64le, s390x and aarch64 (including any combination of host-guest of these arches). I've tested it just on x86 for now, it should theoretically work everywhere.

**Comment by sharkcz** [comment]
`tmt-all` has no broken deps for F-35/s390x, but then fails due a VM config, see bellow. But I believe we are very close :-)
````
[sharkcz@rock-kvmlp-fedora ~]$ tmt run --remove provision -vvv -h virtual -i fedora-35 -a s390x finish
/var/tmp/tmt/run-001

/plans/default
    provision
        how: virtual
        order: 50
        image: fedora-35
        user: root
        memory: 2048 MB
        disk: 10 GB
        connection: session
        arch: s390x
        qcow: Fedora-Cloud-Base-35-1.2.s390x.qcow2
        progress: downloading...
        name: tmt-001-ftFHUUnf
        progress: booting...
libvirt: QEMU Driver error : unsupported configuration: Migratable attribute for host-passthrough CPU is not supported by this QEMU binary
    finish
libvirt: QEMU Driver error : Domain not found: no domain with matching name 'tmt-001-ftFHUUnf'
Failed to stop testcloud instance: Instance doesn't exist: tmt-001-ftFHUUnf
````

**Comment by sharkcz** [comment]
awesome, s390x works :-) I will take a look on ppc64le later
````
[sharkcz@rock-kvmlp-fedora ~]$ tmt run --remove provision -vvv -h virtual -i fedora-35 -a s390x finish
/var/tmp/tmt/run-002

/plans/default
    provision
        how: virtual
        order: 50
        image: fedora-35
        user: root
        memory: 2048 MB
        disk: 10 GB
        connection: session
        arch: s390x
        qcow: Fedora-Cloud-Base-35-1.2.s390x.qcow2
        name: tmt-002-liWXXmew
        progress: booting...
        ip: 127.0.0.1
        port: 10022
        distro: Fedora Linux 35 (Cloud Edition)
        kernel: 5.14.10-300.fc35.s390x
        summary: 1 guest provisioned
    finish
        guest: stopped
        guest: removed
        summary: 0 tasks completed
````

**Comment by lukaszachy** [comment]
Very nice: On my x86_64 laptop - ` tmt run --remove provision -vvv -ddd -h virtual -i centos-stream-9 -a aarch64` boots and works (slooow, but works)

**Comment by thrix** [comment]
HAW COOL!!!!
