### ISSUE TITLE
Detach executor does not support multiline shell scripts

### ISSUE THREAD

**Issue by FrNecas** [teemtee/tmt#860]
While playing around with https://github.com/psss/tmt/pull/855 , I discovered that the following test works with internal executor but errors with detach executor which is a bit inconsistent (and I think according to the specification, we should accept multiline scripts, since it is still a normal string, just written differently):

```
summary: Concise summary describing what the test does
test: |
    /bin/false
    /bin/true
framework: shell
```

Apparently the detach executor requires `run.yaml` to be in the format `key: value` (on one line) and can't handle the case mentioned above.

**Comment by psss** [comment]
This could be fixed either directly in the `run.sh` script or python code would take care of preparing the script to be executed and push it to the guest so that `detach` executor has everything ready and prepare just for simple execution.

**Comment by FrNecas** [comment]
No longer relevant, detach has been removed
