### ISSUE TITLE
Allow control of SSH timeouts by explicit ServerAliveInterval

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#868]
I ran into a test that kicks off `rpmbuild -bb ~/rpmbuild/SPECS/kernel.spec &> log`, and waits for `rpmbuild` to finish. Obviously, as long as `rpmbuild` runs, there's no output, and after some time, tmt/ssh believes the connection has broken down:

```
                out: ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
                out: ::   Build
                out: ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
                out: 
                out: :: [ 14:10:43 ] :: [  BEGIN   ] :: Running 'sed -i "s/# % define buildid .local/%define buildid .LimeKitten/" /test_tmp_root/tmp.H5PZ87jFFs/SPECS/kernel.spec'
                out: :: [ 14:10:43 ] :: [   PASS   ] :: Command 'sed -i "s/# % define buildid .local/%define buildid .LimeKitten/" /test_tmp_root/tmp.H5PZ87jFFs/SPECS/kernel.spec' (Expected 0, got 0)
                out: :: [ 14:10:43 ] :: [  BEGIN   ] :: Running 'sed -i "s/# define buildid .local/%define buildid .LimeKitten/" /test_tmp_root/tmp.H5PZ87jFFs/SPECS/kernel.spec'
                out: :: [ 14:10:43 ] :: [   PASS   ] :: Command 'sed -i "s/# define buildid .local/%define buildid .LimeKitten/" /test_tmp_root/tmp.H5PZ87jFFs/SPECS/kernel.spec' (Expected 0, got 0)
                out: :: [ 14:10:43 ] :: [  BEGIN   ] :: Running 'CC=/usr/bin/gcc rpmbuild --define="_topdir /test_tmp_root/tmp.H5PZ87jFFs" -bb --target=x86_64 --clean /test_tmp_root/tmp.H5PZ87jFFs/SPECS/kernel.spec &> BUILD_LOG'
                out: client_loop: send disconnect: Broken pipe
            Command returned '255'.
            Write file '/WORKDIR/work-ci5l_KrQ/plans/ci/execute/data/tests/Sanity/rebuild-kernel-and-reboot/output.txt'.
            02:11:56 /tests/Sanity/rebuild-kernel-and-reboot [1/1]
```

I'd like to gain control over the SSH timeouts, for example by tmt running `ssh` with explicit and controllable `ServerAliveInterval` and `ServerAliveCountMax`. This keep-alive mechanism is disabled by default (`ServerAliveInterval == 0`), is there any reason against setting them explicitly, to avoid random connection issues like this?

Note that the remote machine was alive and well, and would respond to keep-alive packets. Should it break down, careful setting of both interval and max count should prevent tmt from waiting indefinitely.

**Comment by psss** [comment]
@thrix do you plan to work on this for 1.8 (this week) or shall we postpone?

**Comment by RHEmployee** [comment]
Hello.

1) should be ServerAliveInterval and ServerAliveCountMax part of CLI interface? Should be user pass this via cli?
2) should (as @thrix) mentioned) be configured via configuration provide by user?
If yes, then we can add it to:
https://github.com/psss/tmt/issues/84
3) What seems to be reasonable defaults for tmt?
Defaults for ssh are (according to docs):
ServerAliveInterval - 0 seconds
ServerAliveCountMax - 3

Beware (citation from docs):
The default value is 3. If, for example, ServerAliveInterval (see below) is set to 15 and ServerAliveCountMax is left at the default, if the server becomes unresponsive, ssh will disconnect after approximately 45 seconds.

So changing those values may be not much user friendly in case that remote machine dies.

**Comment by RHEmployee** [comment]
Hello.

Just brain dump:

what aboout some cli interface similar to:
rsync -e which allows something like:
```
-e 'ssh -p 2234'
-e 'ssh -o "ProxyCommand nohup ssh firewall nc -w1 %h %p"
```

or there is another possibility which allows only changes of ssh options (ssh -o).

Possible scenarios:

(%u and %h should be replaced by tmt. Tmt also needs to add some internal stuff (? - keys, etc..)
tmt -e "ssh -o timeout %u@%h" 

Another approach:

tmt --ssh-option "ServerAliveInterval=123" --ssh-option "ServerAliveCountMax=2" ...

**Comment by RHEmployee** [comment]
Very small part of possible solution:
https://github.com/teemtee/tmt/pull/1088

It looks like ssh options needs to be passed per plugin (minute, connection).
For now, only internal minute plugin have support for --ssh-option on MR.

Note: I'm going to add support to connection plugin to MR so stay tuned and review :).

**Comment by RHEmployee** [comment]
Hello. I think this is good for review.
There is missing some parts but I'm not sure how far is config implementation.

**Comment by thrix** [comment]
@RHEmployee thanks for working on this, I believe assignee is you then .. so bumped it
