### ISSUE TITLE
Shall we introduce a uuid for tests?

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#910]
The [fmf identifier](https://fmf.readthedocs.io/en/latest/concept.html#identifiers) can be used as a unique identifier for tests. This works nicely as long as the test is not renamed or moved (both within and outside of the git repository) or a different `url` is used to point to the same git repository.

The uniqueness of the `url` part could be resolved by using something like a canonical version of the git repository `url`. The implementation would not be completely bulletproof but I guess we could cover the most common cases.

For use cases, where the unique id should stay the same even when the test is moved or renamed we would have to probably introduce a dedicated L1 key which would hold the unique value. It could look like this:

```yaml
summary: Verify basic functionality
test: ./test.sh
uuid: 8b633137-fea0-4baf-81a6-73f14ec6501d
```

To brainstomr a little bit more, such a unique identifier could be useful also for tracking historical test results in the ReportPortal. Thoughts? Ideas? Concerns? Let's discuss this more here.

**Comment by lukaszachy** [comment]
I think this could work well. Just to be sure: This value should be aided by `tmt tests lint --fix` and `tmt tests create` commands, user can't be asked to fill it manually

**Comment by thrix** [comment]
One thing for me standing out is weather we should consider this as a required attribute from some later tmt version (2.0? 3.0?). I believe each tmt test should have an ID, ideally in only one form and it should be a required thing.

**Comment by lukaszachy** [comment]
It might be obvious but 'fmf id' is the only way how to get to the test from external sources. So I think these two can live together without any problems.

**Comment by jscotka** [comment]
working on this issue.
https://github.com/teemtee/tmt/pull/1117
