### ISSUE TITLE
Reboot doesn't work with tmt executed with --interactive

### ISSUE THREAD

**Issue by ZelenyMartin** [teemtee/tmt#915]
Tests with reboot are not possible to run with `--interactive` option:

Working:
```
tmt run -vvvaddd execute -h tmt
```
Not working:
```
tmt run -vvvaddd execute -h tmt --interactive
```
Not working case doesn't reboot at all.

**Comment by lukaszachy** [comment]
One of motivations for --interactive is debugging tests e.g. by putting 'bash' into the test code

**Comment by psss** [comment]
@sopos, could you please try to execute once the whole run (all steps) using `tmt run --all`? Just to confirm the problem is in the handling of selected steps.

**Comment by sopos** [comment]
I issued `tmt run -vvvddd provision -h connect --guest sopos-rhel8-brq.usersys.redhat.com plans --default tests --name . discover -f prepare -f report --verbose execute -f --how tmt` and now I even did not get the magic reboot string

**Comment by RHEmployee** [comment]
Hi. About exit codes and specially for exit 222. Just technical note

According to bash man:
 The return value of a simple command is its exit status, or 128+n if the command  is
       terminated by signal n.

https://tldp.org/LDP/abs/html/exitcodes.html says:
There has been an attempt to systematize exit status numbers (see /usr/include/sysexits.h), but this is intended for C and C++ programmers. A similar standard for scripting might be appropriate. The author of this document proposes restricting user-defined exit codes to the range 64 - 113 (in addition to 0, for success), to conform with the C/C++ standard. This would allot 50 valid codes, and make troubleshooting scripts more straightforward. [2] All user-defined exit codes in the accompanying examples to this document conform to this standard, except where overriding circumstances exist, as in Example 9-2.

And from wiki https://en.wikipedia.org/wiki/Exit_status:
When a command is terminated by a signal whose number is N, a shell sets the variable $? to a value greater than 128. Most shells use 128+N, while ksh93 uses 256+N.

So I think that use 222 as a exit code can have some portability (among shells) issues.

**Comment by sopos** [comment]
I tried the tried also `tmt run -vvvddd --all provision --how connect --guest sopos-rhel8-brq plans --default report --verbose execute --how tmt` and I see still the same behaviour.
```
out: :: [ 07:58:18 ] :: [   INFO   ] :: rebooting now
out: MEeCPMMWfyYUx6Lk6mtvuhWmAdVeyTLh:{    "type": "reboot",    "version": "0.2"}
out: /bin/sh: warning: setlocale: LC_ALL: cannot change locale (c): No such file or directory
```
the test, respectively the Reboot library actually calls `rhts-reboot; sleep 3600`.

**Comment by FrNecas** [comment]
@sopos Sorry for not responding earlier, just noticed the discussion here when going through issues :) If `rhts-reboot; sleep 3600` is called, the problem is that tmt doesn't take control before the test finishes. So `rhts-reboot` is called which prints out our magic string for detecting reboot requests but then also `sleep` is called which keeps hanging and tmt doesn't get control back. I guess that ideally `rhts-reboot` would stop the test right away which would pass control back to tmt but I don't know how to achieve that since `rhts-reboot` is a script called within the test so it can't really stop the parent, can it?

**Comment by FrNecas** [comment]
I like the idea that Petr has proposed for detecting the reboot based on presence of a file. I will try to make adjustments to reboot soon-ish :)
