### ISSUE TITLE
Support search for non-matching regular expressions

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#934]
Currently the following can be used to exclude a regular expression from the search result:

    tmt plan ls '^(?!.*irrelevant)'

However, this is not very use friendly. What about introducing a new `--exclude` option which would add a more straightforward way:

    tmt plan ls --exclude irrelevant
    tmt plan ls -x irrelevant

This would be added to the following commands:

    tmt tests ls
    tmt tests show
    tmt tests lint
    tmt tests export

    tmt plans ls
    tmt plans show
    tmt plans lint

    tmt stories ls
    tmt stories show
    tmt stories lint
    tmt stories export
    tmt stories coverage

By adding the new option to the common option group.

**Comment by fernflower** [comment]
Maybe it's obvious and planned for but will mention anyway - it should be possible to combine several `--exclude` options, at least our use cases depend on this.

**Comment by lukaszachy** [comment]
IMHO should be added to discover.fmf too (UC:  `discover -h fmf ...` by using `tmt t ls`)
