### ISSUE TITLE
Prepared files removed for virtual/connect provision

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#964]
If a file is created during the `prepare` step it will be removed during `push()` as it is not present in the local workdir and `rsync --delete` is used to sync files before executing testing. Reproducible with the `/tests/run/worktree` test:

    cd tests/run/worktree/data/prepare
    tmt run -a provision -h virtual

We need to investigate the best approach as simply removing the `--delete` option is not possible because remote files clean up is expected for example when re-running tests using `tmt run discover --force execute --force`.

One possible solution could be to check for the presence of the `--force` option, the other one to only synchronize selected folders (which would also improve the performance). Let's gather ideas here.

**Comment by psss** [comment]
Possible workaround is to use the `TMT_PLAN_DATA` directory to store the created files.
https://tmt.readthedocs.io/en/stable/overview.html#variables

**Comment by adiosnb** [comment]
I've been investigating the issue and have several questions/topics to discuss. After the `prepare` step, only the `TMT_PLAN_DATA` directory is downloaded from a guest to a local computer using the `guest.pull()` method. However, the output of the shell command is stored in the `TMT_TREE` directory, which is used as the `workdir` for tests in `execute` step. I am thinking about these solutions:

1.  What about pulling `TMT_TREE` after prepare step?
2. What about running the `prepare` step in the `TMT_PLAN_DATA` directory?

@psss What do you think?

**Comment by adiosnb** [comment]
> I've been investigating the issue and have several questions/topics to discuss. After the `prepare` step, only the `TMT_PLAN_DATA` directory is downloaded from a guest to a local computer using the `guest.pull()` method. However, the output of the shell command is stored in the `TMT_TREE` directory, which is used as the `workdir` for tests in `execute` step. I am thinking about these solutions:
> 
>     1. What about pulling `TMT_TREE` after prepare step?
> 
>     2. What about running the `prepare` step in the `TMT_PLAN_DATA` directory?
> 
> 
> @psss What do you think?

3rd and preferred option is to improve documentation for now.
